import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {androidVoicePlatform,readAndroidVoiceReturn} from '../src/model/ei-android-voice.ts'
const fixtures=JSON.parse(readFileSync(new URL('./fixtures/voice/android-voice-fixtures.json',import.meta.url),'utf8')) as any[]
test('Android native serializer fixtures retain their own provider and stop scopes',()=>{for(const fixture of fixtures){const context={id:fixture.request.sessionId,scope:fixture.request.scope};try{const value=readAndroidVoiceReturn(JSON.stringify(fixture.response),context);assert.equal(value.processing,'on-device');assert.equal(value.applied,false)}catch(reason){throw Error(fixture.name+': '+String(reason))}}})
test('Android route cannot be used from another origin',()=>{assert.throws(()=>androidVoicePlatform('https://homebase.local'),/unavailable/)})
const named=(name:string)=>structuredClone(fixtures.find(f=>f.name===name))
const responseFor=(name:string,request:any)=>{const value=named(name).response;if(request.action==='poll'){value.cursor=request.cursor;value.events=value.events.filter((e:any)=>e.sequence>request.cursor).slice(0,8);value.nextCursor=request.cursor+value.events.length}return new Response(JSON.stringify(value),{status:200})}
test('Android async availability, transcript and local speech share the same correlated operation path',async()=>{
 const first=named('availability-checking'),context={id:first.request.sessionId,scope:first.request.scope},requests:any[]=[]
 const transport=(async(url,init)=>{assert.equal(init?.method,'GET');assert.equal(init?.body,undefined);const parsed=new URL(String(url));assert.equal(parsed.origin,'https://appassets.androidplatform.net');const request=JSON.parse(parsed.searchParams.get('request')!);requests.push(request);assert.equal(request.sessionId,context.id);assert.deepEqual(request.scope,context.scope);const name=request.action==='availability'?'availability-checking':request.action==='listen'?'listen-starting':request.action==='speak'?'speech-starting':request.action==='end'?'ended':request.operationId===0?'availability-ready':request.operationId===1?'transcript-with-alternative':'speech-ended';return responseFor(name,request)}) as typeof fetch
 const platform=androidVoicePlatform('https://appassets.androidplatform.net',transport);assert.equal(await platform.available('en-US',context),true);assert.equal((platform.availabilityReceipt!(context)!.capabilities as any).recognitionLanguageSupport,'unknown');const recognition=platform.recognition('en-US',context);let heard:any,started=0,ended=0;recognition.onstart=()=>started++;recognition.onresult=(_index,text,detail)=>heard={text,detail};recognition.onend=()=>ended++;await recognition.start();assert.equal(started,1);assert.equal(ended,1);assert.equal(heard.text,'turn left');assert.equal(heard.detail.nativeEvent.detail.otherAlternatives[0].text,'turn lift');const source=named('speech-starting').request.source,text=named('speech-starting').request.text,speech=platform.speech(text,'en-US',{...context,source});let spoken=false;speech.onend=detail=>{spoken=true;assert.equal((detail as any).nativeEvent.detail.userHearingVerified,false)};await speech.start();assert.equal(spoken,true);const terminal=await platform.end!(context);assert.equal((terminal as any).nativeReturn.status,'ended');assert.equal(requests.filter(r=>r.action==='listen').length,1)
})
test('Android rejects contradictory alternative counts, network voices and invented stop proof',()=>{const f=named('transcript-with-alternative'),context={id:f.request.sessionId,scope:f.request.scope};f.response.events.find((e:any)=>e.kind==='transcript').detail.retainedAlternativeCount=99;assert.throws(()=>readAndroidVoiceReturn(JSON.stringify(f.response),context));const voice=named('availability-ready');voice.response.capabilities.voices[0].networkRequired=true;assert.throws(()=>readAndroidVoiceReturn(JSON.stringify(voice.response),context));const end=named('ended');end.response.events.find((e:any)=>e.kind==='ended').detail.hardwareStopVerified=true;assert.throws(()=>readAndroidVoiceReturn(JSON.stringify(end.response),context))})
test('ending Android availability prevents any pending polling or audio start',async()=>{const f=named('availability-checking'),context={id:f.request.sessionId,scope:f.request.scope},requests:any[]=[];const transport=(async(url)=>{const r=JSON.parse(new URL(String(url)).searchParams.get('request')!);requests.push(r);if(r.action==='availability')return responseFor('availability-checking',r);const value=f.response,event={id:`${context.id}/native/2`,sequence:2,parentEventId:`${context.id}/native/1`,sessionId:context.id,scope:context.scope,operationId:0,kind:'ended',observedAt:1,detail:{stopAcknowledgment:'android-cancel-destroy-and-tts-stop-api-return',hardwareStopVerified:false}};return new Response(JSON.stringify({...value,status:'ended',events:[...value.events,event],nextCursor:2}),{status:200})}) as typeof fetch;const platform=androidVoicePlatform('https://appassets.androidplatform.net',transport),pending=platform.available('en-US',context);await new Promise(resolve=>setTimeout(resolve,10));await platform.end!(context);assert.equal(await pending,false);assert.equal(requests.filter(r=>r.action==='poll'||r.action==='listen').length,0)})
test('Android End before availability retains an uninitialized tombstone without opening audio',async()=>{const f=named('ended-before-availability'),context={id:f.request.sessionId,scope:f.request.scope},requests:any[]=[];const platform=androidVoicePlatform('https://appassets.androidplatform.net',(async url=>{const request=JSON.parse(new URL(String(url)).searchParams.get('request')!);requests.push(request);return new Response(JSON.stringify(f.response))}) as typeof fetch);const receipt=await platform.end!(context);assert.equal((receipt as any).nativeReturn.events[0].detail.resourcesCreated,false);assert.equal(await platform.available('en-US',context),false);assert.deepEqual(requests.map(r=>r.action),['end','availability']);const forged=structuredClone(f.response);forged.language='en-US';assert.throws(()=>readAndroidVoiceReturn(JSON.stringify(forged),context))})
test('Android stopping waits for the actual scoped API acknowledgment instead of terminal status alone',async()=>{const f=named('ended-before-availability'),context={id:f.request.sessionId,scope:f.request.scope};let polls=0;const platform=androidVoicePlatform('https://appassets.androidplatform.net',(async url=>{const request=JSON.parse(new URL(String(url)).searchParams.get('request')!);if(request.action==='end')return new Response(JSON.stringify({...f.response,language:'en-US',status:'stopping',events:[],cursor:0,nextCursor:0}));polls++;assert.equal(request.operationId,0);assert.equal(request.cursor,0);return new Response(JSON.stringify(f.response))}) as typeof fetch);await platform.end!(context);assert.equal(polls,1)})
