import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {readEIDiscoveryReturn,proposeEIDiscoveryBatch,readEIDiscoverySteps,requestEIHomebaseDiscovery} from '../src/model/ei-discovery.ts'
import {observeEIBrowserDiscovery} from '../src/model/ei-discovery-providers.ts'
import {createEILedger,executeEI,verifyEI,commitEI,proposeEI,advanceEI,exportEILedger,type EILedger,type EIProposal} from '../src/model/ei-engine.ts'
const fixtures=(name:string)=>JSON.parse(readFileSync(new URL(`./fixtures/discovery/${name}.json`,import.meta.url),'utf8')) as any[]
const scope=(v:any)=>({requestId:v.requestId,address:v.address,revision:v.revision})
const root=()=>createEILedger({records:[{address:'device',value:'User-owned local field',source:{id:'owner',text:'User-owned local field'}}]})
function commit(ledger:EILedger,p:EIProposal){const e=executeEI(ledger,p);if(e.status!=='staged')throw Error('not staged');return commitEI(ledger,verifyEI(e,{kind:'rendered-address-values',values:e.expected})).ledger}
test('synthetic native fixtures validate without promoting metadata to global knowledge',()=>{for(const name of ['windows-synthetic','selected-folder-fixture','linux-synthetic'])for(const v of fixtures(name)){const r=readEIDiscoveryReturn(JSON.stringify(v),scope(v));assert.equal(r.value.applied,false);assert.equal(r.value.contentRead,false);assert.equal(r.raw,JSON.stringify(v))}})
test('incremental batches attach stable targets and new child steps to the one user root',async()=>{
 let l=root();const input=fixtures('windows-synthetic');for(const batch of input){const returned=readEIDiscoveryReturn(JSON.stringify(batch),scope(batch)),before=exportEILedger(l),p=await proposeEIDiscoveryBatch(l,'device',returned);assert.equal(exportEILedger(l),before);assert.ok(p.proposal);l=commit(l,p.proposal);assert.ok(l.records.some(r=>r.address===p.focusAddress));assert.equal((await proposeEIDiscoveryBatch(l,'device',returned)).proposal,null)}
 const steps=readEIDiscoverySteps(l);assert.equal(steps.length,input.length);assert.equal(steps[0].data.parentStep,null);if(steps.length>1)assert.equal(steps[1].data.parentStep,steps[0].address);assert.ok(steps.every(s=>s.data.wholeComputerComplete===false&&s.data.simultaneousPhysicalObservation===false));assert.ok(steps[0].data.differences.every((d:any)=>d.hadBefore===false&&d.valueDifferent===false));assert.ok(steps[0].data.childOccurrences.every((c:any)=>c.parentOccurrence===steps[0].address));assert.equal(l.records.filter(r=>!r.parents.length).length,1)
})
test('equal observed values retain a new occurrence without a fabricated value change',async()=>{
 let l=root();const first=fixtures('windows-synthetic')[0],a=readEIDiscoveryReturn(JSON.stringify(first),scope(first)),p=await proposeEIDiscoveryBatch(l,'device',a);l=commit(l,p.proposal!);const identities=l.records.filter(r=>r.address.startsWith('observed/')).map(r=>r.address)
 const next={...first,requestId:'another-request',scanId:'another-scan'},b=readEIDiscoveryReturn(JSON.stringify(next),scope(next)),q=await proposeEIDiscoveryBatch(l,'device',b);l=commit(l,q.proposal!);assert.deepEqual(l.records.filter(r=>r.address.startsWith('observed/')).map(r=>r.address),identities);const step=readEIDiscoverySteps(l).at(-1)!;assert.ok(step.data.differences.every((d:any)=>d.hadBefore&&d.valueDifferent===false));assert.notEqual(step.address,p.stepAddress)
})
test('folder hierarchy follows actual returned parents and refuses unknown parents',async()=>{
 let l=root();for(const batch of fixtures('selected-folder-fixture')){const p=await proposeEIDiscoveryBatch(l,'device',readEIDiscoveryReturn(JSON.stringify(batch),scope(batch)));l=commit(l,p.proposal!)}
 const records=l.records.filter(r=>r.is.source.realm==='returned-device-observation');assert.ok(records.length>1);for(const r of records){const item=JSON.parse(r.is.source.text);if(item.parentKey!==null){const p=l.records.find(p=>p.address===r.parents[0])!;assert.equal(JSON.parse(p.is.source.text).key,item.parentKey)}}
 const invalid=fixtures('windows-synthetic')[0];invalid.observations[0].parentKey='not-returned';await assert.rejects(proposeEIDiscoveryBatch(root(),'device',readEIDiscoveryReturn(JSON.stringify(invalid),scope(invalid))),/before its parent/)
})
test('stale scope, reordered/conflicting replay and foreign source ownership are not overwritten',async()=>{
 let l=root();const batch=fixtures('windows-synthetic')[0],ret=readEIDiscoveryReturn(JSON.stringify(batch),scope(batch)),p=await proposeEIDiscoveryBatch(l,'device',ret);l=commit(l,p.proposal!);const changed={...batch,platform:'changed'};await assert.rejects(proposeEIDiscoveryBatch(l,'device',readEIDiscoveryReturn(JSON.stringify(changed),scope(changed))),/replayed batch differs/)
 const late={...batch,sequence:4,nextCursor:5,scanId:'late'};await assert.rejects(proposeEIDiscoveryBatch(l,'device',readEIDiscoveryReturn(JSON.stringify(late),scope(late))),/reordered/)
 const target=l.records.find(r=>r.address.startsWith('observed/'))!,source={id:'my-edit',text:'My edit'};l=advanceEI(l,proposeEI(l,{id:'manual',producer:'device',input:source,candidates:[{id:'one',label:'Manual edit',owner:'engine',source,conditions:[],patches:[{address:target.address,value:'My edit',source}]}]})).ledger
 const newScan={...batch,requestId:'new-scan',scanId:'new-scan'};await assert.rejects(proposeEIDiscoveryBatch(l,'device',readEIDiscoveryReturn(JSON.stringify(newScan),scope(newScan))),/different retained source owner/);assert.equal(l.records.find(r=>r.address===target.address)!.is.value,'My edit')
 const moved={...batch,revision:99};await assert.rejects(proposeEIDiscoveryBatch(l,'device',readEIDiscoveryReturn(JSON.stringify(moved),scope(moved))),/scope changed/)
})
test('capacity is explicit and the exact pending return survives unchanged',async()=>{
 const l=createEILedger({records:Array.from({length:255},(_,i)=>({address:i?`node/${i}`:'device',value:String(i),source:{id:`s${i}`,text:String(i)}}))}),batch=fixtures('windows-synthetic')[0],r=readEIDiscoveryReturn(JSON.stringify(batch),scope(batch)),before=exportEILedger(l);await assert.rejects(proposeEIDiscoveryBatch(l,'device',r),/capacity/);assert.equal(exportEILedger(l),before);assert.equal(r.raw,JSON.stringify(batch))
})
test('common browser provider returns only actual supplied runtime observations through the same admission',async()=>{
 const scope={requestId:'browser-test',address:'device',revision:0},batches=observeEIBrowserDiscovery(scope,{userAgent:'Actual fixture input',language:'en',platform:'test',hardwareConcurrency:4},{width:800,height:600,colorDepth:24},'2026-10-02T00:00:00.000Z');assert.equal(batches[0].carrier,'web');const p=await proposeEIDiscoveryBatch(root(),'device',batches[0]);assert.ok(p.proposal);assert.ok(batches[0].value.diagnostics.some(d=>d.code.includes('not-exposed')))
})
test('unexpected source effects and wrong carrier route reject before admission',async()=>{
 const v=fixtures('windows-synthetic')[0];for(const key of ['contentRead','credentialsRead','externalUpload','applied'])assert.throws(()=>readEIDiscoveryReturn(JSON.stringify({...v,[key]:true}),scope(v)),/scope/)
 let called=false;await assert.rejects(requestEIHomebaseDiscovery('https://example.com',{...scope(v),action:'start',kind:'system'},undefined,async()=>{called=true;return new Response('{}')}),/unavailable/);assert.equal(called,false);await assert.rejects(proposeEIDiscoveryBatch(root(),'device',JSON.parse(JSON.stringify(readEIDiscoveryReturn(JSON.stringify(v),scope(v))))),/unvalidated/)
})

test('edited provider roots cannot silently acquire new provider children',async()=>{
 const batch=fixtures('windows-synthetic')[0],ret=readEIDiscoveryReturn(JSON.stringify(batch),scope(batch));let l=root();l=commit(l,(await proposeEIDiscoveryBatch(l,'device',ret)).proposal!);const provider=l.records.find(r=>r.is.source.realm==='discovery-provider')!,source={id:'provider-edit',text:'My own provider meaning'};l=advanceEI(l,proposeEI(l,{id:'edit-provider',producer:'device',input:source,candidates:[{id:'edit',label:'Edit',owner:'engine',source,conditions:[],patches:[{address:provider.address,value:'Edited root',source}]}]})).ledger;const before=exportEILedger(l),next={...batch,requestId:'another',scanId:'another'};await assert.rejects(proposeEIDiscoveryBatch(l,'device',readEIDiscoveryReturn(JSON.stringify(next),scope(next))),/root has a different retained source owner/);assert.equal(exportEILedger(l),before)
})
test('synthetic carrier conformance preserves supplied values and parent relations with explicit provenance',async()=>{
 const base=fixtures('selected-folder-fixture')[0],at=base.observedAt,observations=[{key:'root',parentKey:null,kind:'folder',label:'Fixture root',metadata:{fixture:true},source:'selected-root-filesystem',observedAt:at},{key:'root/child',parentKey:'root',kind:'file',label:'Fixture child',metadata:{fixture:true,size:7},source:'selected-root-filesystem',observedAt:at}];const normalized=[]
 for(const carrier of ['homebase','web','android'] as const){const batch={...base,schema:carrier==='homebase'?'field.homebase.discovery.v1':'ei.provider.discovery.v1',status:'complete',sequence:0,nextCursor:null,root:{key:'root',label:'Fixture root'},observations,progress:{visited:2,returned:2,skipped:0,queued:0}},raw=JSON.stringify(batch),returned=readEIDiscoveryReturn(raw,scope(batch),carrier),initial=root(),one=await proposeEIDiscoveryBatch(initial,'device',returned),two=await proposeEIDiscoveryBatch(initial,'device',returned);assert.deepEqual(one,two);const ledger=commit(initial,one.proposal!),records=ledger.records.filter(r=>r.is.source.realm==='returned-device-observation');normalized.push(records.map(record=>({key:JSON.parse(record.is.source.text).key,value:record.is.value,parent:ledger.records.find(parent=>parent.address===record.parents[0])?.is.source.realm==='returned-device-observation'?JSON.parse(ledger.records.find(parent=>parent.address===record.parents[0])!.is.source.text).key:'user-provider'})));const step=readEIDiscoverySteps(ledger)[0];assert.equal(step.data.raw,raw);assert.equal(step.data.carrier,carrier);assert.equal(step.data.userRoot,'device');assert.equal(step.data.logicalSnapshotRevision,initial.revision)}
 assert.deepEqual(normalized[0],normalized[1]);assert.deepEqual(normalized[1],normalized[2])
})
