import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {createEILedger,chooseEI,executeEI,verifyEI,commitEI} from '../src/model/ei-engine.ts'
import {createEIDeviceFieldRecords,proposeEIDeviceEncounter,proposeEIDeviceWorkspace} from '../src/model/ei-device-field.ts'
import {describeEIBrowserFiles} from '../src/model/ei-browser-encounter.ts'
import {validateEIDeviceEnvelope,deviceEncounterRows,readEIDeviceEncounter} from '../src/model/ei-device-encounter.ts'
test('declared collections are not fabricated discovered inventory',()=>{const r=createEIDeviceFieldRecords();assert.equal(r.length,5);assert.ok(r.slice(1).every(record=>record.value.includes('Awaiting an explicit device encounter')))})
test('device encounter retains exact source and duplicate return cannot create a second entry',()=>{let ledger=createEILedger({records:createEIDeviceFieldRecords()});const item={id:'r',kind:'hardware' as const,label:'Sensor',sourceText:'{"known":true}',realm:'native-return',locator:'request-1',producer:{address:'device/hardware',revision:0}},p=proposeEIDeviceEncounter(ledger,item,'retain')!,e=executeEI(ledger,p,chooseEI(p,p.candidates[0].candidate.id));if(e.status!=='staged')throw Error('not staged');ledger=commitEI(ledger,verifyEI(e,{kind:'rendered-address-values',values:e.expected})).ledger;assert.equal(proposeEIDeviceEncounter(ledger,item,'retry'),null);assert.throws(()=>proposeEIDeviceEncounter(ledger,{...item,sourceText:'different'},'conflict'));assert.throws(()=>proposeEIDeviceEncounter(ledger,{...item,id:'new',producer:{address:'device/hardware',revision:1}},'stale'))})
test('older sessions can explicitly add device workspace while retaining original root',()=>{const l=createEILedger({records:[{address:'user-root',value:'original',source:{id:'original',text:'original'}}]}),p=proposeEIDeviceWorkspace(l,'user-root','add')!,e=executeEI(l,p,chooseEI(p,p.candidates[0].candidate.id));if(e.status!=='staged')throw Error('not staged');const r=commitEI(l,verifyEI(e,{kind:'rendered-address-values',values:e.expected}));assert.equal(r.ledger.records[0].address,'user-root');assert.deepEqual(r.ledger.records.find(record=>record.address==='device')?.parents,['user-root'])})
test('browser directory encounters preserve exact paths but make no file-content claim',()=>{const file={name:' a.txt',size:12,type:'',lastModified:0,webkitRelativePath:'chosen/ a.txt'},rows=describeEIBrowserFiles([file],{address:'device/folders',revision:0},'batch',true);assert.equal(rows[0].kind,'folders');assert.equal(JSON.parse(rows[1].sourceText).relativePath,'chosen/ a.txt');assert.equal(JSON.parse(rows[1].sourceText).contentRead,false);assert.throws(()=>describeEIBrowserFiles(Array(65).fill(file),{address:'device',revision:0},'batch'))})
test('all nine native serializer fixtures bind actual action source and unobserved software remains absent',async()=>{const fixtures=JSON.parse(await readFile(new URL('./fixtures/device-encounters.json',import.meta.url),'utf8'));assert.equal(fixtures.length,9);for(const value of fixtures){const a=value.action,scope={address:a?.address??'field:synthetic-fixture',revision:a?.revision??7},op=a?.requestId===value.requestId?a.op:'status';const checked=validateEIDeviceEnvelope(value,value.requestId,scope,op,a?.requestId);assert.equal(checked,value);assert.throws(()=>validateEIDeviceEnvelope(value,'wrong',scope,op,a?.requestId));if(a?.result?.kind==='software')assert.equal(deviceEncounterRows({scope,raw:JSON.stringify(value),value}).length,[a.result.ownApp,a.result.webViewProvider].filter(p=>p.state==='returned').length)}})
test('native encounters cannot hit ordinary web or Windows origin',async()=>{let calls=0;await assert.rejects(readEIDeviceEncounter({address:'device',revision:0},'https://homebase.local','r','software',{},async()=>{calls++;return new Response('')}));assert.equal(calls,0)})
