import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createEILedger,executeEI,chooseEI,verifyEI,commitEI,type EILedger,type EIProposal} from '../src/model/ei-engine.ts'
import {proposeGuideStep} from '../src/model/ei-guide-steps.ts'
import {deriveEISeedMirrors,projectEIEnvironmentHorizon,fitEIEnvironmentObjects} from '../src/model/ei-field-environment.ts'
function commit(l:EILedger,p:EIProposal){const e=executeEI(l,p,chooseEI(p,p.candidates[0].candidate.id));if(e.status!=='staged')throw Error('not staged');return commitEI(l,verifyEI(e,{kind:'rendered-address-values',values:e.expected})).ledger}
test('eligible mirror preserves original seed identity and actual declared context',()=>{let l=createEILedger({records:[{address:'goal',value:'Supplied goal',source:{id:'g',text:'Supplied goal'}},{address:'condition',value:'ready',source:{id:'c',text:'ready'}}]});l=commit(l,proposeGuideStep(l,{id:'s',intentAddress:'goal',action:'Supplied possible action',expected:'Expected',conditions:[{address:'condition',equals:'ready'}]}));const before=JSON.stringify(l),mirrors=deriveEISeedMirrors(l);assert.equal(mirrors.length,1);assert.equal(mirrors[0].address,'guide/steps/s');assert.equal(mirrors[0].environmentAddress,'goal');assert.equal(mirrors[0].realized,false);assert.equal(mirrors[0].physicalPlacement,null);assert.equal(JSON.stringify(l),before)})
test('missing or failed prerequisites never produce plantable mirrors',()=>{let l=createEILedger({records:[{address:'goal',value:'Goal',source:{id:'g',text:'Goal'}}]});l=commit(l,proposeGuideStep(l,{id:'s',intentAddress:'goal',action:'Maybe',expected:'Expected',conditions:[{address:'missing',equals:'ready'}]}));assert.equal(deriveEISeedMirrors(l).length,0)})
test('horizon is a finite observer projection with no source state advancement',()=>{const a=projectEIEnvironmentHorizon({x:0,y:0,zoom:2},{width:1200,height:800},0),b=projectEIEnvironmentHorizon({x:0,y:0,zoom:2},{width:1200,height:800},.5);assert.ok(Math.abs(a.horizonY-112)<1e-9);assert.ok(b.horizonY>a.horizonY);assert.equal(a.modelAdvanced,false);assert.throws(()=>projectEIEnvironmentHorizon({x:0,y:0,zoom:0},{width:1200,height:800},0))})

test('lower horizon reserves sky across pan, zoom and resize while preserving visible ground',()=>{for(const zoom of [.1,1,8])for(const height of [320,800])for(const pitch of [-20,0,.18,20]){const view={x:27,y:-19,zoom},result=projectEIEnvironmentHorizon(view,{width:1200,height},pitch),fraction=(result.horizonY-(view.y-height/(2*zoom)))/(height/zoom);assert.ok(fraction>=.6-1e-9&&fraction<=.95+1e-9);if(pitch===0)assert.ok(Math.abs(fraction-.78)<1e-9);assert.equal(result.modelAdvanced,false)}})

test("the single environment covers viewport corners through a full observer turn",()=>{for(const width of [320,1200])for(const height of [320,800])for(const zoom of [.1,1,8]){const view={x:27,y:-19,zoom},result=projectEIEnvironmentHorizon(view,{width,height},.18),numbers=result.skyPath.match(/-?\d+(?:\.\d+)?/g)!.map(Number),left=numbers[0],top=numbers[1],right=numbers[2];for(let angle=0;angle<Math.PI*2;angle+=Math.PI/12)for(const x of [-width/2,width/2])for(const y of [-height/2,height/2]){const rx=view.x+(x*Math.cos(angle)-y*Math.sin(angle))/zoom,ry=view.y+(x*Math.sin(angle)+y*Math.cos(angle))/zoom;assert.ok(rx>left&&rx<right);assert.ok(ry>top&&ry<view.y+Math.hypot(width,height)/zoom)}}})

test("automatic fit keeps addressed objects above floating dock and below active context",()=>{for(const height of [320,540,800])for(const width of [320,1280]){const bounds={left:-300,right:300,top:-400,bottom:400},view=fitEIEnvironmentObjects(bounds,{width,height}),screenTop=(bounds.top-view.y)*view.zoom+height/2,screenBottom=(bounds.bottom-view.y)*view.zoom+height/2;assert.ok(screenTop>=Math.min(90,height*.15)-1e-9);assert.ok(screenBottom<=height-Math.min(150,Math.max(82,height*.2))+1e-9)}})
