import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createEILedger,executeEI,chooseEI,verifyEI,commitEI,type EILedger,type EIProposal} from '../src/model/ei-engine.ts'
import {proposeGuideStep} from '../src/model/ei-guide-steps.ts'
import {deriveEISeedMirrors,projectEIEnvironmentHorizon} from '../src/model/ei-field-environment.ts'
function commit(l:EILedger,p:EIProposal){const e=executeEI(l,p,chooseEI(p,p.candidates[0].candidate.id));if(e.status!=='staged')throw Error('not staged');return commitEI(l,verifyEI(e,{kind:'rendered-address-values',values:e.expected})).ledger}
test('eligible mirror preserves original seed identity and actual declared context',()=>{let l=createEILedger({records:[{address:'goal',value:'Supplied goal',source:{id:'g',text:'Supplied goal'}},{address:'condition',value:'ready',source:{id:'c',text:'ready'}}]});l=commit(l,proposeGuideStep(l,{id:'s',intentAddress:'goal',action:'Supplied possible action',expected:'Expected',conditions:[{address:'condition',equals:'ready'}]}));const before=JSON.stringify(l),mirrors=deriveEISeedMirrors(l);assert.equal(mirrors.length,1);assert.equal(mirrors[0].address,'guide/steps/s');assert.equal(mirrors[0].environmentAddress,'goal');assert.equal(mirrors[0].realized,false);assert.equal(mirrors[0].physicalPlacement,null);assert.equal(JSON.stringify(l),before)})
test('missing or failed prerequisites never produce plantable mirrors',()=>{let l=createEILedger({records:[{address:'goal',value:'Goal',source:{id:'g',text:'Goal'}}]});l=commit(l,proposeGuideStep(l,{id:'s',intentAddress:'goal',action:'Maybe',expected:'Expected',conditions:[{address:'missing',equals:'ready'}]}));assert.equal(deriveEISeedMirrors(l).length,0)})
test('horizon is a finite observer projection with no source state advancement',()=>{const a=projectEIEnvironmentHorizon({x:0,y:0,zoom:2},{width:1200,height:800},0),b=projectEIEnvironmentHorizon({x:0,y:0,zoom:2},{width:1200,height:800},.5);assert.equal(a.horizonY,0);assert.ok(b.horizonY>a.horizonY);assert.equal(a.modelAdvanced,false);assert.throws(()=>projectEIEnvironmentHorizon({x:0,y:0,zoom:0},{width:1200,height:800},0))})
