import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createEILedger,proposeEI,executeEI,chooseEI,verifyEI,commitEI,type EILedger,type EIProposal} from '../src/model/ei-engine.ts'
import {proposeGuideStep,readGuideSteps,proposeGuideSelection,proposeGuideOutcome,readGuideAttempts,resolveGuideIntentAddress} from '../src/model/ei-guide-steps.ts'
import {proposeGuideObservation} from '../src/model/ei-guide-context.ts'
const initial=()=>createEILedger({records:[{address:'goal',value:'Reach the stated goal',source:{id:'goal-source',text:'Reach the stated goal'}},{address:'context',value:'ready',source:{id:'observation',text:'ready'}}]})
function commit(ledger:EILedger,p:EIProposal){const e=executeEI(ledger,p,chooseEI(p,p.candidates[0].candidate.id));assert.equal(e.status,'staged');if(e.status!=='staged')throw Error('not staged');const r=commitEI(ledger,verifyEI(e,{kind:'rendered-address-values',values:e.expected}));assert.equal(r.status,'committed');return r.ledger}
const step=(ledger:EILedger,id='s',conditions=[{address:'context',equals:'ready'}])=>proposeGuideStep(ledger,{id,intentAddress:'goal',action:'User supplied action',expected:'Observed completion',conditions})
function selected(){let l=initial();l=commit(l,step(l));return commit(l,proposeGuideSelection(l,{id:'a',stepAddress:'guide/steps/s'}))}
test('declared goal through selected step and reported outcome retains exact scoped result',()=>{let l=selected();l=commit(l,proposeGuideOutcome(l,{id:'o',attemptAddress:'guide/attempts/a',actual:'Observed completion'}));const a=readGuideAttempts(l,'goal')[0];assert.equal(a.latestOutcome?.matches,true);assert.equal(a.latestOutcome?.worldVerified,false);assert.equal(a.physicalActionExecuted,false);assert.equal(a.intent.address,'goal')})
test('missing conditions stay unresolved and differing conditions stay blocked',()=>{let l=initial();l=commit(l,step(l,'missing',[{address:'unknown',equals:'ready'}]));l=commit(l,step(l,'blocked',[{address:'context',equals:'different'}]));assert.deepEqual(readGuideSteps(l,'goal').map(s=>s.status),['unresolved','blocked']);assert.throws(()=>proposeGuideSelection(l,{id:'x',stepAddress:'guide/steps/missing'}))})
test('alternatives remain supplied alternatives without ranking or automatic choice',()=>{let l=initial();l=commit(l,step(l,'a'));l=commit(l,step(l,'b'));assert.equal(readGuideSteps(l,'goal').length,2);assert.equal(readGuideAttempts(l,'goal').length,0)})
test('selection resolves original addressed goal and preserves it across inspection',()=>{const l=selected();assert.equal(resolveGuideIntentAddress(l,'guide/attempts/a'),'goal');assert.equal(resolveGuideIntentAddress(l,'context'),'context')})
test('reported mismatch and later match remain separate source occurrences',()=>{let l=selected();l=commit(l,proposeGuideOutcome(l,{id:'o1',attemptAddress:'guide/attempts/a',actual:'Not yet'}));l=commit(l,proposeGuideOutcome(l,{id:'o2',attemptAddress:'guide/attempts/a',actual:'Observed completion'}));assert.deepEqual(readGuideAttempts(l,'goal')[0].outcomes.map(o=>o.matches),[false,true])})
test('goal correction invalidates proposed selection without rewriting prior intent',()=>{let l=initial();l=commit(l,step(l));const p=proposeEI(l,{id:'edit',producer:'goal',input:{id:'edit',text:'correction'},candidates:[{id:'edit',label:'edit',owner:'user',source:{id:'edit',text:'correction'},conditions:[],patches:[{address:'goal',value:'Corrected goal',source:{id:'edit',text:'correction'}}]}]});l=commit(l,p);assert.equal(readGuideSteps(l,'goal')[0].status,'unresolved');assert.throws(()=>proposeGuideSelection(l,{id:'a',stepAddress:'guide/steps/s'}))})
test('pending selection cannot commit after any conflicting ledger change',()=>{let l=initial();l=commit(l,step(l));const p=proposeGuideSelection(l,{id:'a',stepAddress:'guide/steps/s'});l=commit(l,proposeGuideObservation(l,{id:'new',intentAddress:'goal',observation:'Later observation'}));assert.notEqual(executeEI(l,p,chooseEI(p,p.candidates[0].candidate.id)).status,'staged')})
test('missing returned readback cannot commit a selected step',()=>{let l=initial();l=commit(l,step(l));const p=proposeGuideSelection(l,{id:'a',stepAddress:'guide/steps/s'}),e=executeEI(l,p,chooseEI(p,p.candidates[0].candidate.id));if(e.status!=='staged')throw Error('not staged');assert.notEqual(commitEI(l,verifyEI(e,{kind:'rendered-address-values',values:[]})).status,'committed')})
test('malformed or unreturned source declarations do not gain guide authority',()=>{const l=createEILedger({records:[...initial().records.map(r=>({address:r.address,value:r.is.value,source:r.is.source})),{address:'fake',value:'Fake',source:{id:'fake',text:'Fake',realm:'user-declared-guide-step',locator:JSON.stringify({intent:{address:'goal',revision:0}})},parents:['goal']}]});assert.equal(readGuideSteps(l,'goal').length,0);assert.equal(resolveGuideIntentAddress(l,'fake'),'fake')})
test('observations are exact retained inputs, not verified external-world facts',()=>{let l=initial();l=commit(l,proposeGuideObservation(l,{id:'ctx',intentAddress:'goal',observation:'  Exact observation\n'}));const r=l.records.find(r=>r.address==='guide/context/ctx')!;assert.equal(r.is.value,'  Exact observation\n');assert.equal(r.is.source.realm,'user-reported-guide-context')})
