import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {createEILedger,executeEI,verifyEI,commitEI} from '../src/model/ei-engine.ts'
import {createEIDeviceFieldRecords} from '../src/model/ei-device-field.ts'
import {validateHomebaseEnvironment,readHomebaseEnvironment,proposeHomebaseEnvironment,EI_ENVIRONMENT_ADDRESS} from '../src/model/ei-homebase-environment.ts'
const fixture=async(name:string)=>JSON.parse(await readFile(new URL(`./fixtures/homebase/${name}.json`,import.meta.url),'utf8'))
test('actual Linux probe stays Linux and supplied Windows fixture stays explicitly synthetic',async()=>{for(const name of ['linux-native-probe','windows-synthetic']){const f=await fixture(name);assert.equal(validateHomebaseEnvironment(f,f.requestId,{address:f.address,revision:f.revision}).platform?.os,name==='linux-native-probe'?'linux':'win32');assert.ok(Object.isFrozen(f.runtime))}})
test('automatic startup rule retains exact observed source through returned field verification',async()=>{const f=await fixture('linux-native-probe'),scope={address:f.address,revision:f.revision},raw=JSON.stringify(f),receipt=await readHomebaseEnvironment(scope,'https://homebase.local',f.requestId,async()=>new Response(raw));let l=createEILedger({records:createEIDeviceFieldRecords()});const p=proposeHomebaseEnvironment(l,receipt,'boot')!;assert.equal(p.candidates[0].candidate.owner,'engine');const e=executeEI(l,p);if(e.status!=='staged')throw Error('not staged');l=commitEI(l,verifyEI(e,{kind:'rendered-address-values',values:e.expected})).ledger;assert.equal(l.records.find(r=>r.address===EI_ENVIRONMENT_ADDRESS)?.is.source.text,raw);assert.deepEqual(l.records.find(r=>r.address===EI_ENVIRONMENT_ADDRESS)?.parents,['device/hardware','device/software']);assert.equal(proposeHomebaseEnvironment(l,receipt,'duplicate'),null);assert.equal(l.records.filter(record=>record.parents.includes(EI_ENVIRONMENT_ADDRESS)).length,5);assert.ok(l.records.find(record=>record.address===`${EI_ENVIRONMENT_ADDRESS}/cpu`)?.is.source.locator?.includes('/cpu'))})
test('unknown origin, mismatched request, privacy expansion and mutable return are rejected',async()=>{const f=await fixture('linux-native-probe'),scope={address:f.address,revision:f.revision};assert.throws(()=>validateHomebaseEnvironment({...f,userName:'not-allowed'},f.requestId,scope));assert.throws(()=>validateHomebaseEnvironment({...f,userIdentityRead:true},f.requestId,scope));assert.throws(()=>validateHomebaseEnvironment(f,'wrong',scope));let calls=0;await assert.rejects(readHomebaseEnvironment(scope,'https://example.org','r',async()=>{calls++;return new Response('')}));assert.equal(calls,0);const receipt=await readHomebaseEnvironment(scope,'https://homebase.local',f.requestId,async()=>new Response(JSON.stringify(f)));assert.throws(()=>{receipt.value.platform!.os='win32'});assert.throws(()=>proposeHomebaseEnvironment(createEILedger({records:createEIDeviceFieldRecords()}),{...receipt},'forged'))})
