import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync,readdirSync} from 'node:fs'
import {homebaseVoicePlatform,readHomebaseVoiceReturn} from '../src/model/ei-homebase-voice.ts'
const dir=new URL('./fixtures/voice/',import.meta.url),fixture=(name:string)=>JSON.parse(readFileSync(new URL(name+'.json',dir),'utf8'))
const first=fixture('availability'),context={id:first.sessionId,scope:first.scope}
test('all production-serializer synthetic voice fixtures preserve exact scoped metadata',()=>{for(const file of readdirSync(dir).filter(file=>file!=='android-voice-fixtures.json')){const raw=readFileSync(new URL(file,dir),'utf8'),parsed=JSON.parse(raw),value=readHomebaseVoiceReturn(raw,{id:parsed.sessionId,scope:parsed.scope});assert.equal(value.processing,'on-device');assert.equal(value.applied,false);assert.equal(value.rawAudioRetained,false)}})
test('native voice rejects mismatched scope, remote processing, forged providers and event gaps',()=>{for(const changed of [{...first,externalUpload:true},{...first,scope:{...first.scope,revision:9}},{...first,processing:'remote'},{...first,applied:true},{...first,nextCursor:55}])assert.throws(()=>readHomebaseVoiceReturn(JSON.stringify(changed),context));const forged=structuredClone(first);forged.capabilities.recognizers[0].id='REMOTE';assert.throws(()=>readHomebaseVoiceReturn(JSON.stringify(forged),context));const event=structuredClone(first);event.events[0].sequence=99;assert.throws(()=>readHomebaseVoiceReturn(JSON.stringify(event),context))})
test('native adapter cannot send to another origin',()=>{assert.throws(()=>homebaseVoicePlatform('https://example.com'),/unavailable/)})
test('native adapter waits for real listening, delivers exact transcript once and awaits cancellation',async()=>{
 const requests:any[]=[],responses=[fixture('availability'),fixture('starting'),fixture('transcript')];let release!:(response:Response)=>void;const transport=(async(_url,init)=>{const request=JSON.parse(String(init?.body));requests.push(request);if(request.action==='cancel')return await new Promise<Response>(resolve=>release=resolve);const response=responses.shift();assert.ok(response);if(request.action==='poll'){response.cursor=request.cursor;response.events=response.events.filter((e:any)=>e.sequence>request.cursor);response.nextCursor=request.cursor+response.events.length}return new Response(JSON.stringify(response),{status:200})}) as typeof fetch
 const platform=homebaseVoicePlatform('https://homebase.local',transport);assert.equal(await platform.available('en-US',context),true);const operation=platform.recognition('en-US',context),transcripts:string[]=[];let started=0;operation.onstart=()=>{started++};operation.onresult=(_index,text)=>transcripts.push(text);const running=operation.start();await new Promise(resolve=>setTimeout(resolve,190));assert.equal(started,1);assert.equal(transcripts.length,1);assert.equal(transcripts[0],fixture('transcript').events.find((e:any)=>e.kind==='transcript').detail.text);let stopped=false;const ending=Promise.resolve(operation.abort()).then(()=>stopped=true);await new Promise(resolve=>setTimeout(resolve,0));assert.equal(stopped,false);release(new Response(JSON.stringify(fixture('cancelled')),{status:200}));await ending;await running;assert.equal(stopped,true);assert.ok(requests.every(r=>r.sessionId===context.id&&JSON.stringify(r.scope)===JSON.stringify(context.scope)));assert.equal(requests.filter(r=>r.action==='listen').length,1)
})
test('bounded native failure preserves its returned code without treating HTTP failure as success',async()=>{const platform=homebaseVoicePlatform('https://homebase.local',async()=>new Response(JSON.stringify({error:'foreground-required'}),{status:400}));await assert.rejects(platform.available('en-US',context),/foreground-required \(400\)/)})
test('HOMEBASE no-child-active End is a scoped resource acknowledgment, not a fabricated process exit',async()=>{const returned=fixture('lease-end'),event=returned.events.at(-1);event.detail.acknowledgment='no-child-active';event.detail.stoppedOperationId=event.operationId;const c={id:returned.sessionId,scope:returned.scope};let calls=0;const platform=homebaseVoicePlatform('https://homebase.local',async()=>{calls++;return new Response(JSON.stringify(returned))});const receipt=await platform.end!(c);assert.equal((receipt as any).nativeReturn.events.at(-1).detail.acknowledgment,'no-child-active');assert.equal(calls,1);event.detail.stoppedOperationId++;assert.throws(()=>readHomebaseVoiceReturn(JSON.stringify(returned),c))})
