import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createEIMechanismFrame,restoreEIMechanismFrame,deriveEIMechanismJobs,executeEIMechanismJob,runEIMechanism,validateEIMechanismReturn} from '../src/model/ei-mechanism.ts'
const input=()=>({userRoot:'user/root',sourceAddress:'a',sourceRevision:3,sourceId:'snapshot',records:[{address:'a',value:'A\ud800',sourceId:'sa',revision:2,links:[{address:'b',relation:'adjacent' as const,sourceId:'sa',revision:2}]},{address:'b',value:'B',sourceId:'sb',revision:3,links:[{address:'a',relation:'related' as const,sourceId:'sb',revision:3}]}]})
test('actual compiled C core executes the same occurrence contract at root and recursive children',async()=>{const f=await createEIMechanismFrame(input()),r=await runEIMechanism(f);assert.equal(r.complete,true);assert.deepEqual(r.returns.map(r=>r.job),[{address:'a',parentAddress:null,depth:0},{address:'b',parentAddress:'a',depth:1}]);for(const child of r.returns){assert.equal(child.userRoot,'user/root');assert.equal(child.frameDigest,f.digest);assert.equal(child.occurrences.length,4);assert.equal(child.occurrences[0].parentSequence,0);assert.ok(child.occurrences.every(o=>o.hadBefore===false&&o.valueDifferent===false));assert.ok(child.occurrences.some(o=>o.after==='A\ud800'))}})
test('deterministic rebuild preserves exact source and returned behavior without caller mutation',async()=>{const source=input(),f=await createEIMechanismFrame(source),a=await runEIMechanism(f);source.records[0].value='changed';const restored=await restoreEIMechanismFrame(JSON.parse(JSON.stringify(f))),b=await runEIMechanism(restored);assert.deepEqual(a,b);await assert.rejects(restoreEIMechanismFrame({...f,sourceRevision:4}),/differs/)})
test('missing adjacent source and disconnected records stay unresolved rather than whole complete',async()=>{const source=input();source.records[0].links.push({address:'unknown',relation:'adjacent',sourceId:'sa',revision:2});const f=await createEIMechanismFrame(source),r=await runEIMechanism(f);assert.equal(r.complete,false);assert.ok(r.unresolved.includes('unknown'));assert.ok(r.returns.some(r=>r.status==='waiting'))})
test('bounded independent runners preserve source-order output despite reverse delivery',async()=>{const f=await createEIMechanismFrame(input());let active=0,maximum=0;const r=await runEIMechanism(f,{parallelism:2,runner:async(frame,job)=>{active++;maximum=Math.max(maximum,active);await new Promise(resolve=>setTimeout(resolve,job.address==='a'?15:1));const r=await executeEIMechanismJob(frame,job);active--;return r}});assert.equal(maximum,2);assert.equal(r.transport.maximumInFlight,2);assert.deepEqual(r.returns.map(r=>r.job.address),['a','b']);assert.equal(r.transport.mode,'serial')})
test('stale, invented and incomplete returns are rejected before frame admission',async()=>{const f=await createEIMechanismFrame(input()),job=deriveEIMechanismJobs(f).jobs[0],r=await executeEIMechanismJob(f,job);for(const bad of [{...r,frameDigest:'changed'},{...r,userRoot:'other'},{...r,executionAuthority:true},{...r,occurrences:r.occurrences.slice(1)},{...r,occurrences:r.occurrences.map((o,i)=>i?o:{...o,after:'invented'})}])assert.throws(()=>validateEIMechanismReturn(f,job,bad as any));await assert.rejects(runEIMechanism(f,{parallelism:3}),/bound/)})
test('source capacity and non-data behavior fail explicitly',async()=>{const source=input();source.records=Array.from({length:65},(_,i)=>({...source.records[0],address:String(i)}));await assert.rejects(createEIMechanismFrame(source),/excessive/);const bad=input();Object.defineProperty(bad.records[0],'value',{get(){throw Error('should not execute')}});await assert.rejects(createEIMechanismFrame(bad),/accessor/)})
test('one failed child preserves completed sibling returns and cannot close the whole frame',async()=>{const f=await createEIMechanismFrame(input()),r=await runEIMechanism(f,{parallelism:2,runner:async(frame,job)=>{if(job.address==='b')throw Error('synthetic carrier failure');return executeEIMechanismJob(frame,job)}});assert.equal(r.complete,false);assert.equal(r.returns.length,1);assert.equal(r.returns[0].job.address,'a');assert.deepEqual(r.failures,[{job:{address:'b',parentAddress:'a',depth:1},error:'synthetic carrier failure'}])})
test('uint32 provider revisions retain exact unsigned identity across WASM i32 returns',async()=>{const f=await createEIMechanismFrame({userRoot:'u',sourceAddress:'a',sourceRevision:4294967295,sourceId:'s',records:[{address:'a',value:'x',sourceId:'s',revision:4294967295,links:[]}]}),r=await runEIMechanism(f);assert.equal(r.complete,true);assert.equal(r.returns[0].occurrences[0].revision,4294967295)})
test('packaged C artifact and retained source manifest match the actually consumed library bytes',async()=>{const {readFileSync}=await import('node:fs'),{createHash}=await import('node:crypto'),{EI_CORE_WASM_BASE64,EI_CORE_WASM_SHA256}=await import('../src/model/ei-core-binary.ts'),base=new URL('../native/ei-core/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('wasm/manifest.json',base),'utf8')),digest=(value:any)=>createHash('sha256').update(value).digest('hex'),binary=readFileSync(new URL('wasm/ei-core.wasm',base));assert.equal(digest(binary),manifest.binarySha256);assert.equal(digest(Buffer.from(EI_CORE_WASM_BASE64,'base64')),EI_CORE_WASM_SHA256);assert.equal(EI_CORE_WASM_SHA256,manifest.binarySha256);for(const [path,hash]of Object.entries(manifest.sourceSha256))assert.equal(digest(readFileSync(new URL(path,base))),hash);assert.equal(manifest.compilerSelfHostedByUserMechanism,false)})
