import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {createEIMechanismFrame,restoreEIMechanismResult} from '../src/model/ei-mechanism.ts'
const require=createRequire(import.meta.url),{createMechanismRoute,ORIGIN,PATH}=require('../native/homebase-mechanism/route.cjs')
const input={userRoot:'synthetic/user',sourceAddress:'root',sourceRevision:0,sourceId:'frame',records:[{address:'root',value:'root',sourceId:'s0',revision:0,links:[{address:'child',relation:'adjacent' as const,sourceId:'s0',revision:0}]},{address:'child',value:'child',sourceId:'s1',revision:0,links:[]}]}
const request=(body:unknown,origin=ORIGIN)=>{const r=new Request(ORIGIN+PATH,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});Object.defineProperty(r,'initiatorOrigin',{value:origin});return r}
test('fixed local route executes real native worker threads and returns an independently validated frame',async()=>{const route=createMechanismRoute({foreground:()=>true});try{const frame=await createEIMechanismFrame(input),r=await route(request({requestId:'test/1',frame})),body=await r.json();assert.equal(r.status,200);assert.equal(body.applied,false);const returned=restoreEIMechanismResult(frame,body.result);assert.equal(returned.complete,true);assert.equal(returned.transport.mode,'workers');assert.equal(returned.transport.maximumInFlight,2);const replay=await route(request({requestId:'test/1',frame}));assert.deepEqual(await replay.json(),body);assert.equal(route.inspect().requests,1)}finally{await route.dispose()}})
test('native route refuses other origins, changed request identity and background execution',async()=>{const frame=await createEIMechanismFrame(input),route=createMechanismRoute({foreground:()=>true});try{assert.equal((await route(request({requestId:'test/1',frame},'https://other.invalid'))).status,403);await route(request({requestId:'test/1',frame}));const changed=await createEIMechanismFrame({...input,sourceRevision:1});assert.equal((await route(request({requestId:'test/1',frame:changed}))).status,409);assert.equal((await route(request({requestId:'extra',frame,code:'not an allowed instruction'}))).status,400)}finally{await route.dispose()}const background=createMechanismRoute({foreground:()=>false});try{assert.equal((await background(request({requestId:'test',frame}))).status,409);assert.equal(background.inspect().requests,0)}finally{await background.dispose()}})
