import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createEILedger,proposeEI,executeEI} from '../src/model/ei-engine.ts'
import {inspectEIOperationMechanism} from '../src/model/ei-operation-mechanism.ts'
import {runEIMechanism} from '../src/model/ei-mechanism.ts'
function fixture(value='returned'){
 const base=createEILedger({records:[{address:'user',value:'before',source:{id:'original',text:'before'}}]})
 const proposal=proposeEI(base,{id:'operation',producer:'user',input:{id:'input',text:'explicit'},candidates:[{id:'next',label:'exact',owner:'engine',source:{id:'rule',text:'exact input'},conditions:[],patches:[{address:'user',value,source:{id:'returned',text:value}}]}]})
 const execution=executeEI(base,proposal);assert.equal(execution.status,'staged');if(execution.status!=='staged')throw Error('fixture');return{base,execution}
}
test('every staged producer can use the same actual C value-return contract without committing',async()=>{const {base,execution}=fixture(),before=JSON.stringify(base),r=await inspectEIOperationMechanism(base,execution,'user');assert.equal(r.children.length,1);assert.equal(r.children[0].address,'user');assert.equal(r.children[0].occurrences,1);assert.equal(r.baseRevision,0);assert.equal(r.committed,false);assert.equal(JSON.stringify(base),before);assert.deepEqual(await inspectEIOperationMechanism(base,execution,'user'),r)})
test('maximum engine text and exact UTF16 source survive the C handle bridge',async()=>{const {base,execution}=fixture('\ud800'+'x'.repeat(32767)),r=await inspectEIOperationMechanism(base,execution,'user');assert.equal(r.children.length,1)})
test('missing, forged and changed-context returns cannot pass the common boundary',async()=>{const {base,execution}=fixture();await assert.rejects(inspectEIOperationMechanism(base,execution,'user',async f=>({...await runEIMechanism(f),complete:true})),/missing or mismatched/);let current=true;await assert.rejects(inspectEIOperationMechanism(base,execution,'user',async f=>{const result=await runEIMechanism(f);current=false;return result},()=>current),/context changed/);await assert.rejects(inspectEIOperationMechanism(base,execution,'user',async()=>{throw Error('missing carrier')}),/missing carrier/)})
test('larger operations use bounded source-linked windows without changing canonical identity',async()=>{const records=Array.from({length:9},(_,i)=>({address:`a${i}`,value:`old${i}`,source:{id:`s${i}`,text:`old${i}`}})),base=createEILedger({records}),proposal=proposeEI(base,{id:'many',producer:'a0',input:{id:'input',text:'supplied'},candidates:[{id:'next',label:'all',owner:'engine',source:{id:'rule',text:'explicit membership'},conditions:[],patches:records.map(r=>({address:r.address,value:`new ${r.address}`,source:{id:`new/${r.address}`,text:`new ${r.address}`}}))}]}),execution=executeEI(base,proposal);if(execution.status!=='staged')throw Error('fixture');const frames:any[]=[],r=await inspectEIOperationMechanism(base,execution,'owner',async frame=>{frames.push(frame);return runEIMechanism(frame)});assert.equal(frames.length,3);assert.ok(frames.every(f=>f.records.length<=5&&f.userRoot==='owner'&&f.sourceAddress==='a0'));assert.deepEqual(new Set(r.children.map(c=>c.address)),new Set(records.map(r=>r.address)));assert.ok(r.children.some(c=>c.depth===1&&c.parentAddress==='a0'));assert.equal(base.receipts.length,0)})
test('actual core return round-trips through existing session export without a fake field commit',async()=>{const {saveEISession,restoreEISession}=await import('../src/model/ei-session.ts'),{packEIFieldSave,unpackEIFieldSave}=await import('../src/model/ei-field-save.ts'),{base,execution}=fixture(),returned=await inspectEIOperationMechanism(base,execution,'user'),ticket={transactionId:'operation',producer:'user',phase:'mechanism' as const,message:'Core return; engine admission is separate',detail:JSON.stringify(returned),committed:false as const},saved=packEIFieldSave(saveEISession('user',base,execution.proposal,[ticket]),null),restored=restoreEISession(unpackEIFieldSave(saved).sessionString);assert.deepEqual(restored.attempts,[ticket]);assert.deepEqual(JSON.parse(restored.attempts[0].detail),returned);assert.equal(restored.ledger.receipts.length,0);assert.equal(restored.pending?.input.id,'operation');assert.throws(()=>restoreEISession(saveEISession('user',base,null,[{...ticket,committed:true} as any])),/attempt/)})
