import test from 'node:test'
import assert from 'node:assert/strict'
import {createEIPinch} from '../src/model/ei-pinch.ts'
const v={left:100,top:50,width:600,height:400,logicalWidth:1200,logicalHeight:800},c={x:10,y:20,zoom:2}
test('two-pointer scale retains midpoint world anchor in scaled viewport',()=>{const p=createEIPinch();assert.equal(p.down(1,{x:350,y:250},c,v),false);assert.equal(p.down(2,{x:450,y:250},c,v),true);assert.deepEqual(p.move(2,{x:550,y:250},c,v,.08),{x:-15,y:20,zoom:4})})
test('one to two to one suppresses remaining drag and activation until release',()=>{const p=createEIPinch();p.down(1,{x:0,y:0},c,v);p.down(2,{x:10,y:0},c,v);assert.equal(p.end(2),true);assert.equal(p.suppress,true);assert.equal(p.move(1,{x:40,y:0},c,v,.08),null);assert.equal(p.end(1),true);assert.equal(p.suppress,false);assert.equal(p.down(3,{x:0,y:0},c,v),false)})
test('cancel clears pointers; unrelated and third pointer cannot move camera',()=>{const p=createEIPinch();assert.equal(p.move(9,{x:1,y:2},c,v,.08),null);p.down(1,{x:0,y:0},c,v);p.down(2,{x:10,y:0},c,v);p.down(3,{x:20,y:0},c,v);assert.equal(p.move(3,{x:100,y:0},c,v,.08),null);p.cancel();assert.equal(p.count,0);assert.equal(p.suppress,false)})
test('resize rebases without jump; clamp preserves finite observer camera',()=>{const p=createEIPinch();p.down(1,{x:100,y:100},c,v);p.down(2,{x:200,y:100},c,v);assert.equal(p.move(2,{x:210,y:100},c,{...v,width:800},.08),null);assert.equal(p.move(2,{x:1e6,y:100},c,{...v,width:800},.08)?.zoom,32);assert.equal(p.move(2,{x:100,y:100},c,{...v,width:800},.08)?.zoom,.08)})
import {panEIObserver} from '../src/model/ei-pinch.ts'
test('pan is observer-only and accounts for CSS-scaled viewport',()=>{assert.deepEqual(panEIObserver(c,{x:100,y:50},{x:130,y:70},v),{x:-20,y:0,zoom:2});assert.deepEqual(c,{x:10,y:20,zoom:2})})
test('two-pointer quarter turn is observer roll, with same midpoint and source-independent camera',()=>{const p=createEIPinch(),camera={...c,roll:0};p.down(1,{x:400,y:250},camera,v);p.down(2,{x:500,y:250},camera,v);const next=p.move(2,{x:400,y:350},camera,v,.08)!;assert.ok(Math.abs(next.roll!-Math.PI/2)<1e-10);assert.ok(Math.abs(next.x-10)<1e-10);assert.ok(Math.abs(next.y-20)<1e-10);assert.equal(next.zoom,2)})
test('pan after roll moves in the correct observer plane; sequential moves accumulate',()=>{const camera={...c,roll:Math.PI/2},first=panEIObserver(camera,{x:100,y:50},{x:110,y:50},v),second=panEIObserver(first,{x:110,y:50},{x:120,y:50},v);assert.ok(Math.abs(second.x-10)<1e-10);assert.equal(second.y,40);assert.equal(second.roll,Math.PI/2)})

test('wheel normalization preserves cursor anchor and observer roll',async()=>{const {zoomEIObserverAt}=await import('../src/model/ei-pinch.ts'),c={x:20,y:40,zoom:2,roll:.4},v={left:10,top:20,width:600,height:400,logicalWidth:1200,logicalHeight:800},p={x:430,y:280};const a=zoomEIObserverAt(c,p,v,16,0,.08),b=zoomEIObserverAt(c,p,v,1,1,.08);assert.deepEqual(a,b);const returned=zoomEIObserverAt(a,p,v,-16,0,.08);assert.ok(Math.abs(returned.x-c.x)<1e-9&&Math.abs(returned.y-c.y)<1e-9);assert.equal(returned.roll,.4);assert.equal(zoomEIObserverAt({...c,zoom:32},p,v,-1000,0,.08).zoom,32)})
test('mouse mapping retains pan and turn without unrelated button dispatch',async()=>{const {eiMouseGesture}=await import('../src/model/ei-pinch.ts');assert.equal(eiMouseGesture(0),'pan');assert.equal(eiMouseGesture(1),'pan');assert.equal(eiMouseGesture(2),'orbit');assert.equal(eiMouseGesture(0,true),'orbit');assert.equal(eiMouseGesture(4),'ignore')})
