import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {readEIDiscoveryReturn,proposeEIDiscoveryBatch} from '../src/model/ei-discovery.ts'
import {prepareEISpoolPage,verifyEISpoolPage,emptySpoolHead,nextSpoolHead,EI_SPOOL_LIMITS,spoolWindow} from '../src/model/ei-spool.ts'
const fixture=JSON.parse(readFileSync(new URL('./fixtures/discovery/windows-synthetic.json',import.meta.url),'utf8'))
const first=Array.isArray(fixture)?fixture[0]:fixture
const wire=first.response??first
const returned=(value=wire)=>readEIDiscoveryReturn(JSON.stringify(value),{requestId:value.requestId,address:value.address,revision:value.revision})
test('spool retains exact returned source at the existing canonical batch address',async()=>{const r=returned(),page=await prepareEISpoolPage('user/root',r);assert.equal(JSON.parse(page.content).raw,r.raw);assert.equal(page.address,`discovery/${page.scanKey}/${r.value.sequence}`);assert.equal((await verifyEISpoolPage(structuredClone(page))).sha256,page.sha256)})
test('transport replay is byte-identical; a new scan retains a new child occurrence even with equal values',async()=>{const r=returned(),a=await prepareEISpoolPage('user/root',r),b=await prepareEISpoolPage('user/root',returned()),c=await prepareEISpoolPage('user/root',returned({...wire,scanId:wire.scanId+'-new'}));assert.deepEqual(a,b);assert.notEqual(a.address,c.address);assert.deepEqual(JSON.parse(JSON.parse(a.content).raw).observations,JSON.parse(JSON.parse(c.content).raw).observations)})
test('same transport occurrence with altered source bytes stays the same address but has different content evidence',async()=>{const a=await prepareEISpoolPage('user/root',returned()),b=await prepareEISpoolPage('user/root',{...returned(),raw:JSON.stringify(wire)+'\n'});assert.equal(a.address,b.address);assert.notEqual(a.sha256,b.sha256)})
test('each user whole has separate addresses even for the same provider source',async()=>{const a=await prepareEISpoolPage('user/a',returned()),b=await prepareEISpoolPage('user/b',returned());assert.notEqual(a.address,b.address);assert.throws(()=>nextSpoolHead(emptySpoolHead('user/a'),emptySpoolHead('user/a'),b),/changed/)})
test('storage head advances only from its exact expected snapshot',async()=>{const p=await prepareEISpoolPage('user/root',returned()),h=emptySpoolHead('user/root'),next=nextSpoolHead(h,h,p);assert.equal(next.generation,1);assert.equal(next.bytes,p.bytes);assert.equal(h.generation,0);assert.throws(()=>nextSpoolHead(next,h,p),/changed/)})
test('malformed hashes, bytes, addresses and source envelopes cannot be recovered as retained pages',async()=>{const p=await prepareEISpoolPage('user/root',returned());for(const altered of [{...p,sha256:'0'.repeat(64)},{...p,bytes:0},{...p,address:'other'},{...p,content:'{}'},{...p,extra:true}])await assert.rejects(verifyEISpoolPage(altered))})
test('unvalidated pages, accessors and behavior-bearing objects cannot drive append or recovery',async()=>{const p=await prepareEISpoolPage('user/root',returned()),h=emptySpoolHead('user/root');assert.throws(()=>nextSpoolHead(h,h,structuredClone(p)),/prepared/);await assert.rejects(verifyEISpoolPage(Object.create(p)));const evil={...p};Object.defineProperty(evil,'content',{get(){throw Error('getter executed')}});await assert.rejects(verifyEISpoolPage(evil),/accessors/)})
test('explicit storage quota failure leaves the caller’s source and current head unchanged',async()=>{const p=await prepareEISpoolPage('user/root',returned()),h=Object.freeze({...emptySpoolHead('user/root'),generation:1,address:p.address,bytes:EI_SPOOL_LIMITS.totalBytes});assert.throws(()=>nextSpoolHead(h,h,p),/quota/);assert.equal(h.bytes,EI_SPOOL_LIMITS.totalBytes);assert.equal(JSON.parse(p.content).raw,returned().raw)})
test('projection windows are bounded independently of the whole storage page count',()=>{spoolWindow(400,32);assert.throws(()=>spoolWindow(0,33));assert.throws(()=>spoolWindow(-1,1));assert.ok(EI_SPOOL_LIMITS.pages>256)})
test('spool address matches actual engine proposal rather than a second identity algorithm',async()=>{const {createEILedger}=await import('../src/model/ei-engine.ts');const ledger=createEILedger({records:[{address:wire.address,value:'Synthetic user root',source:{id:'synthetic-owner',text:'Synthetic user root'}}]});const r=returned(),p=await prepareEISpoolPage(wire.address,r),proposal=await proposeEIDiscoveryBatch(ledger,wire.address,r);assert.equal(p.address,proposal.stepAddress)})
test('exact raw Unicode and whitespace survive storage encoding without normalization',async()=>{const b=structuredClone(wire);b.observations[0].label+=' \ud800';const raw=JSON.stringify(b,null,2)+'\n',r=readEIDiscoveryReturn(raw,{requestId:b.requestId,address:b.address,revision:b.revision}),p=await prepareEISpoolPage('user/root',r),restored=await verifyEISpoolPage(JSON.parse(JSON.stringify(p)));assert.equal(JSON.parse(restored.content).raw,raw)})
