import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createEIVoiceCall,type EIVoiceRecognition,type EIVoicePlatform,type EIVoiceOperation,type EIVoiceEvent,type EIVoiceTranscript} from '../src/model/ei-voice-call.ts'
import {browserVoicePlatform} from '../src/model/ei-browser-voice.ts'
import {createEILedger,executeEI,verifyEI,commitEI} from '../src/model/ei-engine.ts'
import {prepareEIConversationTurn,readEIConversation} from '../src/model/ei-conversation.ts'
const scope={address:'user',revision:0,sourceId:'source'}
function fixture(available=Promise.resolve(true)){
 let starts=0,aborts=0,cancels=0,endSpeech:(()=>void)|undefined;const recognizers:EIVoiceRecognition[]=[],events:EIVoiceEvent[]=[],transcripts:EIVoiceTranscript[]=[]
 const platform:EIVoicePlatform={name:'synthetic-local-provider',available:()=>available,recognition:()=>{const r:EIVoiceRecognition={start(){starts++;r.onstart?.()},abort(){aborts++},onstart:null,onresult:null,onend:null,onerror:null};recognizers.push(r);return r},speech(){const r:EIVoiceOperation={start(){endSpeech=()=>r.onend?.();r.onstart?.()},abort(){cancels++},onstart:null,onend:null,onerror:null};return r}}
 const call=createEIVoiceCall(platform,{state:()=>{},event:e=>events.push(e),transcript:t=>transcripts.push(t)},()=>123)
 return {call,events,transcripts,recognizers,counts:()=>({starts,aborts,cancels}),finishSpeech:()=>endSpeech?.()}
}
test('voice capture requires explicit start; final transcripts deduplicate with exact source context',async()=>{const f=fixture();assert.equal(f.counts().starts,0);await f.call.start('call',scope,'en-US');assert.equal(f.call.status(),'listening');const r=f.recognizers[0];r.onresult?.(0,'  exact voice text  ');r.onresult?.(0,'duplicate');assert.equal(f.transcripts.length,1);assert.equal(f.transcripts[0].text,'  exact voice text  ');assert.deepEqual(f.transcripts[0].scope,scope);assert.equal(f.transcripts[0].rawAudioRetained,false);await f.call.end();assert.equal(f.counts().aborts,1);assert.equal(f.call.active(),false)})
test('end during availability cannot open a late microphone',async()=>{let resolve!:(yes:boolean)=>void;const f=fixture(new Promise(r=>resolve=r)),p=f.call.start('call',scope,'en');await f.call.end();resolve(true);await p;assert.equal(f.counts().starts,0);assert.equal(f.call.status(),'ended')})
test('mute stops capture and stale callbacks; explicit listen starts a new recognizer',async()=>{const f=fixture();await f.call.start('call',scope,'en');const old=f.recognizers[0].onresult!;await f.call.mute();old(0,'late');assert.equal(f.transcripts.length,0);assert.equal(f.counts().aborts,1);await f.call.resume();assert.equal(f.counts().starts,2);f.call.end()})
test('unavailable local recognition never falls back or starts through resume',async()=>{const f=fixture(Promise.resolve(false));await f.call.start('call',scope,'en');await f.call.resume();assert.equal(f.counts().starts,0);assert.equal(f.call.status(),'unavailable');assert.equal(f.call.canListen(),false)})
test('speaking stops microphone and returns only an actual provider-end event',async()=>{const f=fixture();await f.call.start('call',scope,'en');await f.call.speak({address:'reply',revision:2,sourceId:'reply-source'},'Exact retained reply');assert.equal(f.counts().aborts,1);assert.equal(f.events.filter(e=>e.kind==='speech-ended').length,0);f.finishSpeech();const event=f.events.find(e=>e.kind==='speech-ended')!;assert.equal(event.detail.text,'Exact retained reply');assert.equal(event.detail.userHearingVerified,false);assert.equal(f.call.status(),'idle');assert.equal(f.counts().starts,1)})
test('end cancels speech and late speech return cannot claim completion',async()=>{const f=fixture();await f.call.start('call',scope,'en');await f.call.speak(scope,'Text');await f.call.end('hidden');f.finishSpeech();assert.equal(f.counts().cancels,1);assert.equal(f.events.some(e=>e.kind==='speech-ended'),false)})
test('provider end/error never causes an automatic capture restart',async()=>{const f=fixture();await f.call.start('call',scope,'en');f.recognizers[0].onerror?.('not-allowed');await new Promise(resolve=>setTimeout(resolve,0));assert.equal(f.call.status(),'failed');assert.equal(f.counts().starts,1);assert.equal(f.counts().aborts,1)})
test('legacy or remote-capable-only Web Speech is unavailable without the local API',async()=>{let created=0;class Legacy{constructor(){created++}}const platform=browserVoicePlatform({SpeechRecognition:Legacy} as unknown as Window);assert.equal(await platform.available('en',{id:'call',scope}),false);assert.equal(created,0);assert.throws(()=>platform.recognition('en',{id:'call',scope}),/Local recognition unavailable/)})
test('browser adapter requires installed local availability and sets processLocally before start',async()=>{const checks:unknown[]=[],instances:any[]=[];class Local{processLocally=false;onresult:any;onend:any;onerror:any;static async available(options:unknown){checks.push(options);return 'available'}constructor(){instances.push(this)}start(){assert.equal(this.processLocally,true)}abort(){}}Object.defineProperty(Local.prototype,'processLocally',{writable:true,value:false});const p=browserVoicePlatform({SpeechRecognition:Local} as unknown as Window);assert.equal(await p.available('en-AU',{id:'call',scope}),true);const r=p.recognition('en-AU',{id:'call',scope});r.start();assert.deepEqual(checks,[{langs:['en-AU'],processLocally:true}]);assert.equal(instances[0].interimResults,false)})
test('speech transcript retains its real origin realm atomically without fabricating a reply',async()=>{const ledger=createEILedger({records:[{address:'user',value:'User source',source:{id:'source',text:'User source'}}]}),turn=await prepareEIConversationTurn({ledger,root:'user',input:'heard words',id:'voice-turn',inputOrigin:{id:'call/transcript/1',text:'heard words',locator:JSON.stringify({session:'call',scope,processing:'on-device',rawAudioRetained:false}),realm:'local-speech-transcript'}});assert.equal(turn.status,'proposed');if(turn.status!=='proposed')return;assert.equal(turn.reply,null);const run=executeEI(ledger,turn.proposal);assert.equal(run.status,'staged');if(run.status!=='staged')return;const next=commitEI(ledger,verifyEI(run,{kind:'rendered-address-values',values:run.expected})).ledger;assert.equal(readEIConversation(next,'user').turns.length,1);assert.equal(next.records.find(r=>r.address.endsWith('/source'))!.is.source.realm,'local-speech-transcript');await assert.rejects(prepareEIConversationTurn({ledger:next,root:'user',input:'again',id:'other',inputOrigin:{id:'call/transcript/1',text:'heard words',locator:'{}',realm:'local-speech-transcript'}}),/already retained/)})
test('an abort failure cannot be reported as a successfully ended microphone',async()=>{const f=fixture();await f.call.start('call',scope,'en');f.recognizers[0].abort=()=>{throw Error('provider-stop-failed')};await f.call.end();assert.equal(f.call.status(),'failed');assert.equal(f.call.active(),true);assert.equal(f.events.some(event=>event.kind==='ended'),false);assert.ok(f.events.some(event=>event.kind==='capture-stop-failed'));f.recognizers[0].abort=()=>{};await f.call.end();assert.equal(f.call.active(),false)})
test('async provider stop keeps stopping until acknowledgment and rejects callbacks immediately',async()=>{const f=fixture();await f.call.start('call',scope,'en');let acknowledge!:()=>void;const stale=f.recognizers[0].onresult!;f.recognizers[0].abort=()=>new Promise<void>(resolve=>{acknowledge=resolve});const ending=f.call.end();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(f.call.status(),'stopping');assert.equal(f.call.active(),true);stale(0,'late');assert.equal(f.transcripts.length,0);assert.equal(f.events.some(e=>e.kind==='ended'),false);acknowledge();await ending;assert.equal(f.call.status(),'ended');assert.equal(f.events.at(-1)!.kind,'ended')})
test('queued recognition is not labeled listening until actual provider start',async()=>{let operation!:EIVoiceRecognition;const states:string[]=[];const platform:EIVoicePlatform={name:'delayed-local-fixture',available:async()=>true,recognition:(_language,context)=>{assert.deepEqual(context,{id:'call',scope});operation={start(){},abort(){},onstart:null,onend:null,onresult:null,onerror:null};return operation},speech(){throw Error('unused')}};const call=createEIVoiceCall(platform,{state:s=>states.push(s),transcript:()=>{},event:()=>{}});await call.start('call',scope,'en');assert.equal(call.status(),'checking');operation.onstart?.();assert.equal(call.status(),'listening');await call.end()})
test('browser synthesis rejects remote voices without submitting the text',()=>{let sent=false;const platform=browserVoicePlatform({speechSynthesis:{getVoices:()=>[{localService:false,lang:'en-US'}],speak:()=>{sent=true}}} as unknown as Window);assert.throws(()=>platform.speech('private source','en-US',{id:'call',scope,source:scope}),/No installed local voice/);assert.equal(sent,false)})
test('browser local synthesis retains the actually selected voice and real callbacks',()=>{const original=globalThis.SpeechSynthesisUtterance;class Utterance{onstart:any;onend:any;onerror:any;voice:any;lang:any;text:string;constructor(text:string){this.text=text}};(globalThis as any).SpeechSynthesisUtterance=Utterance;try{let actual:Utterance|undefined,cancelled=0;const platform=browserVoicePlatform({speechSynthesis:{getVoices:()=>[{localService:true,lang:'en-US',name:'Installed test voice',voiceURI:'local:test'}],speak:(u:Utterance)=>{actual=u},cancel:()=>{cancelled++}}} as unknown as Window),operation=platform.speech('Exact source','en-AU',{id:'call',scope,source:scope});let started:any,ended=false;operation.onstart=detail=>started=detail;operation.onend=()=>{ended=true};operation.start();assert.equal(ended,false);assert.equal(actual!.text,'Exact source');actual!.onstart();assert.equal(started.language,'en-US');assert.equal(started.localService,true);actual!.onend();assert.equal(ended,true);operation.abort();assert.equal(cancelled,1)}finally{globalThis.SpeechSynthesisUtterance=original}})
