import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createContext, runInContext } from 'node:vm';
import { webcrypto, createHash } from 'node:crypto';
const html=readFileSync(new URL('../public/private-vault.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)![1];
function harness(saved:string|null=null){
 const elements=new Map<string,any>(), win=new Map(),doc=new Map();let stored=saved;let fail=false;const exports:Blob[]=[];const writes:string[]=[];const timers=new Map<number,Function>();let time=0;
 const element=(id:string)=>{if(!elements.has(id))elements.set(id,{value:'',hidden:false,disabled:false,textContent:'',files:[],children:[],replaceChildren(){this.children=[]},appendChild(n:any){this.children.push(n);return n},listeners:new Map(),addEventListener(n:string,f:Function){this.listeners.set(n,f)}});return elements.get(id)};
 const context=createContext({crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,JSON,Error,Array,Object,String,Promise,isSecureContext:true,atob,btoa,Blob,URL:{createObjectURL:(b:Blob)=>{exports.push(b);return 'blob:synthetic'},revokeObjectURL:()=>{}},setTimeout:(fn:Function)=>{timers.set(++time,fn);return time},clearTimeout:(id:number)=>timers.delete(id),navigator:{locks:{request:async(_name:string,fn:Function)=>fn()}},localStorage:{getItem:()=>stored,setItem:(_key:string,v:string)=>{if(fail)throw Error('Quota');stored=v;writes.push(v)}},document:{hidden:false,getElementById:element,addEventListener:(n:string,f:Function)=>doc.set(n,f),createElement:()=>({textContent:'',children:[],listeners:new Map(),appendChild(n:any){this.children.push(n);return n},addEventListener(n:string,f:Function){this.listeners.set(n,f)},click(){}})},window:{addEventListener:(n:string,f:Function)=>win.set(n,f)}});
 runInContext(script,context);
 return {context,element,win,doc,timers,writes,exports,stored:()=>stored,fail:()=>{fail=true},change:(s:string)=>{stored=s},run:(s:string)=>runInContext(s,context),event:async(id:string,n:string)=>element(id).listeners.get(n)({preventDefault(){}})};
}
const password='SYNTHETIC-ONLY-passphrase-42';
async function unlock(h:ReturnType<typeof harness>,pass=password){h.element('pass').value=pass;h.element('confirm').value=pass;await h.event('unlock-form','submit')}
async function savedHarness(){const h=harness();await unlock(h);h.element('address').value='SYNTHETIC_PRIVATE_ADDRESS';h.element('contents').value='<img src=x onerror=alert(1)>SYNTHETIC_ONLY';await h.event('save','click');return h}
test('CSP hashes match, no external resources or application serialization',()=>{const hash=createHash('sha256').update(script).digest('base64');assert.ok(html.includes(`script-src 'sha256-${hash}'`));assert.ok(html.includes("connect-src 'none'"));assert.ok(!/\b(fetch|XMLHttpRequest|sendBeacon|innerHTML|console\.|history\.|location\.|infinity-address)\b/.test(script));});
test('encrypt/unlock, fresh IV, no plaintext in saved envelope, reload locked, inert text',async()=>{const h=await savedHarness(), raw=h.stored()!;assert.ok(raw);assert.ok(!raw.includes('SYNTHETIC'));assert.ok(!raw.includes(password));const e=JSON.parse(raw);assert.equal(e.iterations,600000);await h.event('save','click');assert.notEqual(JSON.parse(h.stored()!).iv,e.iv);const second=harness(raw);assert.equal(second.element('editor').hidden,true);await unlock(second);assert.equal(second.element('address').value,'SYNTHETIC_PRIVATE_ADDRESS');assert.equal(second.element('contents').value,'<img src=x onerror=alert(1)>SYNTHETIC_ONLY');});
test('wrong password, changed binding, ciphertext corruption fail closed',async()=>{const h=await savedHarness();for(const mode of ['password','id','ciphertext']){const e=JSON.parse(h.stored()!);if(mode==='id')e.id=btoa('another-vault-id!');if(mode==='ciphertext'){const a=atob(e.ciphertext);e.ciphertext=btoa(String.fromCharCode(a.charCodeAt(0)^1)+a.slice(1))}const second=harness(JSON.stringify(e));await unlock(second,mode==='password'?'WRONG-SYNTHETIC-password':password);assert.equal(second.element('editor').hidden,true);assert.equal(second.element('contents').value,'');}});
test('lock cancels pending unlock and encrypt; inactivity, pagehide and visibility erase UI',async()=>{const h=harness();const pending=unlock(h);await h.event('lock','click');await pending;assert.equal(h.run('key'),null);assert.equal(h.element('editor').hidden,true);await unlock(h);const save=h.event('save','click');await h.event('lock','click');await save;assert.equal(h.stored(),null);for(const how of ['idle','pagehide','hidden']){await unlock(h);h.element('contents').value='secret';if(how==='idle'){for(const f of [...h.timers.values()])f()}else if(how==='pagehide')h.win.get('pagehide')();else{h.run('document.hidden=true');h.doc.get('visibilitychange')()}assert.equal(h.element('contents').value,'');assert.equal(h.run('key'),null)}});
test('malformed, oversized, excessive KDF and extra properties rejected before crypto',async()=>{const h=await savedHarness();for(const raw of ['{','x'.repeat(150001),JSON.stringify({...JSON.parse(h.stored()!),iterations:900000000}),JSON.stringify({...JSON.parse(h.stored()!),extra:'x'})])assert.throws(()=>h.run(`parseEnvelope(${JSON.stringify(raw)})`));});
test('storage failure preserves previous ciphertext; stale concurrent tab cannot overwrite',async()=>{const h=await savedHarness();const before=h.stored();h.element('contents').value='changed';h.fail();await h.event('save','click');assert.equal(h.stored(),before);assert.equal(h.run('key'),null);const second=harness(before);await unlock(second);second.change('another-tab-ciphertext');await second.event('save','click');assert.equal(second.stored(),'another-tab-ciphertext');assert.equal(second.writes.length,0);const third=harness(before);await unlock(third);third.win.get('storage')({key:'efn.private-field.v1'});assert.equal(third.run('key'),null);assert.equal(third.element('unlock').disabled,true)});
test('encrypted import validates bounds and never replaces existing vault',async()=>{const h=await savedHarness();const raw=h.stored();h.element('import').files=[{size:1,text:async()=>'{'}];await h.event('import','change');assert.equal(h.stored(),raw);const empty=harness();empty.element('import').files=[{size:150001,text:async()=>{throw Error('must not read')}}];await empty.event('import','change');assert.equal(empty.stored(),null);empty.element('import').files=[{size:raw!.length,text:async()=>raw}];await empty.event('import','change');assert.equal(empty.stored(),raw);assert.equal(empty.run('key'),null)});
test('local plaintext file stays in unlocked memory and is inert; bounds and async lock enforced',async()=>{const h=harness();await unlock(h);h.element('local-file').files=[{size:40,text:async()=>'<script>alert("synthetic")</script>'}];await h.event('local-file','change');assert.equal(h.stored(),null);assert.equal(h.element('contents').value,'<script>alert("synthetic")</script>');h.element('local-file').files=[{size:65537,text:async()=>{throw Error('must not read')}}];await h.event('local-file','change');assert.equal(h.stored(),null);let resolve:any;h.element('local-file').files=[{size:5,text:()=>new Promise(r=>{resolve=r})}];const p=h.event('local-file','change');await h.event('lock','click');resolve('secret');await p;assert.equal(h.element('contents').value,'')});

test('backup exports saved ciphertext only, including when unlocked edits differ',async()=>{const h=await savedHarness();const saved=h.stored();h.element('contents').value='UNSAVED_PRIVATE_VALUE';await h.event('export','click');assert.equal(h.exports.length,1);const backup=await h.exports[0].text();assert.equal(backup,saved);assert.ok(!backup.includes('SYNTHETIC_PRIVATE_ADDRESS'));assert.ok(!backup.includes('UNSAVED_PRIVATE_VALUE'));assert.ok(!backup.includes(password));});
test('lock during encrypted backup file read prevents persistence',async()=>{const existing=await savedHarness(),h=harness();let resolve:any;h.element('import').files=[{size:1000,text:()=>new Promise(r=>{resolve=r})}];const pending=h.event('import','change');await h.event('lock','click');resolve(existing.stored());await pending;assert.equal(h.stored(),null);assert.equal(h.run('key'),null);});

const syntheticIndex={format:'synthetic',format_version:1,created_at:'2026-01-01',privacy:'synthetic',title:'SYNTHETIC PRIVATE INDEX',purpose:'test',coverage:{},semantics:{},entries:[{id:'root',title:'<img src=x onerror=alert(1)>',kind:'root',source_role:'user statement',WAS:'before',IS:{state:'now'},NEXT:'later',provenance:{source:'synthetic'}},{id:'child',title:'Child entry',kind:'file',source_role:'derived',WAS:'old',IS:'present',NEXT:'next',provenance:[]}],edges:[{id:'edge',from:'root',relation:'contains',to:'child',basis:'synthetic',source:'no external link'}]};
test('addressed viewer navigates inert nodes and binary edges; search/back/root stay memory-only',async()=>{const h=harness();await unlock(h);h.element('contents').value=JSON.stringify(syntheticIndex);await h.event('index-refresh','click');assert.equal(h.element('index-view').hidden,false);assert.equal(h.element('index-results').children.length,2);h.element('index-results').children[0].listeners.get('click')();assert.equal(h.run('selectedId'),'root');assert.equal(h.element('index-detail').children[0].textContent,'<img src=x onerror=alert(1)>');const outgoing=h.element('index-detail').children.find((n:any)=>n.className==='index-edge');outgoing.children[0].listeners.get('click')();assert.equal(h.run('selectedId'),'child');await h.event('index-back','click');assert.equal(h.run('selectedId'),'root');h.element('index-search').value='Child';await h.event('index-search','input');assert.equal(h.element('index-results').children.length,1);await h.event('index-root','click');assert.equal(h.run('selectedId'),null);assert.equal(h.element('index-results').children.length,2);assert.equal(h.stored(),null);await h.event('lock','click');assert.equal(h.run('indexView'),null);assert.equal(h.run('viewHistory.length'),0);assert.equal(h.element('index-search').value,'');assert.equal(h.element('index-detail').children.length,0);assert.equal(h.element('index-results').children.length,0);assert.equal(h.element('index-title').textContent,'Private addressed index');});
test('addressed viewer rejects malformed, oversized/deep indexes without changing contents',async()=>{const h=harness();await unlock(h);for(const data of [{entries:[{}],edges:[]},{...syntheticIndex,edges:[{id:'bad',from:'root',relation:'x',to:'missing'}]},{...syntheticIndex,entries:Array(257).fill(syntheticIndex.entries[0])},{...syntheticIndex,title:'x'.repeat(8193)},{...syntheticIndex,semantics:Array.from({length:12}).reduce(v=>({nested:v}),{})}]){const raw=JSON.stringify(data);h.element('contents').value=raw;await h.event('index-refresh','click');assert.equal(h.element('index-view').hidden,true);assert.equal(h.element('contents').value,raw);assert.equal(h.stored(),null)}});
test('addressed viewer clears with edits and lifecycle locks and reconstructs only after unlock',async()=>{const h=harness();await unlock(h);h.element('contents').value=JSON.stringify(syntheticIndex);await h.event('index-refresh','click');await h.event('contents','input');assert.equal(h.run('indexView'),null);await h.event('index-refresh','click');await h.event('save','click');h.win.get('pagehide')();assert.equal(h.run('indexView'),null);assert.equal(h.element('index-title').textContent,'Private addressed index');await unlock(h);assert.equal(h.element('index-view').hidden,false);assert.equal(h.run('indexView.nodes.size'),2);assert.ok(!h.stored()!.includes('SYNTHETIC PRIVATE INDEX'));});
