import test from "node:test"
import assert from "node:assert/strict"
import {clampViewZoom,fitView,pickNodes,stateAddress,parseStateAddress,continuumAtAct} from "../src/model/view-navigation.ts"
import {createLedgerContinuum,advanceLedgerContinuum} from "../src/model/kernel.ts"
test("view zoom exceeds old64 limit without unbounded or invalid arithmetic",()=>{assert.equal(clampViewZoom(512),512);assert.equal(clampViewZoom(Infinity),.125);assert.equal(clampViewZoom(1e9),65536)})
test("fit enlarges a seeded node and adapts to resize without altering positions",()=>{const points=[{x:-.38,y:-.38},{x:.38,y:.38}],before=JSON.stringify(points);const big=fitView(points,1800,800)!,small=fitView(points,390,400)!;assert.ok(big.zoom>64);assert.ok(big.zoom>small.zoom);assert.equal(big.x,0);assert.equal(JSON.stringify(points),before);assert.equal(fitView([],400,400),null)})
test("fit complete extents and shifted selection",()=>{const fit=fitView([{x:20,y:-4},{x:24,y:2}],600,400)!;assert.equal(fit.x,22);assert.equal(fit.y,-1);assert.ok(fit.zoom*6<400);assert.ok(fit.zoom*4<600)})
test("pick visible tetra surface beyond anchor tolerance",()=>{const nodes=[{address:'a',x:0,y:0,polygons:[[{x:0,y:0},{x:90,y:0},{x:0,y:90},{x:10,y:10}]]}];assert.deepEqual(pickNodes(nodes,{x:25,y:25}),['a']);assert.deepEqual(pickNodes(nodes,{x:100,y:100}),[])})
test("overlap returns every address, never silently first",()=>{const nodes=['1,0,0','-1,0,0'].map(address=>({address,x:10,y:10,polygons:[]}));assert.deepEqual(new Set(pickNodes(nodes,{x:10,y:10})),new Set(['1,0,0','-1,0,0']))})
test("state address canonicalization and invalid/future references",()=>{const a={act:2,role:'NEXT' as const,address:'-1,0,0'};assert.deepEqual(parseStateAddress(stateAddress(a)),a);assert.equal(parseStateAddress('nonsense'),null);assert.equal(parseStateAddress('selected-kernel/act/2/IS/9007199254740992,0,0'),null);assert.deepEqual(parseStateAddress('selected-kernel/act/2/IS/-0,00,0'),{act:2,role:'IS',address:'0,0,0'})})
test("retained state navigation reproduces exact snapshots without advancing live time",()=>{let live=createLedgerContinuum();const states=[live.state];for(let i=0;i<7;i++){live=advanceLedgerContinuum(live);states.push(live.state)}const before=live;for(let i=0;i<8;i++){const got=continuumAtAct(live,i);assert.deepEqual(got.state,states[i]);assert.equal(got.receipts.length,i)}assert.equal(live,before);assert.equal(live.state.act,7);assert.throws(()=>continuumAtAct(live,8));assert.throws(()=>continuumAtAct(live,-1))})
