import test from "node:test"
import assert from "node:assert/strict"
import {clampViewZoom,fitView,usableFieldView,isCurrentActFrame,createViewAdvanceQueue,pickNodes,stateAddress,parseStateAddress,continuumAtAct} from "../src/model/view-navigation.ts"
import {createLedgerContinuum,advanceLedgerContinuum} from "../src/model/kernel.ts"
test("view zoom exceeds old64 limit without unbounded or invalid arithmetic",()=>{assert.equal(clampViewZoom(512),512);assert.equal(clampViewZoom(Infinity),.125);assert.equal(clampViewZoom(1e9),65536)})
test("fit enlarges a seeded node and adapts to resize without altering positions",()=>{const points=[{x:-.38,y:-.38},{x:.38,y:.38}],before=JSON.stringify(points);const big=fitView(points,1800,800)!,small=fitView(points,390,400)!;assert.ok(big.zoom>64);assert.ok(big.zoom>small.zoom);assert.equal(big.x,0);assert.equal(JSON.stringify(points),before);assert.equal(fitView([],400,400),null)})
test("fit complete extents and shifted selection",()=>{const fit=fitView([{x:20,y:-4},{x:24,y:2}],600,400)!;assert.equal(fit.x,22);assert.equal(fit.y,-1);assert.ok(fit.zoom*6<400);assert.ok(fit.zoom*4<600)})
test("pick visible tetra surface beyond anchor tolerance",()=>{const nodes=[{address:'a',x:0,y:0,polygons:[[{x:0,y:0},{x:90,y:0},{x:0,y:90},{x:10,y:10}]]}];assert.deepEqual(pickNodes(nodes,{x:25,y:25}),['a']);assert.deepEqual(pickNodes(nodes,{x:100,y:100}),[])})
test("overlap returns every address, never silently first",()=>{const nodes=['1,0,0','-1,0,0'].map(address=>({address,x:10,y:10,polygons:[]}));assert.deepEqual(new Set(pickNodes(nodes,{x:10,y:10})),new Set(['1,0,0','-1,0,0']))})
test("state address canonicalization and invalid/future references",()=>{const a={act:2,role:'NEXT' as const,address:'-1,0,0'};assert.deepEqual(parseStateAddress(stateAddress(a)),a);assert.equal(parseStateAddress('nonsense'),null);assert.equal(parseStateAddress('selected-kernel/act/2/IS/9007199254740992,0,0'),null);assert.deepEqual(parseStateAddress('selected-kernel/act/2/IS/-0,00,0'),{act:2,role:'IS',address:'0,0,0'})})
test("retained state navigation reproduces exact snapshots without advancing live time",()=>{let live=createLedgerContinuum();const states=[live.state];for(let i=0;i<7;i++){live=advanceLedgerContinuum(live);states.push(live.state)}const before=live;for(let i=0;i<8;i++){const got=continuumAtAct(live,i);assert.deepEqual(got.state,states[i]);assert.equal(got.receipts.length,i)}assert.equal(live,before);assert.equal(live.state.act,7);assert.throws(()=>continuumAtAct(live,8));assert.throws(()=>continuumAtAct(live,-1))})

test("fitted field reserves toolbar, inspector and existing camera inset",()=>{const view=usableFieldView(1180,757,90,true);assert.equal(view.left,490);assert.ok(view.top>16+757*.28);assert.ok(view.top+view.height<=757-70);const narrow=usableFieldView(500,757,136,true);assert.equal(narrow.left,0);assert.equal(narrow.width,500)})

test("historical frame completion cannot gate a live model commit",()=>{assert.equal(isCurrentActFrame(0,7),false);assert.equal(isCurrentActFrame(7,7),true);assert.equal(isCurrentActFrame(-1,-1),false);assert.equal(isCurrentActFrame(NaN,7),false)})

test("queued advance interrupted by historical navigation cancels only uncommitted work",()=>{let live=createLedgerContinuum();for(let i=0;i<3;i++)live=advanceLedgerContinuum(live);const retained=live,queue=createViewAdvanceQueue();queue.request();const history=continuumAtAct(live,0);assert.equal(queue.consumeCurrentFrame(history.state.act,live.state.act),false);assert.equal(queue.pending,1);assert.equal(queue.cancel(),1);assert.equal(live,retained);assert.equal(live.state.act,3);queue.request();const current=continuumAtAct(live,live.state.act);if(queue.consumeCurrentFrame(current.state.act,live.state.act))live=advanceLedgerContinuum(live);assert.equal(live.state.act,4);assert.equal(queue.consumeCurrentFrame(current.state.act,live.state.act),false);assert.equal(queue.cancel(),0);assert.equal(live.state.act,4);assert.equal(retained.state.act,3)})
