import {checkEIData} from './ei-binary-machine.ts'
import {createEINativeVoicePlatform,type EINativeVoiceReturn} from './ei-native-voice.ts'
import type {EIVoiceContext,EIVoiceScope} from './ei-voice-call.ts'
const integer=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>=0
const text=(v:unknown,max:number)=>typeof v==='string'&&v.length>0&&v.length<=max
const same=(a:EIVoiceScope,b:EIVoiceScope)=>!!a&&a.address===b.address&&a.revision===b.revision&&a.sourceId===b.sourceId
const keys=(v:object,allowed:string[])=>{if(Object.keys(v).some(k=>!allowed.includes(k)))throw Error('Unexpected Android voice field')}
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v)}return v}
export function readAndroidVoiceReturn(raw:string,context:EIVoiceContext):EINativeVoiceReturn{
 if(raw.length>262144)throw Error('Android voice return exceeds bound');const v=JSON.parse(raw);checkEIData(v)
 keys(v,['schema','sessionId','scope','operationId','status','language','capabilities','cursor','nextCursor','events','processing','rawAudioRetained','externalUpload','applied','limits'])
 if(v.schema!=='field.android.voice.v1'||v.sessionId!==context.id||!same(v.scope,context.scope)||v.processing!=='on-device'||v.rawAudioRetained!==false||v.externalUpload!==false||v.applied!==false)throw Error('Android voice scope or processing mismatch');keys(v.scope,['address','revision','sourceId'])
 if(!integer(v.operationId)||v.operationId>128||!['checking','ready','unavailable','starting','permission','listening','speaking','stopping','idle','cancelled','ended','failed'].includes(v.status)||!(text(v.language,80)||(v.language===null&&v.status==='ended'&&v.operationId===0&&v.capabilities===null))||!integer(v.cursor)||!integer(v.nextCursor)||v.nextCursor>192||!Array.isArray(v.events)||v.events.length>8||v.nextCursor!==v.cursor+v.events.length)throw Error('Invalid Android voice state')
 const expected={requestBytes:49152,responseBytes:262144,sessions:32,operations:128,events:192,eventBatch:8,sessionBytes:524288,totalBytes:2097152,sessionMs:600000,leaseMs:15000,textCodeUnits:8192};if(!v.limits||Object.keys(v.limits).length!==Object.keys(expected).length||Object.entries(expected).some(([k,n])=>v.limits[k]!==n))throw Error('Android voice bounds changed')
 const c=v.capabilities;if(c!==null){if(!c||c.kind!=='availability'||!integer(c.apiLevel)||c.apiLevel<1||typeof c.recognitionAvailable!=='boolean'||typeof c.speechAvailable!=='boolean'||c.language!==v.language||c.recognitionLanguageSupport!=='unknown'||!['granted','not-granted'].includes(c.microphonePermission)||![null,'android-on-device-speech-api'].includes(c.recognitionProvider)||c.actualTtsEngineAttested!==false||c.evidence!=='android-api-and-installed-voice-metadata'||c.providerAttestation!==false||c.foregroundActivityRequired!==true||!integer(c.nativeTtsTextLimit)||c.nativeTtsTextLimit<1||!(c.configuredTtsEngine===null||text(c.configuredTtsEngine,1024)))throw Error('Invalid Android voice capabilities');keys(c,['kind','apiLevel','recognitionAvailable','speechAvailable','language','recognitionLanguageSupport','microphonePermission','recognitionProvider','voices','configuredTtsEngine','actualTtsEngineAttested','nativeTtsTextLimit','evidence','providerAttestation','foregroundActivityRequired']);if(c.recognitionAvailable&&(c.apiLevel<31||c.recognitionProvider!=='android-on-device-speech-api'))throw Error('On-device recognition unsupported');if(!Array.isArray(c.voices)||c.voices.length>32||(c.speechAvailable&&!c.voices.length))throw Error('Invalid local Android voices');for(const voice of c.voices){keys(voice,['id','language','networkRequired','dataInstalled']);if(!text(voice.id,1024)||!text(voice.language,80)||voice.networkRequired!==false||voice.dataInstalled!==true)throw Error('Android voice is not installed locally')}}
 for(let i=0;i<v.events.length;i++){const e=v.events[i];keys(e,['id','sequence','parentEventId','sessionId','scope','operationId','kind','observedAt','detail']);keys(e.scope,['address','revision','sourceId']);if(e.sequence!==v.cursor+i+1||e.id!==`${context.id}/native/${e.sequence}`||e.parentEventId!==(e.sequence===1?null:`${context.id}/native/${e.sequence-1}`)||e.sessionId!==context.id||!same(e.scope,context.scope)||!integer(e.operationId)||e.operationId>128||!integer(e.observedAt)||!['availability-requested','availability-returned','listen-requested','permission-requested','permission-returned','listening','audio-input-ended','transcript','recognition-ended','speech-requested','speaking','speech-ended','failed','cancelled','ended'].includes(e.kind)||!e.detail||typeof e.detail!=='object'||Array.isArray(e.detail))throw Error('Invalid Android voice event')
  const d=e.detail;if(e.kind==='transcript'&&(!text(d.text,8192)||!(d.confidence===null||(typeof d.confidence==='number'&&Number.isFinite(d.confidence)&&d.confidence>=0&&d.confidence<=1))||d.provider!=='android-on-device-speech-api'||d.processing!=='on-device'||d.rawAudioRetained!==false))throw Error('Invalid Android transcript');if(e.kind==='transcript'){if(d.selectedResultIndex!==0||!integer(d.returnedAlternativeCount)||Number(d.returnedAlternativeCount)<1||!integer(d.retainedAlternativeCount)||!integer(d.omittedAlternativeCount)||!Array.isArray(d.otherAlternatives)||d.otherAlternatives.length>7||d.retainedAlternativeCount!==d.otherAlternatives.length+1||Number(d.returnedAlternativeCount)!==Number(d.retainedAlternativeCount)+Number(d.omittedAlternativeCount)||d.alternativesTruncated!==(Number(d.omittedAlternativeCount)>0)||new TextEncoder().encode(JSON.stringify(d.otherAlternatives)).length>16384)throw Error('Invalid recognition alternatives');let previous=0;for(const alternative of d.otherAlternatives){keys(alternative,['index','text','confidence']);if(!integer(alternative.index)||alternative.index<=previous||alternative.index>=Number(d.returnedAlternativeCount)||!text(alternative.text,8192)||!(alternative.confidence===null||(typeof alternative.confidence==='number'&&Number.isFinite(alternative.confidence)&&alternative.confidence>=0&&alternative.confidence<=1)))throw Error('Invalid recognition alternative');previous=alternative.index}}if(e.kind==='listening'&&(d.provider!=='android-on-device-speech-api'||d.processing!=='on-device'||d.evidence!=='onReadyForSpeech'||d.hardwareCaptureVerified!==false))throw Error('Invalid Android listening evidence');if(['speaking','speech-ended'].includes(e.kind)&&(d.processing!=='on-device'||d.userHearingVerified!==false||!text(d.voiceId,1024)||!text(d.text,8192)||!d.source||!text(d.source.address,1024)||!integer(d.source.revision)||!text(d.source.sourceId,1024)))throw Error('Invalid Android spoken source');if(v.language===null&&(e.kind!=='ended'||e.operationId!==0||d.stopAcknowledgment!=='android-session-tombstone-no-resources-created'||d.resourcesCreated!==false))throw Error('Invalid uninitialized voice tombstone');if(['cancelled','ended'].includes(e.kind)&&(d.hardwareStopVerified!==false||!(d.stopAcknowledgment==='android-cancel-destroy-and-tts-stop-api-return'||(e.kind==='ended'&&v.language===null&&v.operationId===0&&v.capabilities===null&&d.stopAcknowledgment==='android-session-tombstone-no-resources-created'&&d.resourcesCreated===false))))throw Error('Invalid Android stop acknowledgment')
 }
 return freeze(v)
}
export function androidVoicePlatform(origin:string,transport:typeof fetch=fetch){
 const core=createEINativeVoicePlatform({origin,path:'/EverthingFromNothing/__native/voice.json',method:'GET',name:'android-on-device-speech',read:readAndroidVoiceReturn},transport)
 return {...core,speech(text:string,language:string,context:EIVoiceContext&{source:EIVoiceScope}){const capability=core.availabilityReceipt?.(context)?.capabilities as {nativeTtsTextLimit?:number}|undefined;if(capability?.nativeTtsTextLimit&&text.length>capability.nativeTtsTextLimit)throw Error('Spoken source exceeds this Android engine input limit');return core.speech(text,language,context)}}
}
