import {readEIDiscoveryReturn,type EIDiscoveryReturn} from './ei-discovery.ts'
import {readEIPhoneReturn} from './ei-phone-return.ts'
import type {HomebaseDiscoveryObservation,HomebaseDiscoveryScope} from './ei-discovery-types.ts'
/** Same bounded batch/receipt path, with truthful provider provenance. These
 * adapters inspect exposed metadata; they do not infer hidden system layers. */
function batches(carrier:'web'|'android',scope:HomebaseDiscoveryScope,rows:HomebaseDiscoveryObservation[],platform:string,startedAt:string,diagnostics:{code:string;count:number}[]):EIDiscoveryReturn[]{
 const parts=[];for(let at=0;at<Math.max(1,rows.length);at+=16){const observations=rows.slice(at,at+16),sequence=at/16,complete=at+16>=rows.length,value={schema:'ei.provider.discovery.v1',...scope,scanId:`${carrier}/${scope.requestId}`,kind:'system',status:complete?'complete':'running',sequence,nextCursor:complete?null:sequence+1,startedAt,observedAt:startedAt,platform,root:null,observations,progress:{visited:Math.min(rows.length,at+16),returned:Math.min(rows.length,at+16),skipped:0,queued:Math.max(0,rows.length-at-16)},limits:{batchSize:16,maxEntries:1024,maxDepth:6,maxSeconds:120},diagnostics,contentRead:false,credentialsRead:false,externalUpload:false,applied:false};parts.push(readEIDiscoveryReturn(JSON.stringify(value),scope,carrier))}return parts
}
export function observeEIBrowserDiscovery(scope:HomebaseDiscoveryScope,navigatorValue:Pick<Navigator,'userAgent'|'language'|'platform'|'hardwareConcurrency'>,screenValue:Pick<Screen,'width'|'height'|'colorDepth'>,observedAt=new Date().toISOString()){
 const rows:HomebaseDiscoveryObservation[]=[{key:'browser/runtime',parentKey:null,kind:'runtime',label:'Current browser',metadata:{userAgent:navigatorValue.userAgent,language:navigatorValue.language,reportedPlatform:navigatorValue.platform,installedApplicationsEnumerated:false},source:'browser-api',observedAt},{key:'browser/display',parentKey:null,kind:'display',label:'Reported display',metadata:{width:screenValue.width,height:screenValue.height,colorDepth:screenValue.colorDepth,scope:'browser-reported-screen'},source:'browser-api',observedAt}]
 if(Number.isSafeInteger(navigatorValue.hardwareConcurrency)&&navigatorValue.hardwareConcurrency>0)rows.push({key:'browser/concurrency',parentKey:null,kind:'cpu',label:'Reported logical concurrency',metadata:{logicalConcurrency:navigatorValue.hardwareConcurrency,physicalCpuAttested:false},source:'browser-api',observedAt})
 return batches('web',scope,rows,'browser',observedAt,[{code:'firmware-kernel-installed-software-not-exposed',count:1}])
}
export async function observeEIAndroidDiscovery(scope:HomebaseDiscoveryScope,origin:string,request:typeof fetch=fetch){
 const returned=await readEIPhoneReturn(scope,origin,scope.requestId,request);if(returned.check.status!=='os-metadata-return')throw Error('Android metadata provider is unavailable')
 const value=returned.value as Record<string,unknown>,observedAt=new Date().toISOString(),rows:HomebaseDiscoveryObservation[]=[{key:'android/os',parentKey:null,kind:'os',label:`Android API ${value.apiLevel}`,metadata:{apiLevel:value.apiLevel,packageName:value.packageName,elapsedRealtimeNanos:value.elapsedRealtimeNanos,hardwareAttestation:false},source:'android-os-api',observedAt}]
 for(const [field,kind]of [['osReportedFeatures','feature'],['osReportedSensorMetadata','sensor'],['installedManifestPermissions','permission']] as const){for(const [index,row]of (value[field] as unknown[]).entries()){const object=row&&typeof row==='object'&&!Array.isArray(row)?row as Record<string,unknown>:{reportedValue:row},name=String(object.name??object.permission??object.reportedValue??`${kind} ${index}`);rows.push({key:`android/${field}/${scope.requestId}/${index}`,parentKey:'android/os',kind,label:name.slice(0,256),metadata:{returned:object,returnRequestId:scope.requestId,sourcePointer:`/${field}/${index}`,identityScope:'this-returned-api-entry',physicalIdentityEstablished:false},source:'android-os-api',observedAt})}}
 return batches('android',scope,rows,`android-api-${value.apiLevel}`,observedAt,[{code:'firmware-kernel-private-files-not-exposed-by-this-provider',count:1}])
}
