import {checkEIData} from './ei-binary-machine.ts'
import type {EIVoiceContext,EIVoiceScope} from './ei-voice-call.ts'
import {createEINativeVoicePlatform,type EINativeVoiceReturn} from './ei-native-voice.ts'
const integer=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>=0
const boundText=(v:unknown,n:number)=>typeof v==='string'&&v.length>0&&v.length<=n
const same=(a:EIVoiceScope,b:EIVoiceScope)=>!!a&&a.address===b.address&&a.revision===b.revision&&a.sourceId===b.sourceId
const exact=(v:object,keys:string[])=>{if(Object.keys(v).some(k=>!keys.includes(k)))throw Error('Unexpected native voice field')}
const freeze=<T>(v:T):T=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v)}return v}
export function readHomebaseVoiceReturn(raw:string,context:EIVoiceContext):EINativeVoiceReturn{
 if(raw.length>262144)throw Error('Native voice return exceeds bound');const v=JSON.parse(raw);checkEIData(v)
 exact(v,['schema','sessionId','scope','operationId','status','language','capabilities','cursor','nextCursor','events','processing','rawAudioRetained','externalUpload','applied','limits'])
 if(v.schema!=='field.homebase.voice.v1'||v.sessionId!==context.id||!same(v.scope,context.scope)||v.processing!=='on-device'||v.rawAudioRetained!==false||v.externalUpload!==false||v.applied!==false)throw Error('Native voice scope or processing mismatch')
 exact(v.scope,['address','revision','sourceId'])
 if(!integer(v.operationId)||v.operationId>128||!['idle','checking','ready','unavailable','starting','listening','speaking','stopping','cancelled','ended','failed'].includes(v.status)||!(v.language===null||boundText(v.language,80))||!integer(v.cursor)||!integer(v.nextCursor)||v.nextCursor>192||!Array.isArray(v.events)||v.events.length>8||v.nextCursor!==v.cursor+v.events.length)throw Error('Invalid native voice state')
 const limits={requestBytes:49152,sessions:32,operations:128,events:192,eventBatch:8,sessionBytes:524288,totalBytes:2097152,sessionMs:600000,leaseMs:15000};if(!v.limits||Object.keys(v.limits).length!==Object.keys(limits).length||Object.entries(limits).some(([k,n])=>v.limits[k]!==n))throw Error('Native voice bounds changed')
 if(v.capabilities!==null){const c=v.capabilities;if(!c||c.kind!=='availability'||typeof c.recognitionAvailable!=='boolean'||typeof c.speechAvailable!=='boolean'||c.language!==v.language||c.evidence!=='installed-engine-metadata'||c.providerAttestation!==false)throw Error('Invalid native voice availability');exact(c,['kind','recognitionAvailable','speechAvailable','recognizers','voices','language','evidence','providerAttestation']);for(const field of ['recognizers','voices']){if(!Array.isArray(c[field])||c[field].length>32)throw Error('Invalid native voice providers');for(const row of c[field]){exact(row,['id','name','language','provider','processing']);if(!boundText(row.id,160)||!boundText(row.name,256)||!boundText(row.language,80)||row.provider!=='microsoft-desktop-sapi'||row.processing!=='on-device'||!(field==='recognizers'?/^MS-[0-9]{4,5}-80-DESK$/:/^TTS_MS_[A-Z]{2,3}-[A-Z]{2,3}_[A-Z0-9_]+_[0-9.]+$/).test(row.id))throw Error('Invalid native voice provider')}}for(const [flag,rows]of [['recognitionAvailable','recognizers'],['speechAvailable','voices']])if(c[flag]!==c[rows].some((r:{language:string})=>r.language.toLowerCase()===c.language.toLowerCase()))throw Error('Native voice availability differs from providers')}
 for(let i=0;i<v.events.length;i++){const e=v.events[i];exact(e,['id','sequence','parentEventId','sessionId','scope','operationId','kind','observedAt','detail']);if(e.sequence!==v.cursor+i+1||e.id!==`${context.id}/native/${e.sequence}`||e.parentEventId!==(e.sequence===1?null:`${context.id}/native/${e.sequence-1}`)||e.sessionId!==context.id||!same(e.scope,context.scope)||!integer(e.operationId)||e.operationId>128||!integer(e.observedAt)||!boundText(e.kind,80)||!e.detail||typeof e.detail!=='object'||Array.isArray(e.detail))throw Error('Invalid native voice event');exact(e.scope,['address','revision','sourceId']);if(!['availability-requested','availability-returned','unavailable','listen-requested','listening','transcript','recognition-ended','speech-requested','speaking','speech-ended','failed','idle','cancelled','ended'].includes(e.kind))throw Error('Unknown native voice event');if(['cancelled','ended'].includes(e.kind)&&(!['child-process-exited','no-child-active'].includes(e.detail.acknowledgment)||e.detail.stoppedOperationId!==e.operationId))throw Error('Invalid native stop acknowledgment');if(e.kind==='speech-ended'&&e.detail.userHearingVerified!==false)throw Error('Unsupported hearing assertion');if(e.kind==='listening'&&(e.detail.processing!=='on-device'||e.detail.adaptationEnabled!==false))throw Error('Unexpected recognition processing');if(e.kind==='speaking'&&e.detail.processing!=='on-device')throw Error('Unexpected synthesis processing');if(e.kind==='transcript'&&(!boundText(e.detail.text,8192)||typeof e.detail.confidence!=='number'||e.detail.confidence<0||e.detail.confidence>1||e.detail.provider!=='microsoft-desktop-sapi'))throw Error('Invalid native transcript')}
 return freeze(v)
}

export function homebaseVoicePlatform(origin:string,transport:typeof fetch=fetch){return createEINativeVoicePlatform({origin,path:'/EverthingFromNothing/__native/homebase-voice.json',method:'POST',name:'homebase-microsoft-local-speech',read:readHomebaseVoiceReturn},transport)}
