import {readBoundedPublicText} from './ei-public-sync-return.ts'
import type {EIVoiceContext,EIVoiceScope,EIVoicePlatform,EIVoiceRecognition} from './ei-voice-call.ts'
export type EINativeVoiceEvent=Readonly<{id:string;sequence:number;parentEventId:string|null;sessionId:string;scope:EIVoiceScope;operationId:number;kind:string;observedAt:number;detail:Readonly<Record<string,unknown>>}>
export type EINativeVoiceReturn=Readonly<{schema:string;sessionId:string;scope:EIVoiceScope;operationId:number;status:string;language:string|null;capabilities:null|Readonly<{recognitionAvailable:boolean;speechAvailable:boolean;language:string}>;cursor:number;nextCursor:number;events:readonly EINativeVoiceEvent[];processing:'on-device';rawAudioRetained:false;externalUpload:false;applied:false;limits:Readonly<Record<string,number>>}>
const same=(a:EIVoiceScope,b:EIVoiceScope)=>!!a&&a.address===b.address&&a.revision===b.revision&&a.sourceId===b.sourceId
/** Fixed, local carrier route only. No remote speech API or audio upload. */
export function createEINativeVoicePlatform(options:{origin:string;path:string;method:'GET'|'POST';name:string;read:(raw:string,context:EIVoiceContext)=>EINativeVoiceReturn},transport:typeof fetch=fetch):EIVoicePlatform{
 const {origin,path,method,read}=options
 if(!((origin==='https://homebase.local'&&path==='/EverthingFromNothing/__native/homebase-voice.json'&&method==='POST')||(origin==='https://appassets.androidplatform.net'&&path==='/EverthingFromNothing/__native/voice.json'&&method==='GET')))throw Error('Native voice is unavailable on this origin or route')
 const sessions=new Map<string,{operation:number;cursor:number;scope:EIVoiceScope;availability?:EINativeVoiceReturn;endRequested?:boolean}>()
 const state=(c:EIVoiceContext)=>{let s=sessions.get(c.id);if(s&&!same(s.scope,c.scope))throw Error('Voice session scope changed');if(!s){s={operation:0,cursor:0,scope:Object.freeze({...c.scope})};sessions.set(c.id,s)}return s}
 const post=async(c:EIVoiceContext,request:Record<string,unknown>)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const payload=JSON.stringify({...request,sessionId:c.id,scope:c.scope}),url=`${origin}${path}`+(method==='GET'?`?request=${encodeURIComponent(payload)}`:'');const response=await transport(url,{method,...(method==='POST'?{headers:{'Content-Type':'application/json'},body:payload}:{}),credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:controller.signal});const raw=await readBoundedPublicText(new Response(response.body),262144);if(!response.ok){let code='unreturned';try{const value=JSON.parse(raw);if(typeof value.error==='string'&&/^[a-z0-9-]{1,100}$/.test(value.error))code=value.error}catch{if(/^[a-z0-9-]{1,100}$/.test(raw))code=raw}throw Error(`Native voice ${code} (${response.status})`)}const value=read(raw,c);if(request.action==='poll'&&(value.cursor!==request.cursor||value.operationId!==request.operationId))throw Error('Native voice poll correlation changed');return value}finally{clearTimeout(timer)}}
 const wait=()=>new Promise<void>(resolve=>setTimeout(resolve,150))
 const stopAck=(returned:EINativeVoiceReturn,expected:readonly string[])=>returned.events.some(e=>expected.includes(e.kind)&&e.operationId===returned.operationId&&(origin==='https://homebase.local'?['child-process-exited','no-child-active'].includes(String(e.detail.acknowledgment))&&e.detail.stoppedOperationId===e.operationId:e.detail.hardwareStopVerified===false&&(e.detail.stopAcknowledgment==='android-cancel-destroy-and-tts-stop-api-return'||(e.kind==='ended'&&returned.status==='ended'&&returned.language===null&&returned.operationId===0&&returned.capabilities===null&&e.detail.stopAcknowledgment==='android-session-tombstone-no-resources-created'&&e.detail.resourcesCreated===false))))
 const terminal=async(c:EIVoiceContext,returned:EINativeVoiceReturn,expected:readonly string[])=>{const deadline=Date.now()+30000;while(!expected.includes(returned.status)||!stopAck(returned,expected)){if(!['stopping',...expected].includes(returned.status)||Date.now()>deadline)throw Error('Native voice stop acknowledgment unavailable');await wait();returned=await post(c,{action:'poll',operationId:returned.operationId,cursor:returned.nextCursor})}return returned}
 const operation=(kind:'listen'|'speak',language:string,c:EIVoiceContext,source?:EIVoiceScope,text?:string):EIVoiceRecognition=>{
  const s=state(c),id=++s.operation;if(id>128)throw Error('Voice operation capacity reached');let started=false,stopped=false,finished=false,timer:ReturnType<typeof setTimeout>|null=null,wake:(()=>void)|null=null
  const output:EIVoiceRecognition={onstart:null,onend:null,onerror:null,onresult:null,async start(){if(started)throw Error('Voice operation already started');started=true;try{let returned=await post(c,{action:kind,language,operationId:id,...(kind==='speak'?{source,text}:{})});while(!stopped&&!finished){if(returned.operationId!==id||returned.language!==language)throw Error('Native voice operation or language changed');for(const e of returned.events){if(e.sequence<=s.cursor)continue;if(e.sequence!==s.cursor+1)throw Error('Native voice event gap');s.cursor=e.sequence;if(e.operationId!==id)continue;if(kind==='speak'&&['speaking','speech-ended'].includes(e.kind)&&(!same(e.detail.source as EIVoiceScope,source!)||e.detail.text!==text))throw Error('Native spoken source changed');if(e.kind===(kind==='listen'?'listening':'speaking'))output.onstart?.({nativeEvent:e});if(e.kind==='transcript'&&kind==='listen')output.onresult?.(e.sequence,e.detail.text as string,{nativeEvent:e});if(e.kind===(kind==='listen'?'recognition-ended':'speech-ended')){finished=true;output.onend?.({nativeEvent:e})}if(e.kind==='failed'){finished=true;output.onerror?.(String(e.detail.code??'native-speech-failed'))}}
    if(stopped||finished)break;if(['ended','failed','cancelled','unavailable'].includes(returned.status)){finished=true;output.onerror?.(`Native voice ${returned.status}`);break}if(returned.events.length<8)await new Promise<void>(resolve=>{wake=resolve;timer=setTimeout(()=>{timer=null;wake=null;resolve()},150)});if(stopped)break;returned=await post(c,{action:'poll',operationId:id,cursor:s.cursor})}
   }catch(reason){if(!stopped){finished=true;output.onerror?.(String(reason))}}},async abort(){stopped=true;if(timer){clearTimeout(timer);timer=null}wake?.();wake=null;if(!started)return;const returned=await terminal(c,await post(c,{action:'cancel',operationId:id}),['cancelled','ended']);if(returned.operationId!==id||!['cancelled','ended'].includes(returned.status))throw Error('Native voice stop was not acknowledged');return {nativeReturn:returned}}}
  return output
 }
 return {name:options.name,availabilityReceipt:c=>{const value=state(c).availability;return value?{...value}:undefined},async available(language,c){const s=state(c),deadline=Date.now()+30000;let returned=await post(c,{action:'availability',language});while(returned.status==='checking'&&returned.capabilities===null){if(s.endRequested)return false;if(Date.now()>deadline)throw Error('Local speech availability timed out');await wait();if(s.endRequested)return false;returned=await post(c,{action:'poll',operationId:returned.operationId,cursor:returned.nextCursor})}if(s.endRequested)return false;s.cursor=Math.max(s.cursor,returned.nextCursor);if(returned.language!==language)throw Error('Native voice language changed');state(c).availability=returned;return returned.capabilities?.recognitionAvailable===true},recognition:(language,c)=>operation('listen',language,c),speech:(text,language,c)=>operation('speak',language,c,c.source,text),async end(c){state(c).endRequested=true;const returned=await terminal(c,await post(c,{action:'end'}),['ended']);if(returned.status!=='ended')throw Error('Native voice session end was not acknowledged');return {nativeReturn:returned}}}
}
