/** Explicit foreground voice session; providers enforce local processing. */
export type EIVoiceScope=Readonly<{address:string;revision:number;sourceId:string}>
export type EIVoiceContext=Readonly<{id:string;scope:EIVoiceScope}>
export type EIVoiceTranscript=Readonly<{id:string;sessionId:string;sequence:number;text:string;language:string;scope:EIVoiceScope;provider:string;processing:'on-device';rawAudioRetained:false;providerReturn?:Readonly<Record<string,unknown>>}>
export type EIVoiceEvent=Readonly<{id:string;sessionId:string;sequence:number;parentEventId:string|null;kind:string;scope:EIVoiceScope;at:number;detail:Readonly<Record<string,unknown>>}>
export type EIVoiceStatus='ended'|'checking'|'listening'|'muting'|'muted'|'stopping'|'speaking'|'idle'|'unavailable'|'failed'
export interface EIVoiceOperation {start():void|Promise<void>;abort():void|Readonly<Record<string,unknown>>|Promise<void|Readonly<Record<string,unknown>>>;onstart:((detail?:Readonly<Record<string,unknown>>)=>void)|null;onend:((detail?:Readonly<Record<string,unknown>>)=>void)|null;onerror:((reason:string)=>void)|null}
export interface EIVoiceRecognition extends EIVoiceOperation {onresult:((index:number,text:string,detail?:Readonly<Record<string,unknown>>)=>void)|null}
export interface EIVoicePlatform {name:string;availabilityReceipt?(context:EIVoiceContext):Readonly<Record<string,unknown>>|undefined;end?(context:EIVoiceContext):void|Readonly<Record<string,unknown>>|Promise<void|Readonly<Record<string,unknown>>>;available(language:string,context:EIVoiceContext):Promise<boolean>;recognition(language:string,context:EIVoiceContext):EIVoiceRecognition;speech(text:string,language:string,context:EIVoiceContext&{source:EIVoiceScope}):EIVoiceOperation}
export function createEIVoiceCall(platform:EIVoicePlatform,handlers:{state:(status:EIVoiceStatus)=>void;transcript:(value:EIVoiceTranscript)=>void;event:(value:EIVoiceEvent)=>void},clock=()=>Date.now()){
 let generation=0,session:(EIVoiceContext&{language:string})|null=null,recognition:EIVoiceRecognition|null=null,speech:EIVoiceOperation|null=null,status:EIVoiceStatus='ended',permitted=false,sequence=0,transcripts=0,stopTail=Promise.resolve(true)
 const update=(value:EIVoiceStatus)=>{status=value;handlers.state(value)}
 const event=(kind:string,detail:Record<string,unknown>={})=>{if(!session)return;const number=++sequence;handlers.event(Object.freeze({id:`${session.id}/event/${number}`,sessionId:session.id,sequence:number,parentEventId:number>1?`${session.id}/event/${number-1}`:null,kind,scope:session.scope,at:clock(),detail:Object.freeze({...detail})}))}
 const context=():EIVoiceContext=>Object.freeze({id:session!.id,scope:session!.scope})
 const stopResources=()=>{stopTail=stopTail.then(async()=>{let success=true;for(const [kind,operation]of [['capture',recognition],['speech',speech]] as const){if(!operation)continue;operation.onstart=null;operation.onend=null;operation.onerror=null;if('onresult'in operation)(operation as EIVoiceRecognition).onresult=null;try{const receipt=await operation.abort();event('provider-stop-returned',{channel:kind,...(receipt?{providerReturn:receipt}:{acknowledgment:'provider-method-return'})});if(kind==='capture'&&recognition===operation)recognition=null;if(kind==='speech'&&speech===operation)speech=null}catch(reason){event(`${kind}-stop-failed`,{reason:String(reason)});success=false}}return success});return stopTail}
 const fail=async(token:number,kind:string,reason:unknown)=>{if(token!==generation)return;const failureToken=++generation;event(kind,{reason:String(reason)});await stopResources();if(failureToken===generation)update('failed')}
 const listen=async(token:number)=>{if(!session||token!==generation)return;if(!await stopResources()){if(token===generation)update('failed');return}if(!session||token!==generation)return;const current=session,seen=new Set<number>();let r:EIVoiceRecognition
  try{r=platform.recognition(current.language,context())}catch(reason){await fail(token,'recognition-failed',reason);return}recognition=r;update('checking');event('listen-requested',{provider:platform.name,processing:'on-device'})
  r.onstart=detail=>{if(token===generation&&recognition===r){event('listening',detail?{providerReturn:detail}:{});update('listening')}}
  r.onresult=(index,text,detail)=>{if(token!==generation||recognition!==r||seen.has(index))return;seen.add(index);if(!Number.isSafeInteger(index)||index<0||typeof text!=='string'||!text.trim()||text.length>8192||transcripts>=64){void fail(token,'transcript-rejected','empty-or-resource-bound');return}const value=Object.freeze({id:`${current.id}/transcript/${++transcripts}`,sessionId:current.id,sequence:transcripts,text,language:current.language,scope:current.scope,provider:platform.name,processing:'on-device' as const,rawAudioRetained:false as const,...(detail?{providerReturn:detail}:{})});event('transcript-returned',{transcript:value});handlers.transcript(value)}
  r.onend=detail=>{if(token!==generation||recognition!==r)return;recognition=null;event('recognition-ended',detail?{providerReturn:detail}:{});update('idle')};r.onerror=reason=>void fail(token,'recognition-failed',reason)
  try{await r.start()}catch(reason){await fail(token,'recognition-failed',reason)}
 }
 const end=async(reason='user-ended')=>{const token=++generation;if(session)update('stopping');const stopped=await stopResources();if(token!==generation)return;if(!stopped){update('failed');return}let terminalReceipt:void|Readonly<Record<string,unknown>>=undefined;try{if(session)terminalReceipt=await platform.end?.(context())}catch(reason){if(token===generation){event('session-stop-failed',{reason:String(reason)});update('failed')}return}if(token!==generation)return;event('ended',{reason,...(terminalReceipt?{providerReturn:terminalReceipt}:{})});session=null;permitted=false;update('ended')}
 return {status:()=>status,active:()=>session!==null,canListen:()=>!!session&&permitted&&transcripts<64,
  async start(id:string,scope:EIVoiceScope,language:string){if(!id||id.length>128||!scope.address||!Number.isSafeInteger(scope.revision)||scope.revision<0||!scope.sourceId||!language||language.length>80)throw Error('Invalid voice source scope');const token=++generation;update('checking');if(!await stopResources()){if(token===generation)update('failed');return}if(token!==generation)return;try{if(session)await platform.end?.(context())}catch(reason){await fail(token,'session-stop-failed',reason);return}if(token!==generation)return;event('ended',{reason:'replaced-session'});session={id,scope:Object.freeze({...scope}),language};permitted=false;sequence=0;transcripts=0;event('requested',{language});try{const available=await platform.available(language,context());if(token!==generation||!session)return;event('availability-returned',{available,...(platform.availabilityReceipt?.(context())?{providerReturn:platform.availabilityReceipt(context())}:{})});if(!available){event('unavailable',{reason:'local-recognition-unavailable'});update('unavailable');return}permitted=true;await listen(token)}catch(reason){if(token===generation&&session){event('unavailable',{reason:String(reason)});update('unavailable')}}},
  async mute(){if(!session)return;const token=++generation;update('muting');const stopped=await stopResources();if(token!==generation)return;if(!stopped){update('failed');return}event('muted');update('muted')},
  async resume(){if(session&&permitted&&transcripts<64&&!['checking','listening','muting','stopping'].includes(status))await listen(++generation)},
  async speak(source:EIVoiceScope,text:string){if(!session)throw Error('Start a voice session first');if(!source.address||!source.sourceId||!Number.isSafeInteger(source.revision)||typeof text!=='string'||!text.trim()||text.length>8192)throw Error('Invalid spoken source');const token=++generation,bound=Object.freeze({...source});update('checking');if(!await stopResources()){if(token===generation)update('failed');return}if(token!==generation||!session)return;event('speech-requested',{source:bound,text});let output:EIVoiceOperation;try{output=platform.speech(text,session.language,Object.freeze({...context(),source:bound}))}catch(reason){await fail(token,'speech-failed',reason);return}speech=output;output.onstart=detail=>{if(token===generation&&speech===output){event('speech-started',{source:bound,...(detail?{providerReturn:detail}:{})});update('speaking')}};output.onend=detail=>{if(token!==generation||speech!==output)return;speech=null;event('speech-ended',{source:bound,text,scope:'speech-provider-end-event',userHearingVerified:false,...(detail?{providerReturn:detail}:{})});update('idle')};output.onerror=reason=>void fail(token,'speech-failed',reason);try{await output.start()}catch(reason){await fail(token,'speech-failed',reason)}},end}
}
