import { FACES, fromKey, key } from "./address.ts"
import { projectWhole } from "./projection.ts"

export type ScenePoint = Readonly<{
  id: string
  kind: "CHILD_WHOLE" | "RESOLVED_RELATION"
  position: readonly [number, number, number]
  result: "SOURCE" | "SAME" | "DIFFERENT"
  arrivalCount: number
  selected: boolean
  provenance: "GENERATED"
  dependsOnSelectedFormalization: true
}>

export type SceneEdge = Readonly<{
  id: string
  from: string
  to: string
  contributor: string
  provenance: "GENERATED"
  dependsOnSelectedFormalization: true
}>

export type WholeScene = Readonly<{
  level: number
  points: readonly ScenePoint[]
  edges: readonly SceneEdge[]
  bounds: Readonly<{
    minimum: readonly [number, number, number]
    maximum: readonly [number, number, number]
  }>
  accessibilitySummary: string
}>

function coordinates(address: string): readonly [number, number, number] {
  const value = fromKey(address)
  return Object.freeze([value.x, value.y, value.z])
}

function extrema(
  points: readonly ScenePoint[],
): WholeScene["bounds"] {
  const axes = [0, 1, 2] as const
  const minimum = axes.map((axis) =>
    Math.min(...points.map((point) => point.position[axis])),
  ) as [number, number, number]
  const maximum = axes.map((axis) =>
    Math.max(...points.map((point) => point.position[axis])),
  ) as [number, number, number]
  return Object.freeze({
    minimum: Object.freeze(minimum),
    maximum: Object.freeze(maximum),
  })
}

export function buildWholeScene(
  level: number,
  selectedNormalizedAddress: string | null = null,
): WholeScene {
  const projection = projectWhole(level)
  const childPoints = FACES.map((face): ScenePoint =>
    Object.freeze({
      id: `child:${key(face)}`,
      kind: "CHILD_WHOLE",
      position: coordinates(key(face)),
      result: "SOURCE",
      arrivalCount: 0,
      selected: false,
      provenance: "GENERATED",
      dependsOnSelectedFormalization: true,
    }),
  )
  const relationPoints = projection.entries.map((entry): ScenePoint =>
    Object.freeze({
      id: `relation:${entry.normalizedAddress}`,
      kind: "RESOLVED_RELATION",
      position: coordinates(entry.normalizedAddress),
      result: entry.result,
      arrivalCount: entry.arrivalCount,
      selected: entry.normalizedAddress === selectedNormalizedAddress,
      provenance: "GENERATED",
      dependsOnSelectedFormalization: true,
    }),
  )
  const edges = projection.entries.flatMap((entry) =>
    entry.contributors.map((contributor, index): SceneEdge =>
      Object.freeze({
        id: `presentation:${contributor}>${entry.normalizedAddress}:${index}`,
        from: `child:${contributor}`,
        to: `relation:${entry.normalizedAddress}`,
        contributor,
        provenance: "GENERATED",
        dependsOnSelectedFormalization: true,
      }),
    ),
  )
  const points = Object.freeze([...childPoints, ...relationPoints])
  const same = relationPoints.filter((point) => point.result === "SAME").length
  const different = relationPoints.filter(
    (point) => point.result === "DIFFERENT",
  ).length
  return Object.freeze({
    level,
    points,
    edges: Object.freeze(edges),
    bounds: extrema(points),
    accessibilitySummary:
      `Six complete child wholes make ${edges.length} presentations to `
      + `${relationPoints.length} containing-grain relations. `
      + `${same} resolve to Same and ${different} remain Different. `
      + "Every point and edge is generated by a kernel that depends on "
      + "selected six-Face and parity formalizations.",
  })
}
