import {useEffect,useRef,useState} from 'react'
import type {EILedger,EIProposal} from './model/ei-engine'
import {proposeEIDiscoveryBatch,readEIDiscoverySteps,requestEIHomebaseDiscovery,type EIDiscoveryReturn} from './model/ei-discovery'
import {observeEIAndroidDiscovery,observeEIBrowserDiscovery} from './model/ei-discovery-providers'
import type {HomebaseDiscoveryScope} from './model/ei-discovery-types'
export function EIDiscovery({ledger,userRoot,disabled,frameReady,onStage,onState,onStart,onTicket}:{ledger:EILedger;userRoot:string;disabled:boolean;frameReady:boolean;onStage:(proposal:EIProposal,focusAddress:string,startup:boolean)=>void;onState:(state:string)=>void;onStart:()=>void;onTicket:(ticket:{id:string;address:string;message:string;detail:string})=>void}){
 const [visible,setVisible]=useState(typeof document==='undefined'||!document.hidden)
 const [pending,setPending]=useState<EIDiscoveryReturn|null>(null),[session,setSession]=useState<{scope:HomebaseDiscoveryScope;last:EIDiscoveryReturn|null;queued:EIDiscoveryReturn[];startup:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[stopped,setStopped]=useState(false)
 const nativeActive=useRef<{scope:HomebaseDiscoveryScope;scanId:string}|null>(null)
 const automatic=useRef(false),alive=useRef(true),epoch=useRef(0),locked=useRef(false),staged=useRef<string|null>(null),live=useRef({ledger,userRoot,disabled});live.current={ledger,userRoot,disabled}
 const origin=typeof window==='undefined'?'':window.location.origin
 useEffect(()=>{alive.current=true;const visibility=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',visibility);return()=>{alive.current=false;epoch.current++;const active=nativeActive.current;nativeActive.current=null;if(active&&origin==='https://homebase.local')void requestEIHomebaseDiscovery(origin,{...active.scope,action:'cancel',scanId:active.scanId}).catch(()=>{});document.removeEventListener('visibilitychange',visibility)}},[])
 const request=async(kind:'system'|'folder',startup=false)=>{
  if(locked.current||disabled)return;automatic.current=true;const root=ledger.records.find(r=>r.address===userRoot);if(!root)return
  const scope={requestId:crypto.randomUUID(),address:userRoot,revision:root.is.revision},token=++epoch.current;locked.current=true;setBusy(true);setError('');setStopped(false);staged.current=null;onStart();onState('Reading adjacent provider addresses')
  try{const results=origin==='https://homebase.local'?[await requestEIHomebaseDiscovery(origin,{...scope,action:'start',kind})]:origin==='https://appassets.androidplatform.net'?await observeEIAndroidDiscovery(scope,origin):observeEIBrowserDiscovery(scope,navigator,screen)
   if(origin==='https://homebase.local')nativeActive.current={scope,scanId:results[0].value.scanId};if(!alive.current||token!==epoch.current){if(origin==='https://homebase.local'){void requestEIHomebaseDiscovery(origin,{...scope,action:'cancel',scanId:results[0].value.scanId}).catch(()=>{});nativeActive.current=null}if(!alive.current)return;setStopped(true)}setSession({scope,last:null,queued:results.slice(1),startup});setPending(results[0])
  }catch(reason){if(alive.current){setError(String(reason));onTicket({id:scope.requestId,address:scope.address,message:String(reason),detail:JSON.stringify({scope,kind,returned:false})});onState('Provider return unavailable')}}finally{locked.current=false;if(alive.current)setBusy(false)}
 }
 // User requested initial mapping of exposed computer information. Folder
 // selection remains an explicit separate action; no path is invented here.
 useEffect(()=>{if(!automatic.current&&!disabled&&visible&&ledger.records.some(r=>r.address===userRoot)){const timer=setTimeout(()=>{if(!automatic.current)void request('system',true)},0);return()=>clearTimeout(timer)}},[disabled,userRoot,visible])
 useEffect(()=>{
  if(!visible||!pending||!session||stopped||busy||disabled||!frameReady||locked.current)return
  const accepted=readEIDiscoverySteps(ledger).find(s=>s.data.userRoot===userRoot&&s.data.carrier===pending.carrier&&s.data.batch.scanId===pending.value.scanId&&s.data.batch.sequence===pending.value.sequence)
  if(accepted){staged.current=null;setSession(current=>current?{...current,last:pending}:null);setPending(null);onState(`Provider ${pending.value.status} · ${pending.value.progress.returned} returned`);return}
  const id=`${pending.value.scanId}/${pending.value.sequence}`;if(staged.current===id)return
  const token=epoch.current,base=ledger;locked.current=true;setBusy(true)
  void proposeEIDiscoveryBatch(base,userRoot,pending).then(result=>{if(!alive.current||token!==epoch.current||live.current.userRoot!==userRoot)return;if(live.current.ledger!==base)return;if(result.proposal){staged.current=id;onState('Ingesting returned neighbours');onStage(result.proposal,pending.value.sequence===0?result.focusAddress:'',session.startup)}}).catch(reason=>{if(alive.current){setError(String(reason));setStopped(true);if(pending.carrier==='homebase')void requestEIHomebaseDiscovery(origin,{...session.scope,action:'cancel',scanId:pending.value.scanId}).catch(()=>{});onTicket({id:pending.value.requestId+':'+pending.value.sequence,address:pending.value.address,message:String(reason),detail:pending.raw});onState('Pending observation retained · continuation needed')}}).finally(()=>{locked.current=false;if(alive.current)setBusy(false)})
 },[pending,session,ledger,userRoot,disabled,frameReady,busy,stopped,visible])
 useEffect(()=>{
  if(!visible||pending||!session?.last||stopped||busy||disabled||!frameReady||locked.current)return
  const last=session.last;if(last.value.status!=='running'||last.value.nextCursor===null)return
  const token=epoch.current;locked.current=true;setBusy(true)
  const next=async()=>{try{const returned=session.queued[0]??await requestEIHomebaseDiscovery(origin,{...session.scope,action:'next',scanId:last.value.scanId,cursor:last.value.nextCursor!});if(!alive.current||token!==epoch.current)return;if(returned.value.status!=='running')nativeActive.current=null;setSession(current=>current?{...current,queued:current.queued.slice(1)}:null);setPending(returned)}catch(reason){if(alive.current){setError(String(reason));setStopped(true);onTicket({id:session.scope.requestId+':next:'+last.value.nextCursor,address:session.scope.address,message:String(reason),detail:JSON.stringify({scope:session.scope,scanId:last.value.scanId,cursor:last.value.nextCursor,returned:false})})}}finally{locked.current=false;if(alive.current)setBusy(false)}}
  void next()
 },[pending,session,stopped,busy,disabled,frameReady,origin,visible])
 const stop=()=>{epoch.current++;setStopped(true);onTicket({id:session?.scope.requestId??'starting-discovery',address:session?.scope.address??userRoot,message:'Discovery acquisition set idle',detail:JSON.stringify({scanId:(pending??session?.last)?.value.scanId??null,pendingSequence:pending?.value.sequence??null,domainDifference:'not-inferred'})});staged.current=null;onState('Idle · source and returned observations retained');const last=pending??session?.last;if(origin==='https://homebase.local'&&session&&last)void requestEIHomebaseDiscovery(origin,{...session.scope,action:'cancel',scanId:last.value.scanId}).catch(reason=>setError(String(reason)))}
 const exportPending=()=>{if(!pending)return;const blob=new Blob([pending.raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pending-addressed-observation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section aria-label="Addressed device mapping"><button disabled={disabled||busy} onClick={()=>void request('system')}>Map this environment</button>{origin==='https://homebase.local'&&<button disabled={disabled||busy} onClick={()=>void request('folder')}>Map a selected folder</button>}{(session||busy)&&<button onClick={stop}>Idle discovery</button>}{stopped&&!pending&&session?.last?.value.status==='running'&&<button disabled={busy||disabled} onClick={()=>{setError('');setStopped(false)}}>Retry provider return</button>}{pending&&stopped&&<><button onClick={exportPending}>Save pending return</button><button disabled={disabled||busy} onClick={()=>{staged.current=null;setError('');setStopped(false)}}>Retry pending return</button></>}{(pending??session?.last)&&<small>{(pending??session!.last)!.value.progress.returned} observations returned · {(pending??session!.last)!.value.status}</small>}{error&&<p role="alert">{error}</p>}</section>
}
