import {EI_HOME_VIEW} from './model/ei-home-view'
import {readGuideAttempts} from './model/ei-guide-steps'
import {readEISeedPlantings,deriveEISeedSowingTargets} from './model/ei-seed-planting'
import {createEISeedDrag,type EISeedDropTarget} from './model/ei-seed-drag'
import {EIRootTree} from './EIRootTree'
import {projectEIEnvironmentHorizon,projectEIGroundLandmark,fitEIEnvironmentObjects} from './model/ei-field-environment'
import {createEIPinch,panEIObserver,zoomEIObserverAt,eiMouseGesture} from './model/ei-pinch'
import {useEIModelerObjects} from './useEIModelerObjects'
import type {EIFieldPresentationSnapshot} from './model/ei-field-save'
import {useEIFitImprovement} from './useEIFitImprovement'
import {EIFieldAction} from './EIFieldAction'
import {projectEIWorldObject,type EIWorldPresentation} from './model/ei-world-object'
import {deriveEIFieldObject,projectEIFieldTetrahedron} from './model/ei-field-object'
import {resolveEIObserverZero} from './model/ei-observer-zero'
import {EI_FIELD_NODE_PATH,createEISvgSceneGeometry} from './model/ei-svg-frame-witness'
import {createEIThreadDrawPlan} from './model/ei-thread-draw'
import {projectEIThreadDrawFrame} from './model/ei-thread-draw-frame'
import {useEIThreadDrawing} from './useEIThreadDrawing'
import {useMemo,useState,useEffect,useLayoutEffect,useRef,type ReactNode,type CSSProperties} from 'react'
import type {EILedger} from './model/ei-engine'
import type {EIGrain} from './model/ei-grain-identity'
import {projectEIFieldArray,clampEIFieldZoom} from './model/ei-field-array-view'
export function EIFieldArray({ledger,address,revision,grain,disabled,onSelect,contextLabel,rootLabel,nodeLabel,relationNode,tetrahedronPositions,recursiveFrames,onSelectFrame,visibility,retrospective,sourceAddress,children,workspaceOpen=false,onCloseWorkspace,onReaddress,onChooseZero,onPlant,initialDrawPhase=0,initialObserverZero,initialZeroHistory=[],initialPresentation,onSnapshot,activity,focusRequest,onFrameReturn}:{ledger:EILedger;address:string;revision:number|null;grain:EIGrain;disabled:boolean;onSelect:(address:string)=>void;contextLabel?:string;rootLabel?:string;nodeLabel?:(address:string)=>string;relationNode?:(address:string)=>boolean;tetrahedronPositions?:ReadonlyMap<string,number>;recursiveFrames?:ReadonlyArray<{address:string;parent:string|null;tipIndex:number|null;depth:number;scale:number}>;onSelectFrame?:(address:string)=>void;visibility?:Readonly<{mapping:boolean;nodes:boolean;paths:boolean;connections:boolean;labels:boolean}>;retrospective?:Readonly<{selected:string;onSelect:(role:string)=>void}>;sourceAddress:string;children?:ReactNode;workspaceOpen?:boolean;onCloseWorkspace?:()=>void;onReaddress?:(address:string)=>void;onChooseZero?:(address:string)=>void;onPlant?:(target:EISeedDropTarget)=>void;initialDrawPhase?:number;initialObserverZero?:string;initialZeroHistory?:readonly string[];initialPresentation?:EIFieldPresentationSnapshot|null;onSnapshot?:(read:()=>EIFieldPresentationSnapshot)=>void;focusRequest?:Readonly<{id:number;address:string}>;onFrameReturn?:(revision:number,complete:boolean)=>void;activity?:Readonly<{state:string;operation:string|null;result:string|null;environment?:string}>}){
 const shown=visibility??{mapping:true,nodes:true,paths:true,connections:true,labels:true}
 const [observerZero,setObserverZero]=useState(initialPresentation?.observerZero??initialObserverZero??sourceAddress),[zeroChosen,setZeroChosen]=useState(true),[zeroHistory,setZeroHistory]=useState<string[]>([...new Set([sourceAddress,...(initialPresentation?.zeroHistory??initialZeroHistory),initialPresentation?.observerZero??initialObserverZero??sourceAddress])])
 const [presentationMode,setPresentationMode]=useState<EIWorldPresentation>(initialPresentation?.presentationMode??'solar')
 const [gestureActive,setGestureActive]=useState(false)
 const [zeroFocusRequest,setZeroFocusRequest]=useState(0),fittedZeroRequest=useRef(0)
 const [orientation,setOrientation]=useState({roll:0,...(initialPresentation?.orientation??{yaw:.46,pitch:.18})}),[orbiting,setOrbiting]=useState(false)

 const object=useMemo(()=>deriveEIFieldObject(ledger,observerZero,grain),[ledger,observerZero,grain])
 const tetrahedron=useMemo(()=>projectEIFieldTetrahedron(orientation.yaw,orientation.pitch),[orientation.yaw,orientation.pitch])
 const recursiveProjection=useMemo(()=>{const positions=new Map<string,{x:number;y:number}>();return (recursiveFrames??[]).map(frame=>{const parent=frame.parent?positions.get(frame.parent):null,parentFrame=frame.parent?recursiveFrames?.find(item=>item.address===frame.parent):null,tip=frame.tipIndex===null?null:tetrahedron.points[frame.tipIndex]!,x=(parent?.x??0)+(tip?tip.x*(parentFrame?.scale??1)*12:0),y=(parent?.y??0)+(tip?tip.y*(parentFrame?.scale??1)*12:0);positions.set(frame.address,{x,y});return {...frame,x,y}})},[recursiveFrames,tetrahedron])
 const wholeField=useMemo(()=>{const original=projectEIFieldArray(ledger,grain,revision===null?undefined:{address,revision},observerZero);if(!tetrahedronPositions)return original;const nodes=original.nodes.map(node=>{const index=tetrahedronPositions.get(node.address),point=index===undefined?null:tetrahedron.points[index];return {...node,x:point?point.x*12:0,y:point?point.y*12:0}}),xs=[...nodes.map(node=>node.x),...tetrahedron.points.map(point=>point.x*12),...recursiveProjection.flatMap(frame=>tetrahedron.points.map(point=>frame.x+point.x*12*frame.scale))],ys=[...nodes.map(node=>node.y),...tetrahedron.points.map(point=>point.y*12),...recursiveProjection.flatMap(frame=>tetrahedron.points.map(point=>frame.y+point.y*12*frame.scale))];return {...original,nodes,bounds:{left:Math.min(...xs)-110,right:Math.max(...xs)+110,top:Math.min(...ys)-110,bottom:Math.max(...ys)+110}}},[ledger,grain,address,revision,observerZero,tetrahedronPositions,tetrahedron,recursiveProjection])
 const field=useMemo(()=>{if(!zeroChosen)return wholeField;const parts=new Set([observerZero,...object.partAddresses,...zeroHistory]);const nodes=wholeField.nodes.filter(node=>parts.has(node.address));const edges=wholeField.edges.filter(edge=>parts.has(edge.from)&&parts.has(edge.to));const xs=nodes.map(node=>node.x),ys=nodes.map(node=>node.y);return {...wholeField,nodes,edges,bounds:tetrahedronPositions?wholeField.bounds:{left:Math.min(...xs)-110,right:Math.max(...xs)+110,top:Math.min(...ys)-150,bottom:Math.max(...ys)+90}}},[wholeField,zeroChosen,observerZero,object,zeroHistory])
 const drawPlan=useMemo(()=>createEIThreadDrawPlan(field.nodes,field.edges,observerZero),[field,observerZero])
 const [view,setView]=useState<{x:number;y:number;zoom:number}|null>(initialPresentation?.view??null),[search,setSearch]=useState(''),[finding,setFinding]=useState(false),[size,setSize]=useState({width:1200,height:800})
 const fieldSvg=useRef<SVGSVGElement>(null),surface=useRef<HTMLElement>(null),workspace=useRef<HTMLDivElement>(null),wasOpen=useRef(false)
 useEffect(()=>{if(workspaceOpen){workspace.current?.focus();workspace.current?.scrollIntoView({block:'start'})}else if(wasOpen.current){const selected=surface.current?.querySelector<SVGGElement>('[aria-pressed="true"]');selected?.focus();selected?.scrollIntoView({block:'center'})}wasOpen.current=workspaceOpen},[workspaceOpen])
 useEffect(()=>{if(finding&&!workspaceOpen)surface.current?.querySelector<HTMLInputElement>('.ei-field-find input')?.focus()},[finding,workspaceOpen])
 const readdress=(target:EventTarget|null)=>{if(disabled||!onReaddress||!(target instanceof Element))return;const at=target.closest('[data-field-node]')?.getAttribute('data-field-node'),node=field.nodes.find(item=>item.address===at);if(node){const next=resolveEIObserverZero(ledger,node.address,grain);setObserverZero(next.address);setZeroHistory(history=>history.includes(next.address)?history:[...history,next.address]);setZeroChosen(true);setZeroFocusRequest(value=>value+1);onChooseZero?.(next.address)}}
 const planting=useRef(createEISeedDrag()),[plantPoint,setPlantPoint]=useState<{x:number;y:number}|null>(null)
 const pointer=useRef<{x:number;y:number;startX:number;startY:number;mode?:'pan'|'orbit'}|null>(null),suppressClick=useRef(false),pinch=useRef(createEIPinch())
 useEffect(()=>{const svg=fieldSvg.current;if(!svg||typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(entries=>{const box=entries[0]?.contentRect;if(box?.width&&box.height)setSize({width:box.width,height:box.height})});observer.observe(svg);return()=>observer.disconnect()},[])
 const {width,height}=size,b=field.bounds
 const fit=fitEIEnvironmentObjects(b,size)
 const camera=view??fit,byAddress=new Map(field.nodes.map(node=>[node.address,node])),selected=byAddress.get(address)
 const gestureCamera=useRef({...camera,roll:orientation.roll});gestureCamera.current={...camera,roll:orientation.roll}
 const contained=useMemo(()=>{const index=new Map(ledger.records.map(record=>[record.address,new Set<string>()]));for(const record of ledger.records){for(const parent of record.parents)index.get(parent)?.add(record.address);for(const relation of record.relations)if(relation.relation==='CONTAINS'&&index.has(relation.address))index.get(record.address)!.add(relation.address)}return index},[ledger])
 const entities=useMemo(()=>field.nodes.map(node=>({...node,partCount:contained.get(node.address)?.size??0,root:node.address===observerZero})),[field,contained,observerZero])
 const worldObjects=useMemo(()=>new Map(entities.map(node=>[node.address,relationNode?.(node.address)?{...projectEIWorldObject(node,orientation.yaw,orientation.pitch,presentationMode),path:'M0 -12L12 0L0 12L-12 0Z',bounds:{left:-12,right:12,top:-12,bottom:12}}:projectEIWorldObject(node,orientation.yaw,orientation.pitch,presentationMode)])),[entities,orientation,presentationMode,relationNode])
 const rasterEntities=useMemo(()=>relationNode?entities.filter(node=>!relationNode(node.address)):entities,[entities,relationNode])
 const raster=useEIModelerObjects(rasterEntities,orientation,presentationMode)
 const viewBox=`${camera.x-width/(2*camera.zoom)} ${camera.y-height/(2*camera.zoom)} ${width/camera.zoom} ${height/camera.zoom}`
 const horizon=useMemo(()=>projectEIEnvironmentHorizon(camera,size,orientation.pitch),[camera.x,camera.y,camera.zoom,width,height,orientation.pitch])
 const groundLandmark=useMemo(()=>projectEIGroundLandmark(size),[width,height])
 const homebase=ledger.records.find(record=>record.address===sourceAddress)
 const goHome=()=>{if(disabled||!homebase)return;setObserverZero(homebase.address);setZeroChosen(true);setZeroHistory(history=>history.includes(homebase.address)?history:[...history,homebase.address]);setZeroFocusRequest(value=>value+1);onChooseZero?.(homebase.address);onReaddress?.(homebase.address);onCloseWorkspace?.()}
 const environmentGeometry=useMemo(()=>({space:'viewport' as const,skyPath:horizon.skyPath,groundPath:horizon.groundPath,linePath:horizon.linePath}),[horizon])
 const sceneTransform=`rotate(${orientation.roll*180/Math.PI} ${camera.x} ${camera.y})`
 const plantings=useMemo(()=>readEISeedPlantings(ledger),[ledger])
 const plantedOutcomes=useMemo(()=>new Map(plantings.map(planting=>[planting.address,readGuideAttempts(ledger,planting.environment.address).find(attempt=>attempt.address===planting.attemptAddress)?.outcomes??[]])),[ledger,plantings])
 const availableSeeds=useMemo(()=>deriveEISeedSowingTargets(ledger),[ledger])
 const seedMirrors=useMemo(()=>availableSeeds.filter(mirror=>byAddress.has(mirror.address)&&byAddress.has(mirror.environmentAddress)).map(mirror=>{const node=byAddress.get(mirror.address)!,environment=byAddress.get(mirror.environmentAddress)!,sprite=raster.sprites.get(mirror.address),c=Math.cos(orientation.roll),s=Math.sin(orientation.roll),rawX=camera.x+(node.x-camera.x)*c-(node.y-camera.y)*s,screenX=(rawX-camera.x)*camera.zoom+width/2,wellLeft=(width-groundLandmark.width)/2+152*groundLandmark.unit,wellRight=wellLeft+192*groundLandmark.unit,clearX=screenX>wellLeft-42&&screenX<wellRight+42?(screenX-(wellLeft-42)<wellRight+42-screenX?wellLeft-42:wellRight+42):screenX,x=camera.x+(Math.max(36,Math.min(width-36,clearX))-width/2)/camera.zoom;return {id:mirror.viewId,address:mirror.address,revision:mirror.revision,sourceId:mirror.sourceId,environmentAddress:mirror.environmentAddress,transform:`translate(${x} ${horizon.horizonY+Math.min(48,height*.184*.38)/camera.zoom}) scale(${0.45/camera.zoom})`,image:sprite?{href:sprite.href,x:sprite.x,y:sprite.y,width:sprite.width,height:sprite.height}:null}}),[availableSeeds,field,raster.sprites,horizon.horizonY,camera.x,camera.y,camera.zoom,orientation.roll,width,height,groundLandmark])
 const plantContext=JSON.stringify([ledger.revision,viewBox,sceneTransform,availableSeeds])
 const currentPlantContext=()=>{const m=fieldSvg.current?.getScreenCTM();return plantContext+JSON.stringify(m?[m.a,m.b,m.c,m.d,m.e,m.f]:null)}
 const cancelPlant=()=>{planting.current.cancel();setPlantPoint(null);setGestureActive(false)}
 const startPlant=(event:React.PointerEvent<SVGGElement>,seedAddress:string)=>{if(disabled||!onPlant||event.button!==0||event.shiftKey||event.ctrlKey||event.metaKey||pinch.current.count)return;const svg=fieldSvg.current;if(!svg)return;const targets:EISeedDropTarget[]=[];for(const element of svg.querySelectorAll<SVGGElement>('[data-environment-mirror]')){if(element.getAttribute('data-seed-address')!==seedAddress||element.getAttribute('opacity')!=='1')continue;const seed=availableSeeds.find(item=>item.viewId===element.getAttribute('data-environment-mirror'));const matrix=element.getScreenCTM();if(!seed||!matrix||!Number.isFinite(matrix.a*matrix.d-matrix.b*matrix.c)||Math.abs(matrix.a*matrix.d-matrix.b*matrix.c)<1e-12)continue;const inverse=matrix.inverse();targets.push({id:seed.viewId,seedAddress:seed.address,seedRevision:seed.revision,seedSourceId:seed.sourceId,environmentAddress:seed.environmentAddress,environmentRevision:seed.environmentRevision,screenToLocal:[inverse.a,inverse.b,inverse.c,inverse.d,inverse.e,inverse.f],radius:70})}if(planting.current.start(event.pointerId,{x:event.clientX,y:event.clientY},currentPlantContext(),targets)){event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);setGestureActive(true);suppressClick.current=false;const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(svg.getScreenCTM()!.inverse());setPlantPoint({x:p.x,y:p.y})}}
 const geometry=useMemo(()=>createEISvgSceneGeometry(Object.fromEntries([...worldObjects].map(([id,shape])=>[id,{path:shape.path,faces:[],...(raster.sprites.has(id)?{image:{href:raster.sprites.get(id)!.href,x:raster.sprites.get(id)!.x,y:raster.sprites.get(id)!.y,width:raster.sprites.get(id)!.width,height:raster.sprites.get(id)!.height}}:{})}])),viewBox,sceneTransform,environmentGeometry,seedMirrors),[worldObjects,viewBox,sceneTransform,raster.sprites,environmentGeometry,seedMirrors])
 const drawing=useEIThreadDrawing(drawPlan,field,fieldSvg,initialDrawPhase,geometry,initialPresentation?.animation,initialPresentation?.idle,raster.ready&&!gestureActive),drawFrame=projectEIThreadDrawFrame(drawPlan,drawing.phase,drawing.retained)
 const drawnNodes=new Map(drawFrame.nodes.map(node=>[node.address,node])),drawnEdges=new Map(drawFrame.edges.map(edge=>[edge.id,edge]))
 const fitEvidence=useMemo(()=>({sourceSnapshot:JSON.stringify([observerZero,ledger.revision,grain]),viewport:{width,height},view:camera,objects:field.nodes.map(node=>{const shape=worldObjects.get(node.address)!;return {address:node.address,revision:node.revision,sourceId:node.sourceId,bounds:{left:node.x+shape.bounds.left,right:node.x+shape.bounds.right,top:node.y+shape.bounds.top,bottom:node.y+shape.bounds.bottom}}})}),[observerZero,ledger.revision,grain,width,height,camera,field,worldObjects])
 const improvement=useEIFitImprovement(fitEvidence,fieldSvg,setView)
 useEffect(()=>{if(initialPresentation)improvement.restore(initialPresentation.improvement)},[])
 useEffect(()=>{onSnapshot?.(()=>({schema:'ei.field-presentation.v1',canonicalRoot:sourceAddress,observerZero,zeroHistory,selectedAddress:address,selectedRevision:revision??ledger.records.find(record=>record.address===address)!.is.revision,grain,view:camera,orientation,presentationMode,animation:drawing.save(),idle:drawing.getIdle(),improvement:improvement.save()}))},[onSnapshot,sourceAddress,observerZero,zeroHistory,address,grain,camera,orientation,presentationMode,drawing.cycle,improvement.state])
 const handledFocus=useRef(0)
 useEffect(()=>{if(disabled||!focusRequest||handledFocus.current===focusRequest.id||!ledger.records.some(r=>r.address===focusRequest.address))return;const next=resolveEIObserverZero(ledger,focusRequest.address,grain);handledFocus.current=focusRequest.id;setObserverZero(next.address);setZeroHistory(history=>history.includes(next.address)?history:[...history,next.address]);setZeroChosen(true);setZeroFocusRequest(value=>value+1);onChooseZero?.(next.address)},[focusRequest,ledger,grain,disabled])
 useEffect(()=>{onFrameReturn?.(ledger.revision,!!drawing.cycle.IS&&drawing.complete&&!drawing.cycle.NEXT&&raster.ready&&!gestureActive)},[ledger.revision,drawing.cycle,drawing.complete,raster.ready,gestureActive,onFrameReturn])
 const chooseZero=()=>{const next=resolveEIObserverZero(ledger,address,grain);setObserverZero(next.address);setZeroHistory(history=>history.includes(next.address)?history:[...history,next.address]);setZeroChosen(true);setZeroFocusRequest(value=>value+1);onChooseZero?.(next.address);onCloseWorkspace?.()}
 useLayoutEffect(()=>{if(!zeroChosen||fittedZeroRequest.current===zeroFocusRequest)return;fittedZeroRequest.current=zeroFocusRequest;const incident=new Set([observerZero,...object.partAddresses]);const local=field.nodes.filter(node=>incident.has(node.address)),xs=local.map(node=>node.x),ys=local.map(node=>node.y);const left=Math.min(...xs)-80,right=Math.max(...xs)+80,top=Math.min(...ys)-80,bottom=Math.max(...ys)+80;setView(fitEIEnvironmentObjects(tetrahedronPositions?wholeField.bounds:{left,right,top,bottom},size,8))},[observerZero,zeroChosen,zeroFocusRequest,field,width,height,object])
 const matches=wholeField.nodes.filter(node=>node.address.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
 useEffect(()=>{const svg=fieldSvg.current;if(!svg)return;const wheel=(event:WheelEvent)=>{if(disabled)return;if(planting.current.active){event.preventDefault();cancelPlant();suppressClick.current=true;return}event.preventDefault();if(event.altKey){readdress(event.target);return}const rect=svg.getBoundingClientRect(),next=zoomEIObserverAt(gestureCamera.current,{x:event.clientX,y:event.clientY},{left:rect.left,top:rect.top,width:rect.width,height:rect.height,logicalWidth:width,logicalHeight:height},event.deltaY,event.deltaMode,Math.min(.08,fit.zoom/10));gestureCamera.current={...next,roll:next.roll??orientation.roll};setView({x:next.x,y:next.y,zoom:next.zoom})};svg.addEventListener('wheel',wheel,{passive:false});return()=>svg.removeEventListener('wheel',wheel)},[disabled,onReaddress,field,width,height,fit.zoom,orientation.roll])
 useEffect(()=>{const cancel=()=>{cancelPlant();pinch.current.cancel();pointer.current=null;suppressClick.current=true;setGestureActive(false)};window.addEventListener('blur',cancel);const hidden=()=>{if(document.hidden)cancel()};document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('blur',cancel);document.removeEventListener('visibilitychange',hidden)}},[])

 const zoom=(factor:number)=>setView({...camera,zoom:clampEIFieldZoom(camera.zoom*factor,Math.min(.08,fit.zoom/10))})
 return <section ref={surface} className="ei-field-array" aria-label="Addressed field array" data-retained-addresses={wholeField.nodes.length}>
  <div className="ei-field-visual" inert={workspaceOpen?true:undefined} aria-hidden={workspaceOpen}>
  <div className="ei-field-hud"><span className="ei-field-activity" data-activity-state={activity?.state??'idle'} aria-label="Active field operation and environment"><small>{activity?.environment??(typeof window==='undefined'?'Shared field':window.location.origin==='https://appassets.androidplatform.net'?'Android local':window.location.origin==='https://homebase.local'?'HOMEBASE local':'Web field')}</small><strong>{activity?.operation?.slice(0,80)??'Observe addressed states'}</strong><small>{activity?.state??'idle'}{activity?.result?` · last return ${activity.result}`:''}</small></span><button aria-label="Switch field presentation" onClick={()=>setPresentationMode(mode=>mode==='solar'?'nature':'solar')}>{visibility&&!shown.labels?(presentationMode==='solar'?'☀':'✿'):presentationMode==='solar'?'Solar':'Nature'}</button><button className="ei-field-address" disabled={disabled} onClick={()=>onSelect(address)} aria-label={`Open selected address ${address}`}><strong>{visibility&&!shown.labels?'◎':address===sourceAddress?(rootLabel??EI_HOME_VIEW.name):address.split('/').at(-1)}</strong>{(!visibility||shown.labels)&&<small>{grain} · {revision??selected?.revision}</small>}</button><span className="ei-field-scope" title={contextLabel??'Addressed field'}>{contextLabel?'Public source':''}</span></div>
  <EIRootTree ledger={ledger} address={address} revision={revision} disabled={disabled} onSelect={target=>onReaddress?.(target)} onChooseZero={chooseZero}/>
  <div className="ei-world-dock" data-ground-contact-y={groundLandmark.contactY} style={{top:groundLandmark.top,width:groundLandmark.width,'--ground-unit':groundLandmark.unit} as CSSProperties} data-sowing-active={availableSeeds.some(seed=>seed.address===address)}><EIFieldAction grounded landmark={homebase?{address:homebase.address,revision:homebase.is.revision,sourceId:homebase.is.source.id,disabled,homeName:rootLabel??EI_HOME_VIEW.name,onOpen:goHome}:undefined} address={observerZero} revision={drawing.cycle.source.revision} sourceId={drawing.cycle.source.sourceId} operation={drawing.complete?'replay-source-frames':drawing.playing?'idle-render-observation':'next-render-frame'} label={drawing.complete?'Replay retained source frames':drawing.playing?'Idle and observe':'Resolve next addressed frame'} hint={drawing.complete?'Replay':drawing.playing?'Observe':'NEXT'} form={{kind:'transition',before:{id:drawing.cycle.IS?.frameKey??'unpresented',label:'IS',address:observerZero,revision:drawing.cycle.source.revision,value:drawing.cycle.IS?String(drawing.cycle.IS.sequence):undefined},...(drawing.cycle.NEXT?{proposed:{id:drawing.cycle.NEXT.frameKey,label:'NEXT',address:observerZero,revision:drawing.cycle.source.revision,value:String(drawing.cycle.NEXT.sequence)}}:{}),...(drawing.cycle.IS?{returned:{id:drawing.cycle.IS.frameKey,label:'Returned',address:observerZero,revision:drawing.cycle.source.revision,value:String(drawing.cycle.IS.sequence),status:'verified-svg-readback'}}:{})}} onClick={drawing.complete?drawing.play:drawing.playing?drawing.idle:drawing.step}/></div>
  <div className="ei-field-find" hidden={!finding}><label>Find address<input value={search} onChange={event=>setSearch(event.target.value)}/></label><select aria-label="Select field address" disabled={disabled} value={matches.some(node=>node.address===address)?address:''} onChange={event=>{if(event.target.value){const node=byAddress.get(event.target.value);if(node)setView({...camera,x:node.x,y:node.y});onReaddress?.(event.target.value);setFinding(false);surface.current?.querySelector<HTMLButtonElement>('.ei-field-address')?.focus()}}}><option value="">{matches.length}</option>{matches.map(node=><option key={node.address} value={node.address}>{node.address}</option>)}</select></div>
  <svg ref={fieldSvg} className="ei-field-surface" viewBox={viewBox} role="group" aria-label="Selectable addressed field" data-field-source-snapshot={fitEvidence.sourceSnapshot} data-observer-zero={observerZero} data-drawing-complete={drawing.complete} data-render-frame={drawing.frame?.frameKey} data-render-generation={drawing.frame?.generation} data-render-sequence={drawing.frame?.sequence} onContextMenu={event=>event.preventDefault()} onClickCapture={event=>{if(suppressClick.current){event.preventDefault();event.stopPropagation()}}}
 onPointerDown={event=>{if(disabled)return;if(planting.current.active){cancelPlant();suppressClick.current=true;return}const mode=event.pointerType==='mouse'?eiMouseGesture(event.button,event.shiftKey):'pan';if(mode==='ignore')return;setGestureActive(true);const fresh=pinch.current.count===0;if(fresh){suppressClick.current=event.pointerType==='mouse'&&event.button!==0;pointer.current={x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY,mode}}const rect=event.currentTarget.getBoundingClientRect();if(pinch.current.down(event.pointerId,{x:event.clientX,y:event.clientY},gestureCamera.current,{left:rect.left,top:rect.top,width:rect.width,height:rect.height,logicalWidth:width,logicalHeight:height})){suppressClick.current=true;pointer.current=null}if(pinch.current.active)event.currentTarget.setPointerCapture(event.pointerId);else (event.target as Element).setPointerCapture(event.pointerId)}}
 onPointerMove={event=>{if(disabled)return;if(planting.current.active){if(planting.current.move(event.pointerId,{x:event.clientX,y:event.clientY},currentPlantContext())){const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(event.currentTarget.getScreenCTM()!.inverse());setPlantPoint({x:p.x,y:p.y});suppressClick.current=true;event.preventDefault()}else {cancelPlant();suppressClick.current=true}return}const rect=event.currentTarget.getBoundingClientRect(),viewport={left:rect.left,top:rect.top,width:rect.width,height:rect.height,logicalWidth:width,logicalHeight:height};if(!pinch.current.has(event.pointerId))return;const next=pinch.current.move(event.pointerId,{x:event.clientX,y:event.clientY},gestureCamera.current,viewport,Math.min(.08,fit.zoom/10));if(next){gestureCamera.current={...next,roll:next.roll??orientation.roll};setView({x:next.x,y:next.y,zoom:next.zoom});setOrientation(current=>({...current,roll:next.roll??current.roll}));suppressClick.current=true;event.preventDefault();return}if(pinch.current.active||!pointer.current)return;const previous=pointer.current;if(!suppressClick.current&&Math.hypot(event.clientX-previous.startX,event.clientY-previous.startY)<5)return;if(orbiting||previous.mode==='orbit')setOrientation(current=>({...current,yaw:current.yaw+(event.clientX-previous.x)/160,pitch:Math.max(-1.5,Math.min(1.5,current.pitch+(event.clientY-previous.y)/160))}));else {const p=panEIObserver(gestureCamera.current,previous,{x:event.clientX,y:event.clientY},viewport);gestureCamera.current={...p,roll:p.roll??orientation.roll};setView({x:p.x,y:p.y,zoom:p.zoom})}pointer.current={...previous,x:event.clientX,y:event.clientY};suppressClick.current=true;event.currentTarget.setPointerCapture(event.pointerId);event.preventDefault()}}
 onPointerUp={event=>{if(planting.current.active){if(planting.current.context!==currentPlantContext())suppressClick.current=true;const target=planting.current.finish(event.pointerId,{x:event.clientX,y:event.clientY},currentPlantContext());cancelPlant();if(suppressClick.current)event.preventDefault();if(target){suppressClick.current=true;onPlant?.(target)}return}if(!pinch.current.has(event.pointerId))return;if(pinch.current.end(event.pointerId))suppressClick.current=true;setGestureActive(pinch.current.count>0);const remaining=pinch.current.remaining;pointer.current=remaining?{...remaining,startX:remaining.x,startY:remaining.y}:null;if(suppressClick.current)event.preventDefault()}}
 onPointerCancel={event=>{if(planting.current.active){cancelPlant();suppressClick.current=true;return}if(!pinch.current.has(event.pointerId))return;pinch.current.end(event.pointerId);setGestureActive(pinch.current.count>0);pointer.current=null;suppressClick.current=true}}
 onLostPointerCapture={event=>{if(planting.current.pointerId===event.pointerId){cancelPlant();suppressClick.current=true;return}if(event.target!==event.currentTarget||event.currentTarget.hasPointerCapture(event.pointerId))return;if(pinch.current.has(event.pointerId)){pinch.current.end(event.pointerId);setGestureActive(pinch.current.count>0);pointer.current=null;suppressClick.current=true}}}>
   <g data-field-environment="" data-environment-space="viewport" pointerEvents="none"><path data-environment-sky="" d={horizon.skyPath} fill="#10263a"/><path data-environment-ground="" d={horizon.groundPath} fill="#31584a"/><path data-environment-horizon="" d={horizon.linePath} stroke="#98b8a4" strokeWidth={1/camera.zoom}/></g>
   <g data-field-mirrors="" data-environment-space="viewport">{seedMirrors.map(mirror=><g key={mirror.id} opacity={drawnNodes.get(mirror.address)?.visible&&!drawnNodes.get(mirror.address)?.unreached?1:0} style={{pointerEvents:drawnNodes.get(mirror.address)?.visible&&!drawnNodes.get(mirror.address)?.unreached?undefined:'none'}} data-environment-mirror={mirror.id} data-seed-address={mirror.address} data-seed-revision={mirror.revision} data-seed-source={mirror.sourceId} data-environment-address={mirror.environmentAddress} data-planting-receipt={plantings.find(p=>p.seed.address===mirror.address&&p.seed.revision===mirror.revision&&p.seed.source.id===mirror.sourceId&&p.environment.address===mirror.environmentAddress&&p.current)?.receiptId} transform={mirror.transform} role="button" tabIndex={disabled||!drawnNodes.get(mirror.address)?.visible||drawnNodes.get(mirror.address)?.unreached?-1:0} aria-hidden={!drawnNodes.get(mirror.address)?.visible||drawnNodes.get(mirror.address)?.unreached} aria-label={`Select seed ${mirror.address} in ${mirror.environmentAddress}`} onClick={()=>{if(!disabled&&!suppressClick.current&&drawnNodes.get(mirror.address)?.visible&&!drawnNodes.get(mirror.address)?.unreached)onReaddress?.(mirror.address)}} onDoubleClick={event=>{event.stopPropagation();if(!disabled&&!suppressClick.current)onSelect(mirror.address)}} onKeyDown={event=>{if(!disabled&&drawnNodes.get(mirror.address)?.visible&&!drawnNodes.get(mirror.address)?.unreached&&(event.key==='Enter'||event.key===' ')){event.preventDefault();if(mirror.address===address)onSelect(mirror.address);else onReaddress?.(mirror.address)}}}><title>{`${availableSeeds.find(seed=>seed.viewId===mirror.id)?.status} · ${mirror.environmentAddress}`}</title>{mirror.image&&<image data-modeler-image="" {...mirror.image}/>}{plantings.filter(p=>p.seed.address===mirror.address&&p.seed.revision===mirror.revision&&p.seed.source.id===mirror.sourceId&&p.environment.address===mirror.environmentAddress).flatMap(p=>(plantedOutcomes.get(p.address)??[]).map((outcome,index)=><circle key={outcome.address} data-planting-outcome={outcome.address} r={76+index*5} fill="none" stroke={outcome.matches?'#c5df90':'#eab677'} strokeWidth="2"><title>{outcome.actual}</title></circle>))}<circle r="70" fill="none" stroke={availableSeeds.find(seed=>seed.viewId===mirror.id)?.status==='available'?'#b3d599':'#eab677'} strokeDasharray={plantings.some(p=>p.seed.address===mirror.address&&p.seed.revision===mirror.revision&&p.seed.source.id===mirror.sourceId&&p.environment.address===mirror.environmentAddress&&p.current)?undefined:'4 5'} pointerEvents="all"/></g>)}</g>
   <g data-observer-scene="" transform={sceneTransform}>
   <g data-visible-layer="connections" style={{visibility:shown.connections?undefined:'hidden'}}>{field.edges.filter(edge=>edge.known).map(edge=>{const draw=drawnEdges.get(edge.id)!,from=byAddress.get(draw.drawFrom)!,to=byAddress.get(draw.drawTo)!,active=edge.from===address||edge.to===address;const prior=draw.retained||(drawFrame.complete&&draw.status==='unreachable');return <g key={edge.id} className={active?'ei-thread active':'ei-thread'} opacity={draw.visible?1:0} data-thread-id={edge.id} data-draw-stage={draw.stage??undefined}><title>{`${edge.from} → ${edge.label} → ${edge.to}`}</title>{prior&&<line x1={from.x} y1={from.y} x2={to.x} y2={to.y} style={{opacity:draw.status==='unreachable'?.06:.16}}/>}<line x1={from.x} y1={from.y} x2={from.x+(to.x-from.x)*draw.fraction} y2={from.y+(to.y-from.y)*draw.fraction} style={draw.fraction>0&&draw.fraction<1?{stroke:'#ffd085',opacity:1,strokeWidth:2}:undefined}/></g>})}</g>
   {tetrahedronPositions&&<g data-triple-tetrahedron="" data-shared-centre={observerZero}><g data-visible-layer="mapping" style={{visibility:shown.mapping?undefined:'hidden'}}>{[0,1,2].map(layer=><path key={layer} data-tetrahedron-layer={layer} d={tetrahedron.path} transform="scale(12)" fill="none" stroke={["#7ddbd0","#e2b46d","#ac94ee"][layer]} strokeWidth="1" vectorEffect="non-scaling-stroke" strokeDasharray={layer===0?undefined:layer===1?"9 6":"2 8"}/>)}</g><g style={{visibility:shown.nodes?undefined:'hidden'}} data-is-position="tip" data-is-address={observerZero} transform={'translate('+tetrahedron.points[3]!.x*12+' '+tetrahedron.points[3]!.y*12+')'} role="button" tabIndex={0} aria-label={'Select IS NEXT tip at '+observerZero} onClick={()=>onSelect(observerZero)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(observerZero)}}}><circle r="28" fill="#183c45" stroke="#b8e6dd"/><text style={{visibility:shown.labels?undefined:'hidden'}} y="5" textAnchor="middle" fill="#e5fff9">IS NEXT</text></g></g>}
   {tetrahedronPositions&&retrospective&&<g data-retrospective-projection="illustrative" data-visible-layer="paths" style={{visibility:shown.paths?undefined:'hidden'}} data-source-address={observerZero}>{['DID','COULD HAVE','WOULD HAVE'].map((role,index)=>{const tip=tetrahedron.points[3]!,x=tip.x*12,y=tip.y*12,bend=(index-1)*100,active=retrospective.selected===role,colour=['#9fe0d3','#e2b46d','#ac94ee'][index];return <g key={role} data-retrospective-path={role} onClick={event=>{event.stopPropagation();retrospective.onSelect(role)}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();retrospective.onSelect(role)}}}><path d={'M0 0 Q'+(x/2+bend)+' '+(y/2-bend)+' '+x+' '+y} fill="none" stroke={colour} opacity={active?1:.7} strokeWidth={active?5:3} strokeDasharray={index===0?undefined:index===1?'12 8':'3 7'} vectorEffect="non-scaling-stroke"/><g role="button" tabIndex={0} aria-label={'Illustrate '+role} aria-pressed={active} transform={'translate('+(x*(index+1)/4)+' '+(y*(index+1)/4-12)+')'}><rect style={{visibility:shown.labels?undefined:'hidden'}} x={index===0?-50:-112} y="-34" width={index===0?100:224} height="46" rx="8" fill="#102832" fillOpacity={active?.9:.55} stroke={active?colour:undefined}/><text textAnchor="middle" fill={colour} style={{fontSize:32,visibility:shown.labels?undefined:'hidden'}} opacity={active?1:.65}>{role}</text></g></g>})}</g>}
   <g data-visible-layer="nodes" style={{visibility:shown.nodes?undefined:'hidden'}}>{field.nodes.map(node=>{const draw=drawnNodes.get(node.address)!,shape=worldObjects.get(node.address)!,sprite=raster.sprites.get(node.address);return <g opacity={draw.visible?(draw.unreached?.25:1):0} style={{pointerEvents:draw.visible?undefined:'none'}} aria-hidden={!draw.visible} data-draw-stage={draw.stage??undefined} data-field-node={node.address} data-render-revision={node.revision} data-render-source={node.sourceId} key={node.address} transform={`translate(${node.x} ${node.y})`} role="button" aria-label={`Select ${node.address}`} aria-pressed={node.address===address} aria-disabled={disabled} tabIndex={disabled||!draw.visible?-1:0} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}if(!disabled)onReaddress?.(node.address)}} onDoubleClick={event=>{event.stopPropagation();if(!disabled&&!suppressClick.current)onSelect(node.address)}} onKeyDown={event=>{if(!disabled&&(event.key==='Enter'||event.key===' ')){event.preventDefault();if(node.address===address)onSelect(node.address);else onReaddress?.(node.address)}}} className={(node.address===address?'ei-array-node selected':'ei-array-node')+(relationNode?.(node.address)?' ei-relation-node':'')}><title>{`${node.address} · ${node.role} revision ${node.revision} · Double-click or press Enter when selected to open`}</title><circle r="72" fill="none" stroke="none" pointerEvents="all"/>{sprite&&<image key={sprite.key} data-modeler-image="" href={sprite.href} x={sprite.x} y={sprite.y} width={sprite.width} height={sprite.height} onLoad={()=>raster.onLoad(sprite.key,sprite.href)} onError={()=>raster.onError(sprite.key,sprite.href)}/>}<path data-world-outline="" d={shape.path} fill="none" stroke="none" opacity={relationNode?.(node.address)?1:0}/>{node.address===address&&<g role="button" aria-label={`Choose ${node.address} IS as ZERO`} onPointerDown={event=>startPlant(event,node.address)} onDoubleClick={event=>event.stopPropagation()} tabIndex={disabled||!draw.visible?-1:0} aria-disabled={disabled||!draw.visible} onClick={event=>{event.stopPropagation();if(!disabled&&draw.visible&&!suppressClick.current)chooseZero()}} onKeyDown={event=>{if(!disabled&&draw.visible&&(event.key==='Enter'||event.key===' ')){event.preventDefault();event.stopPropagation();chooseZero()}}}><circle cx="0" cy="18" r="13" fill="#efd67b"/><text x="0" y="22" textAnchor="middle">0</text></g>}<text style={{visibility:shown.labels?undefined:'hidden'}} y="46" textAnchor="middle">{nodeLabel?nodeLabel(node.address):node.address===sourceAddress?(rootLabel??EI_HOME_VIEW.name):node.value.split('\n')[0].slice(0,32)}</text></g>})}</g>
   {recursiveProjection.filter(frame=>frame.depth>0).map(frame=><g key={frame.address} data-recursive-frame={frame.address} data-parent-centre={frame.parent} data-recursive-depth={frame.depth} transform={'translate('+frame.x+' '+frame.y+') scale('+frame.scale+')'}><g data-visible-layer="mapping" style={{visibility:shown.mapping?undefined:'hidden'}}>{[0,1,2].map(layer=><path key={layer} d={tetrahedron.path} transform="scale(12)" fill="none" stroke={['#7ddbd0','#e2b46d','#ac94ee'][layer]} strokeWidth="1" vectorEffect="non-scaling-stroke" opacity=".65" strokeDasharray={layer===0?undefined:layer===1?'9 6':'2 8'}/>)}</g><circle style={{visibility:shown.nodes?undefined:'hidden'}} r="22" fill="#183c45" stroke="#9fe0d3" role="button" tabIndex={0} aria-label={'Enter recursive field '+frame.address} onClick={event=>{event.stopPropagation();onSelectFrame?.(frame.address)}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();onSelectFrame?.(frame.address)}}}/></g>)}
   </g>
   {plantPoint&&<g data-zero-drag="" pointerEvents="none"><circle cx={plantPoint.x} cy={plantPoint.y} r={14/camera.zoom} fill="#efd67b"/><text x={plantPoint.x} y={plantPoint.y+4/camera.zoom} fontSize={12/camera.zoom} textAnchor="middle">0</text></g>}
  </svg>
  </div>
  <div ref={workspace} tabIndex={-1} role="region" aria-label={`Field workspace ${address}`} className="ei-field-workspace" hidden={!workspaceOpen} data-field-address={address} data-field-revision={revision??selected?.revision}><header><strong>{address===sourceAddress?`${EI_HOME_VIEW.name} · ${address}`:address}</strong><button disabled={disabled} onClick={chooseZero}>Choose IS as ZERO</button><button disabled={disabled} onClick={onCloseWorkspace}>Return to field</button></header><details><summary>Selected state and retained thread sources</summary><p>Object texture grain {raster.grain} × {raster.grain}; {raster.ready?'returned':'constructing'}</p>{raster.error&&<p role="alert">{raster.error}</p>}<small>{field.nodes.length} shown / {wholeField.nodes.length} retained addresses · {field.edges.length} shown threads · revision {ledger.revision}</small><details><summary>WAS · IS · NEXT</summary><p>Fit improvement: {improvement.status}</p><p>Observed comparisons: {drawing.idleObservation.observations} · unchanged {drawing.idleObservation.unchanged} · differences {drawing.idleObservation.differences}</p><p>WAS {drawing.cycle.WAS?.frameKey??'unpresented'}</p><p>IS {drawing.cycle.IS?.frameKey??'unpresented'}</p><p>NEXT {drawing.cycle.NEXT?.frameKey??'none'}</p>{drawing.cycle.openReasons.map(reason=><p key={reason}>{reason}</p>)}</details><p>Drawing follows retained threads from {address}; playback does not change the ledger. {drawPlan.unreachableAddresses.length} addresses are outside this directed traversal.</p><button onClick={drawing.step}>Draw next thread wave</button>  <div className="ei-field-tools-details"><button onClick={()=>zoom(1.6)} aria-label="Zoom field in" title="Zoom field in">+</button><button onClick={()=>zoom(1/1.6)} aria-label="Zoom field out" title="Zoom field out">−</button><button disabled={!drawing.complete||!!improvement.pending} onClick={()=>{if(orientation.roll!==0){setOrientation(current=>({...current,roll:0}));setView(fit)}else improvement.improve()}} aria-label="Fit field" title="Fit field">⊙</button><button disabled={!selected} onClick={()=>selected&&setView({x:selected.x,y:selected.y,zoom:3})} aria-label="Fit selected" title="Fit selected">◎</button><button aria-label={drawing.playing?'Idle addressed drawing':'Run addressed drawing'} title={drawing.playing?'Idle addressed drawing':'Run addressed drawing'} onClick={drawing.playing?drawing.idle:drawing.play}>{drawing.playing?'Ⅱ':'▷'}</button><button aria-label="Complete thread drawing" title="Complete thread drawing" onClick={drawing.finish}>▸│</button><button aria-label="Inspect 3D view" title="Drag to pan; right-drag or Shift-drag to turn; wheel to zoom; Alt-wheel chooses ZERO" aria-pressed={orbiting} onClick={()=>setOrbiting(value=>!value)}>◇</button><button aria-label="Find address" title="Find address" aria-expanded={finding} onClick={()=>{setFinding(true);onCloseWorkspace?.()}}>⌕</button></div>
<nav aria-label="Field view movement"><button aria-label="Pan field left" onClick={()=>setView({...camera,x:camera.x-240/camera.zoom})}>←</button><button aria-label="Pan field right" onClick={()=>setView({...camera,x:camera.x+240/camera.zoom})}>→</button><button aria-label="Pan field up" onClick={()=>setView({...camera,y:camera.y-160/camera.zoom})}>↑</button><button aria-label="Pan field down" onClick={()=>setView({...camera,y:camera.y+160/camera.zoom})}>↓</button></nav>{selected&&<><strong>{selected.address} · {selected.role} revision {selected.revision}</strong><p>Source {selected.sourceId}</p><pre>{selected.value}</pre></>}<p>Screen positions follow retained relation distance from each connected source. They are view coordinates; model placement and geometric motion are unbound.</p>{field.edges.filter(edge=>edge.from===address||edge.to===address).map(edge=><p key={edge.id}>{edge.from} → {edge.label} → {edge.to}{!edge.known?' · endpoint unbound':''} · {edge.sourceId} · revision {edge.sourceRevision}</p>)}</details>{children}</div>
 </section>
}




