import {createEIPinch,panEIObserver} from './model/ei-pinch'
import {useEIModelerObjects} from './useEIModelerObjects'
import type {EIFieldPresentationSnapshot} from './model/ei-field-save'
import {useEIFitImprovement} from './useEIFitImprovement'
import {EIFieldAction} from './EIFieldAction'
import {projectEIWorldObject} from './model/ei-world-object'
import {deriveEIFieldObject,projectEIFieldTetrahedron} from './model/ei-field-object'
import {resolveEIObserverZero} from './model/ei-observer-zero'
import {EI_FIELD_NODE_PATH,createEISvgSceneGeometry} from './model/ei-svg-frame-witness'
import {createEIThreadDrawPlan} from './model/ei-thread-draw'
import {projectEIThreadDrawFrame} from './model/ei-thread-draw-frame'
import {useEIThreadDrawing} from './useEIThreadDrawing'
import {useMemo,useState,useEffect,useLayoutEffect,useRef,type ReactNode} from 'react'
import type {EILedger} from './model/ei-engine'
import type {EIGrain} from './model/ei-grain-identity'
import {projectEIFieldArray,clampEIFieldZoom} from './model/ei-field-array-view'
export function EIFieldArray({ledger,address,revision,grain,disabled,onSelect,contextLabel,sourceAddress,children,workspaceOpen=false,onCloseWorkspace,onReaddress,onChooseZero,initialDrawPhase=0,initialObserverZero,initialZeroHistory=[],initialPresentation,onSnapshot}:{ledger:EILedger;address:string;revision:number|null;grain:EIGrain;disabled:boolean;onSelect:(address:string)=>void;contextLabel?:string;sourceAddress:string;children?:ReactNode;workspaceOpen?:boolean;onCloseWorkspace?:()=>void;onReaddress?:(address:string)=>void;onChooseZero?:(address:string)=>void;initialDrawPhase?:number;initialObserverZero?:string;initialZeroHistory?:readonly string[];initialPresentation?:EIFieldPresentationSnapshot|null;onSnapshot?:(read:()=>EIFieldPresentationSnapshot)=>void}){
 const [observerZero,setObserverZero]=useState(initialPresentation?.observerZero??initialObserverZero??sourceAddress),[zeroChosen,setZeroChosen]=useState(true),[zeroHistory,setZeroHistory]=useState<string[]>([...new Set([sourceAddress,...(initialPresentation?.zeroHistory??initialZeroHistory),initialPresentation?.observerZero??initialObserverZero??sourceAddress])])
 const [gestureActive,setGestureActive]=useState(false)
 const [zeroFocusRequest,setZeroFocusRequest]=useState(0),fittedZeroRequest=useRef(0)
 const [orientation,setOrientation]=useState({roll:0,...(initialPresentation?.orientation??{yaw:.46,pitch:.18})}),[orbiting,setOrbiting]=useState(false)

 const object=useMemo(()=>deriveEIFieldObject(ledger,observerZero,grain),[ledger,observerZero,grain])
 const wholeField=useMemo(()=>projectEIFieldArray(ledger,grain,revision===null?undefined:{address,revision},observerZero),[ledger,grain,address,revision,observerZero])
 const field=useMemo(()=>{if(!zeroChosen)return wholeField;const parts=new Set([observerZero,...object.partAddresses,...zeroHistory]);const nodes=wholeField.nodes.filter(node=>parts.has(node.address));const edges=wholeField.edges.filter(edge=>parts.has(edge.from)&&parts.has(edge.to));const xs=nodes.map(node=>node.x),ys=nodes.map(node=>node.y);return {...wholeField,nodes,edges,bounds:{left:Math.min(...xs)-110,right:Math.max(...xs)+110,top:Math.min(...ys)-150,bottom:Math.max(...ys)+90}}},[wholeField,zeroChosen,observerZero,object,zeroHistory])
 const drawPlan=useMemo(()=>createEIThreadDrawPlan(field.nodes,field.edges,observerZero),[field,observerZero])
 const [view,setView]=useState<{x:number;y:number;zoom:number}|null>(initialPresentation?.view??null),[search,setSearch]=useState(''),[finding,setFinding]=useState(false),[size,setSize]=useState({width:1200,height:800})
 const fieldSvg=useRef<SVGSVGElement>(null),surface=useRef<HTMLElement>(null),workspace=useRef<HTMLDivElement>(null),wasOpen=useRef(false)
 useEffect(()=>{if(workspaceOpen){workspace.current?.focus();workspace.current?.scrollIntoView({block:'start'})}else if(wasOpen.current){const selected=surface.current?.querySelector<SVGGElement>('[aria-pressed="true"]');selected?.focus();selected?.scrollIntoView({block:'center'})}wasOpen.current=workspaceOpen},[workspaceOpen])
 useEffect(()=>{if(finding&&!workspaceOpen)surface.current?.querySelector<HTMLInputElement>('.ei-field-find input')?.focus()},[finding,workspaceOpen])
 const readdress=(target:EventTarget|null)=>{if(disabled||!onReaddress||!(target instanceof Element))return;const at=target.closest('[data-field-node]')?.getAttribute('data-field-node'),node=field.nodes.find(item=>item.address===at);if(node){const next=resolveEIObserverZero(ledger,node.address,grain);setObserverZero(next.address);setZeroHistory(history=>history.includes(next.address)?history:[...history,next.address]);setZeroChosen(true);setZeroFocusRequest(value=>value+1);onChooseZero?.(next.address)}}
 const pointer=useRef<{x:number;y:number;startX:number;startY:number}|null>(null),suppressClick=useRef(false),pinch=useRef(createEIPinch())
 useEffect(()=>{const svg=fieldSvg.current;if(!svg||typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(entries=>{const box=entries[0]?.contentRect;if(box?.width&&box.height)setSize({width:box.width,height:box.height})});observer.observe(svg);return()=>observer.disconnect()},[])
 const {width,height}=size,b=field.bounds
 const fit={x:(b.left+b.right)/2,y:(b.top+b.bottom)/2,zoom:Math.min(width/(b.right-b.left),height/(b.bottom-b.top))}
 const camera=view??fit,byAddress=new Map(field.nodes.map(node=>[node.address,node])),selected=byAddress.get(address)
 const gestureCamera=useRef({...camera,roll:orientation.roll});gestureCamera.current={...camera,roll:orientation.roll}
 const contained=useMemo(()=>{const index=new Map(ledger.records.map(record=>[record.address,new Set<string>()]));for(const record of ledger.records){for(const parent of record.parents)index.get(parent)?.add(record.address);for(const relation of record.relations)if(relation.relation==='CONTAINS'&&index.has(relation.address))index.get(record.address)!.add(relation.address)}return index},[ledger])
 const entities=useMemo(()=>field.nodes.map(node=>({...node,partCount:contained.get(node.address)?.size??0,root:node.address===observerZero})),[field,contained,observerZero])
 const worldObjects=useMemo(()=>new Map(entities.map(node=>[node.address,projectEIWorldObject(node,orientation.yaw,orientation.pitch)])),[entities,orientation])
 const raster=useEIModelerObjects(entities,orientation)
 const viewBox=`${camera.x-width/(2*camera.zoom)} ${camera.y-height/(2*camera.zoom)} ${width/camera.zoom} ${height/camera.zoom}`
 const sceneTransform=`rotate(${orientation.roll*180/Math.PI} ${camera.x} ${camera.y})`
 const geometry=useMemo(()=>createEISvgSceneGeometry(Object.fromEntries([...worldObjects].map(([id,shape])=>[id,{path:shape.path,faces:[],...(raster.sprites.has(id)?{image:{href:raster.sprites.get(id)!.href,x:raster.sprites.get(id)!.x,y:raster.sprites.get(id)!.y,width:raster.sprites.get(id)!.width,height:raster.sprites.get(id)!.height}}:{})}])),viewBox,sceneTransform),[worldObjects,viewBox,sceneTransform,raster.sprites])
 const drawing=useEIThreadDrawing(drawPlan,field,fieldSvg,initialDrawPhase,geometry,initialPresentation?.animation,initialPresentation?.idle,raster.ready&&!gestureActive),drawFrame=projectEIThreadDrawFrame(drawPlan,drawing.phase,drawing.retained)
 const drawnNodes=new Map(drawFrame.nodes.map(node=>[node.address,node])),drawnEdges=new Map(drawFrame.edges.map(edge=>[edge.id,edge]))
 const fitEvidence=useMemo(()=>({sourceSnapshot:JSON.stringify([observerZero,ledger.revision,grain]),viewport:{width,height},view:camera,objects:field.nodes.map(node=>{const shape=worldObjects.get(node.address)!;return {address:node.address,revision:node.revision,sourceId:node.sourceId,bounds:{left:node.x+shape.bounds.left,right:node.x+shape.bounds.right,top:node.y+shape.bounds.top,bottom:node.y+shape.bounds.bottom}}})}),[observerZero,ledger.revision,grain,width,height,camera,field,worldObjects])
 const improvement=useEIFitImprovement(fitEvidence,fieldSvg,setView)
 useEffect(()=>{if(initialPresentation)improvement.restore(initialPresentation.improvement)},[])
 useEffect(()=>{onSnapshot?.(()=>({schema:'ei.field-presentation.v1',canonicalRoot:sourceAddress,observerZero,zeroHistory,selectedAddress:address,selectedRevision:revision??ledger.records.find(record=>record.address===address)!.is.revision,grain,view:camera,orientation,animation:drawing.save(),idle:drawing.getIdle(),improvement:improvement.save()}))},[onSnapshot,sourceAddress,observerZero,zeroHistory,address,grain,camera,orientation,drawing.cycle,improvement.state])
 const chooseZero=()=>{const next=resolveEIObserverZero(ledger,address,grain);setObserverZero(next.address);setZeroHistory(history=>history.includes(next.address)?history:[...history,next.address]);setZeroChosen(true);setZeroFocusRequest(value=>value+1);onChooseZero?.(next.address);onCloseWorkspace?.()}
 useLayoutEffect(()=>{if(!zeroChosen||fittedZeroRequest.current===zeroFocusRequest)return;fittedZeroRequest.current=zeroFocusRequest;const incident=new Set([observerZero,...object.partAddresses]);const local=field.nodes.filter(node=>incident.has(node.address)),xs=local.map(node=>node.x),ys=local.map(node=>node.y);const left=Math.min(...xs)-80,right=Math.max(...xs)+80,top=Math.min(...ys)-80,bottom=Math.max(...ys)+80;setView({x:(left+right)/2,y:(top+bottom)/2,zoom:Math.min(width/(right-left),height/(bottom-top),8)})},[observerZero,zeroChosen,zeroFocusRequest,field,width,height,object])
 const matches=wholeField.nodes.filter(node=>node.address.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
 useEffect(()=>{const svg=fieldSvg.current;if(!svg)return;const wheel=(event:WheelEvent)=>{if(event.ctrlKey)return;event.preventDefault();readdress(event.target)};svg.addEventListener('wheel',wheel,{passive:false});return()=>svg.removeEventListener('wheel',wheel)},[disabled,onReaddress,field,width,height])
 const zoom=(factor:number)=>setView({...camera,zoom:clampEIFieldZoom(camera.zoom*factor,Math.min(.08,fit.zoom/10))})
 return <section ref={surface} className="ei-field-array" aria-label="Addressed field array" data-retained-addresses={wholeField.nodes.length}>
  <div className="ei-field-visual" inert={workspaceOpen?true:undefined} aria-hidden={workspaceOpen}>
  <div className="ei-field-hud"><button className="ei-field-address" disabled={disabled} onClick={()=>onSelect(address)} aria-label={`Open selected address ${address}`}><strong>{address.split('/').at(-1)}</strong><small>{grain} · {revision??selected?.revision}</small></button><span className="ei-field-scope" title={contextLabel??'Addressed field'}>{contextLabel?'Public source':''}</span></div>
  <div className="ei-world-dock"><EIFieldAction address={observerZero} revision={drawing.cycle.source.revision} sourceId={drawing.cycle.source.sourceId} operation={drawing.complete?'replay-source-frames':drawing.playing?'idle-render-observation':'next-render-frame'} label={drawing.complete?'Replay retained source frames':drawing.playing?'Idle and observe':'Resolve next addressed frame'} hint={drawing.complete?'Replay':drawing.playing?'Observe':'NEXT'} form={{kind:'transition',before:{id:drawing.cycle.IS?.frameKey??'unpresented',label:'IS',address:observerZero,revision:drawing.cycle.source.revision,value:drawing.cycle.IS?String(drawing.cycle.IS.sequence):undefined},...(drawing.cycle.NEXT?{proposed:{id:drawing.cycle.NEXT.frameKey,label:'NEXT',address:observerZero,revision:drawing.cycle.source.revision,value:String(drawing.cycle.NEXT.sequence)}}:{}),...(drawing.cycle.IS?{returned:{id:drawing.cycle.IS.frameKey,label:'Returned',address:observerZero,revision:drawing.cycle.source.revision,value:String(drawing.cycle.IS.sequence),status:'verified-svg-readback'}}:{})}} onClick={drawing.complete?drawing.play:drawing.playing?drawing.idle:drawing.step}/></div>
  <div className="ei-field-find" hidden={!finding}><label>Find address<input value={search} onChange={event=>setSearch(event.target.value)}/></label><select aria-label="Select field address" disabled={disabled} value={matches.some(node=>node.address===address)?address:''} onChange={event=>{if(event.target.value){const node=byAddress.get(event.target.value);if(node)setView({...camera,x:node.x,y:node.y});onReaddress?.(event.target.value);setFinding(false);surface.current?.querySelector<HTMLButtonElement>('.ei-field-address')?.focus()}}}><option value="">{matches.length}</option>{matches.map(node=><option key={node.address} value={node.address}>{node.address}</option>)}</select></div>
  <svg ref={fieldSvg} className="ei-field-surface" viewBox={viewBox} role="group" aria-label="Selectable addressed field" data-field-source-snapshot={fitEvidence.sourceSnapshot} data-observer-zero={observerZero} data-drawing-complete={drawing.complete} data-render-frame={drawing.frame?.frameKey} data-render-generation={drawing.frame?.generation} data-render-sequence={drawing.frame?.sequence} onClickCapture={event=>{if(suppressClick.current){event.preventDefault();event.stopPropagation()}}}
 onPointerDown={event=>{if(disabled)return;setGestureActive(true);const fresh=pinch.current.count===0;if(fresh){suppressClick.current=false;pointer.current={x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY}}const rect=event.currentTarget.getBoundingClientRect();if(pinch.current.down(event.pointerId,{x:event.clientX,y:event.clientY},gestureCamera.current,{left:rect.left,top:rect.top,width:rect.width,height:rect.height,logicalWidth:width,logicalHeight:height})){suppressClick.current=true;pointer.current=null}if(pinch.current.active)event.currentTarget.setPointerCapture(event.pointerId);else (event.target as Element).setPointerCapture(event.pointerId)}}
 onPointerMove={event=>{if(disabled)return;const rect=event.currentTarget.getBoundingClientRect(),viewport={left:rect.left,top:rect.top,width:rect.width,height:rect.height,logicalWidth:width,logicalHeight:height};if(!pinch.current.has(event.pointerId))return;const next=pinch.current.move(event.pointerId,{x:event.clientX,y:event.clientY},gestureCamera.current,viewport,Math.min(.08,fit.zoom/10));if(next){gestureCamera.current={...next,roll:next.roll??orientation.roll};setView({x:next.x,y:next.y,zoom:next.zoom});setOrientation(current=>({...current,roll:next.roll??current.roll}));suppressClick.current=true;event.preventDefault();return}if(pinch.current.active||!pointer.current)return;const previous=pointer.current;if(!suppressClick.current&&Math.hypot(event.clientX-previous.startX,event.clientY-previous.startY)<5)return;if(orbiting)setOrientation(current=>({...current,yaw:current.yaw+(event.clientX-previous.x)/160,pitch:Math.max(-1.5,Math.min(1.5,current.pitch+(event.clientY-previous.y)/160))}));else {const p=panEIObserver(gestureCamera.current,previous,{x:event.clientX,y:event.clientY},viewport);gestureCamera.current={...p,roll:p.roll??orientation.roll};setView({x:p.x,y:p.y,zoom:p.zoom})}pointer.current={...previous,x:event.clientX,y:event.clientY};suppressClick.current=true;event.currentTarget.setPointerCapture(event.pointerId);event.preventDefault()}}
 onPointerUp={event=>{if(!pinch.current.has(event.pointerId))return;if(pinch.current.end(event.pointerId))suppressClick.current=true;setGestureActive(pinch.current.count>0);const remaining=pinch.current.remaining;pointer.current=remaining?{...remaining,startX:remaining.x,startY:remaining.y}:null;if(suppressClick.current)event.preventDefault()}}
 onPointerCancel={event=>{if(!pinch.current.has(event.pointerId))return;pinch.current.end(event.pointerId);setGestureActive(pinch.current.count>0);pointer.current=null;suppressClick.current=true}}
 onLostPointerCapture={event=>{if(event.target!==event.currentTarget||event.currentTarget.hasPointerCapture(event.pointerId))return;if(pinch.current.has(event.pointerId)){pinch.current.end(event.pointerId);setGestureActive(pinch.current.count>0);pointer.current=null;suppressClick.current=true}}}>
   <g data-observer-scene="" transform={sceneTransform}>
   {field.edges.filter(edge=>edge.known).map(edge=>{const draw=drawnEdges.get(edge.id)!,from=byAddress.get(draw.drawFrom)!,to=byAddress.get(draw.drawTo)!,active=edge.from===address||edge.to===address;const prior=draw.retained||(drawFrame.complete&&draw.status==='unreachable');return <g key={edge.id} className={active?'ei-thread active':'ei-thread'} opacity={draw.visible?1:0} data-thread-id={edge.id} data-draw-stage={draw.stage??undefined}><title>{`${edge.from} → ${edge.label} → ${edge.to}`}</title>{prior&&<line x1={from.x} y1={from.y} x2={to.x} y2={to.y} style={{opacity:draw.status==='unreachable'?.06:.16}}/>}<line x1={from.x} y1={from.y} x2={from.x+(to.x-from.x)*draw.fraction} y2={from.y+(to.y-from.y)*draw.fraction} style={draw.fraction>0&&draw.fraction<1?{stroke:'#ffd085',opacity:1,strokeWidth:2}:undefined}/></g>})}
   {field.nodes.map(node=>{const draw=drawnNodes.get(node.address)!,shape=worldObjects.get(node.address)!,sprite=raster.sprites.get(node.address);return <g opacity={draw.visible?(draw.unreached?.25:1):0} style={{pointerEvents:draw.visible?undefined:'none'}} aria-hidden={!draw.visible} data-draw-stage={draw.stage??undefined} data-field-node={node.address} data-render-revision={node.revision} data-render-source={node.sourceId} key={node.address} transform={`translate(${node.x} ${node.y})`} role="button" aria-label={`Select ${node.address}`} aria-pressed={node.address===address} aria-disabled={disabled} tabIndex={disabled||!draw.visible?-1:0} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}if(!disabled)onReaddress?.(node.address)}} onKeyDown={event=>{if(!disabled&&(event.key==='Enter'||event.key===' ')){event.preventDefault();onReaddress?.(node.address)}}} className={node.address===address?'ei-array-node selected':'ei-array-node'}><title>{`${node.address} · ${node.role} revision ${node.revision}`}</title><circle r="72" fill="none" stroke="none" pointerEvents="all"/>{sprite&&<image data-modeler-image="" href={sprite.href} x={sprite.x} y={sprite.y} width={sprite.width} height={sprite.height} onLoad={()=>raster.onLoad(sprite.key,sprite.href)} onError={()=>raster.onError(sprite.key,sprite.href)}/>}<path data-world-outline="" d={shape.path} fill="none" stroke="none" opacity="0"/>{node.address===address&&<g role="button" aria-label={`Choose ${node.address} IS as ZERO`} tabIndex={disabled||!draw.visible?-1:0} aria-disabled={disabled||!draw.visible} onClick={event=>{event.stopPropagation();if(!disabled&&draw.visible)chooseZero()}} onKeyDown={event=>{if(!disabled&&draw.visible&&(event.key==='Enter'||event.key===' ')){event.preventDefault();event.stopPropagation();chooseZero()}}}><circle cx="0" cy="18" r="13" fill="#efd67b"/><text x="0" y="22" textAnchor="middle">0</text></g>}<text y="46" textAnchor="middle">{node.value.split('\n')[0].slice(0,32)}</text></g>})}
   </g>
  </svg>
  </div>
  <div ref={workspace} tabIndex={-1} role="region" aria-label={`Field workspace ${address}`} className="ei-field-workspace" hidden={!workspaceOpen} data-field-address={address} data-field-revision={revision??selected?.revision}><header><strong>{address}</strong><button disabled={disabled} onClick={chooseZero}>Choose IS as ZERO</button><button disabled={disabled} onClick={onCloseWorkspace}>Return to field</button></header><details><summary>Selected state and retained thread sources</summary><p>Object texture grain {raster.grain} × {raster.grain}; {raster.ready?'returned':'constructing'}</p>{raster.error&&<p role="alert">{raster.error}</p>}<small>{field.nodes.length} shown / {wholeField.nodes.length} retained addresses · {field.edges.length} shown threads · revision {ledger.revision}</small><details><summary>WAS · IS · NEXT</summary><p>Fit improvement: {improvement.status}</p><p>Observed comparisons: {drawing.idleObservation.observations} · unchanged {drawing.idleObservation.unchanged} · differences {drawing.idleObservation.differences}</p><p>WAS {drawing.cycle.WAS?.frameKey??'unpresented'}</p><p>IS {drawing.cycle.IS?.frameKey??'unpresented'}</p><p>NEXT {drawing.cycle.NEXT?.frameKey??'none'}</p>{drawing.cycle.openReasons.map(reason=><p key={reason}>{reason}</p>)}</details><p>Drawing follows retained threads from {address}; playback does not change the ledger. {drawPlan.unreachableAddresses.length} addresses are outside this directed traversal.</p><button onClick={drawing.step}>Draw next thread wave</button>  <div className="ei-field-tools-details"><button onClick={()=>zoom(1.6)} aria-label="Zoom field in" title="Zoom field in">+</button><button onClick={()=>zoom(1/1.6)} aria-label="Zoom field out" title="Zoom field out">−</button><button disabled={!drawing.complete||!!improvement.pending} onClick={()=>{if(orientation.roll!==0){setOrientation(current=>({...current,roll:0}));setView(fit)}else improvement.improve()}} aria-label="Fit field" title="Fit field">⊙</button><button disabled={!selected} onClick={()=>selected&&setView({x:selected.x,y:selected.y,zoom:3})} aria-label="Fit selected" title="Fit selected">◎</button><button aria-label={drawing.playing?'Idle addressed drawing':'Run addressed drawing'} title={drawing.playing?'Idle addressed drawing':'Run addressed drawing'} onClick={drawing.playing?drawing.idle:drawing.play}>{drawing.playing?'Ⅱ':'▷'}</button><button aria-label="Complete thread drawing" title="Complete thread drawing" onClick={drawing.finish}>▸│</button><button aria-label="Inspect 3D view" title="Inspect 3D view" aria-pressed={orbiting} onClick={()=>setOrbiting(value=>!value)}>◇</button><button aria-label="Find address" title="Find address" aria-expanded={finding} onClick={()=>{setFinding(true);onCloseWorkspace?.()}}>⌕</button></div>
<nav aria-label="Field view movement"><button aria-label="Pan field left" onClick={()=>setView({...camera,x:camera.x-240/camera.zoom})}>←</button><button aria-label="Pan field right" onClick={()=>setView({...camera,x:camera.x+240/camera.zoom})}>→</button><button aria-label="Pan field up" onClick={()=>setView({...camera,y:camera.y-160/camera.zoom})}>↑</button><button aria-label="Pan field down" onClick={()=>setView({...camera,y:camera.y+160/camera.zoom})}>↓</button></nav>{selected&&<><strong>{selected.address} · {selected.role} revision {selected.revision}</strong><p>Source {selected.sourceId}</p><pre>{selected.value}</pre></>}<p>Screen positions follow retained relation distance from each connected source. They are view coordinates; model placement and geometric motion are unbound.</p>{field.edges.filter(edge=>edge.from===address||edge.to===address).map(edge=><p key={edge.id}>{edge.from} → {edge.label} → {edge.to}{!edge.known?' · endpoint unbound':''} · {edge.sourceId} · revision {edge.sourceRevision}</p>)}</details>{children}</div>
 </section>
}
