import {readEISeedPlantings,proposeEISeedNurture} from './model/ei-seed-planting'
import {useMemo,useState} from 'react'
import type {EILedger,EIProposal} from './model/ei-engine'
import {proposeGuideStep,proposeGuideSelection,proposeGuideOutcome,readGuideSteps,readGuideAttempts,resolveGuideIntentAddress} from './model/ei-guide-steps'
import {proposeGuideObservation} from './model/ei-guide-context'
export function EIGuidance({ledger,address,disabled,onStage,onInspect}:{ledger:EILedger;address:string;disabled:boolean;onStage:(proposal:EIProposal)=>void;onInspect?:(address:string)=>void}){
 const intentAddress=readEISeedPlantings(ledger).find(item=>item.address===address)?.environment.address??resolveGuideIntentAddress(ledger,address),intent=ledger.records.find(record=>record.address===intentAddress)
 return intent?<GuideEditor key={JSON.stringify([intentAddress,intent.is.revision,intent.is.source.id])} ledger={ledger} address={intentAddress} disabled={disabled} onStage={onStage} onInspect={onInspect}/>:null
}
function GuideEditor({ledger,address,disabled,onStage,onInspect}:{ledger:EILedger;address:string;disabled:boolean;onStage:(proposal:EIProposal)=>void;onInspect?:(address:string)=>void}){
 const intent=ledger.records.find(record=>record.address===address)!,steps=useMemo(()=>readGuideSteps(ledger,address),[ledger,address]),attempts=useMemo(()=>readGuideAttempts(ledger,address),[ledger,address])
 const sowings=useMemo(()=>readEISeedPlantings(ledger).filter(item=>item.current&&item.environment.address===address&&item.phase==='awaiting-environment'&&!item.attemptAddress),[ledger,address])
 const [action,setAction]=useState(''),[expected,setExpected]=useState(''),[observation,setObservation]=useState(''),[conditionAddress,setConditionAddress]=useState(''),[conditionValue,setConditionValue]=useState(''),[conditions,setConditions]=useState<{address:string;equals:string}[]>([]),[actual,setActual]=useState<Record<string,string>>({}),[error,setError]=useState('')
 const stage=(make:()=>EIProposal)=>{setError('');try{onStage(make())}catch(reason){setError(String(reason))}}
 const id=()=>`guide-${crypto.randomUUID()}`
 return <section aria-label="Guide from selected source"><details><summary>Guide</summary><p>{intent.is.value}</p><small>{intent.address} · IS {intent.is.revision}</small>
 <details><summary>Add what you observed</summary><textarea aria-label="Observed context" value={observation} onChange={event=>setObservation(event.target.value)}/><button disabled={disabled||!observation.trim()} onClick={()=>stage(()=>proposeGuideObservation(ledger,{id:id(),intentAddress:address,observation}))}>Retain observation</button></details>
 <details><summary>Add a possible next step</summary><label>Action<textarea value={action} onChange={event=>setAction(event.target.value)}/></label><label>Expected observation<textarea value={expected} onChange={event=>setExpected(event.target.value)}/></label><label>Required addressed observation<select value={conditionAddress} onChange={event=>setConditionAddress(event.target.value)}><option value="">Choose address</option>{ledger.records.map(record=><option key={record.address} value={record.address}>{record.is.value.split('\n')[0].slice(0,60)} · {record.address}</option>)}</select></label><input aria-label="Required value" value={conditionValue} onChange={event=>setConditionValue(event.target.value)}/><button disabled={disabled||!conditionAddress} onClick={()=>setConditions(list=>[...list,{address:conditionAddress,equals:conditionValue}])}>Add prerequisite</button>{conditions.map((condition,index)=><p key={index}>{condition.address} = {condition.equals}<button onClick={()=>setConditions(list=>list.filter((_,i)=>i!==index))}>Remove</button></p>)}<button disabled={disabled||!action.trim()||!expected.trim()} onClick={()=>stage(()=>proposeGuideStep(ledger,{id:id(),intentAddress:address,action,expected,conditions}))}>Retain possible step</button></details>
 {steps.map(step=><article key={step.address}><strong>{step.action}</strong><p>{step.expected}</p><small>{step.status}</small>{step.reasons.map(reason=><p key={reason}>{reason}</p>)}{step.conditions.map((condition:any,index:number)=><p key={index}>{ledger.records.some(record=>record.address===condition.address)&&onInspect?<button disabled={disabled} onClick={()=>onInspect(condition.address)}>{condition.address}</button>:<span>{condition.address}</span>} · {condition.status} · {condition.equals}</p>)}<button disabled={disabled||step.status!=='available'} onClick={()=>stage(()=>proposeGuideSelection(ledger,{id:id(),stepAddress:step.address}))}>Choose this step</button></article>)}
 {sowings.map(sow=><article key={sow.address} data-waiting-sow={sow.address}><strong>{sow.seed.value}</strong><small>{sow.environmentStatus}</small><button disabled={disabled||sow.environmentStatus!=='available'} onClick={()=>stage(()=>proposeEISeedNurture(ledger,{id:id(),sowingAddress:sow.address}))}>Continue this seed</button></article>)}
 {attempts.map(attempt=><article key={attempt.address}><strong>{attempt.action}</strong><p>Expected: {attempt.expected}</p><small>Goal revision {attempt.intent.revision} · context {attempt.contextStatus}</small>{attempt.contextStatus!=='current'&&<p>{attempt.intent.value}</p>}<label>What happened<textarea value={actual[attempt.address]??''} onChange={event=>setActual(values=>({...values,[attempt.address]:event.target.value}))}/></label><button disabled={disabled||!actual[attempt.address]?.trim()} onClick={()=>stage(()=>proposeGuideOutcome(ledger,{id:id(),attemptAddress:attempt.address,actual:actual[attempt.address]}))}>Retain reported outcome</button>{attempt.outcomes.map(outcome=><div key={outcome.address}><p>{outcome.actual}</p><small>{outcome.comparison} · reported observation</small></div>)}</article>)}
 {error&&<p role="alert">{error}</p>}</details></section>
}
