import {useRef,useState} from 'react'
import {EIFieldAction} from './EIFieldAction'
import {requestEIPhoneOverlay,type EIOverlayOperation} from './model/ei-phone-overlay'
import {phoneReturnMatches,type PhoneScope} from './model/ei-phone-return'
export function EIPhoneOverlay({address,revision,disabled}:{address:string;revision:number;disabled:boolean}){
 const [result,setResult]=useState<Awaited<ReturnType<typeof requestEIPhoneOverlay>>|null>(null),[error,setError]=useState(''),[busyAction,setBusyAction]=useState<{op:EIOverlayOperation;scope:PhoneScope}|null>(null);const pending=useRef(false),busy=busyAction!==null
 const supported=typeof window!=='undefined'&&window.location.origin==='https://appassets.androidplatform.net'
 const act=async(op:EIOverlayOperation)=>{if(pending.current||!supported)return;pending.current=true;setBusyAction({op,scope:{address,revision}});setError('');try{setResult(await requestEIPhoneOverlay({address,revision},window.location.origin,crypto.randomUUID(),op))}catch(reason){setError(`${address} · revision ${revision}: ${reason instanceof Error?reason.message:String(reason)}`)}finally{pending.current=false;setBusyAction(null)}}
 if(!supported)return null
 const control=(op:EIOverlayOperation,label:string,hint:string)=>{
  const returned=result?.op===op&&phoneReturnMatches(result.scope,{address,revision})?result:null
  return <EIFieldAction key={op} address={address} revision={revision} operation={`phone.overlay.${op}`} label={label} hint={hint} disabled={op==='hide'?busy:disabled||busy} pending={busyAction?.op===op&&phoneReturnMatches(busyAction.scope,{address,revision})} presented={!!returned} onClick={()=>act(op)} form={{kind:'source-return',source:{id:address,label:'Field',address,revision},destination:{id:`native:overlay:${op}`,label:op==='request-permission'?'Settings':'Window'},...(returned?{returned:{id:returned.requestId,label:returned.value.lastAction?.state??returned.value.mode,address:returned.scope.address,revision:returned.scope.revision,status:returned.value.lastAction?.state??returned.value.mode,value:JSON.stringify(returned.value)}}:{})}}/>
 }
 return <section aria-label="Overlay at selected field address"><details><summary>Overlay · {address}</summary><p>Passive passes touches to the app underneath. Interactive gives this field the full-screen touches. Android settings grants access; opening settings does not start the overlay.</p>{control('status','Read overlay state','Read')}{control('request-permission','Open Android overlay settings','Settings')}{control('show-passive','Show passive field','Passive')}{control('interact','Interact with field','Interact')}{control('hide','Return field to app','Return')}{error&&<p role="alert">{error}</p>}{result&&<><p>{result.scope.address} · revision {result.scope.revision}{phoneReturnMatches(result.scope,{address,revision})?'':' · previous selection'} · {result.value.mode}</p>{result.value.lastAction&&<p>{result.value.lastAction.address} · revision {result.value.lastAction.revision} · {result.value.lastAction.op} · {result.value.lastAction.state}</p>}<details><summary>Returned window state</summary><pre>{JSON.stringify(result.value,null,2)}</pre></details></>}</details></section>
}
