import {useRef,useState} from 'react'
import {EIFieldAction} from './EIFieldAction'
import {phoneReturnMatches,type PhoneScope} from './model/ei-phone-return'
import {readEIPhoneInputs,phoneInputAdmissionError,acknowledgeEIPhoneInput,discardEIPhoneInput,type EIPhoneInput} from './model/ei-phone-input'
export function EIPhoneInputControl({address,revision,sourceId,disabled,onChoose,used,retained}:{address:string;revision:number;sourceId?:string;disabled:boolean;used:readonly string[];retained:readonly {id:string;utf8Sha256:string;receiptId:string}[];onChoose:(input:EIPhoneInput)=>void}){
 const [inputs,setInputs]=useState<readonly EIPhoneInput[]>([]),[rejections,setRejections]=useState<readonly string[]>([]),[ack,setAck]=useState(''),[error,setError]=useState(''),[busyAction,setBusyAction]=useState<{operation:string;scope:PhoneScope}|null>(null),[readback,setReadback]=useState<{scope:PhoneScope;requestId:string;value:Awaited<ReturnType<typeof readEIPhoneInputs>>}|null>(null),[queueReturn,setQueueReturn]=useState<{scope:PhoneScope;operation:string;requestId:string;status:string;inputId:string}|null>(null);const pending=useRef(false),busy=busyAction!==null
 const supported=typeof window!=='undefined'&&window.location.origin==='https://appassets.androidplatform.net'
 const read=async()=>{if(pending.current||!supported)return;const scope={address,revision},requestId=crypto.randomUUID();pending.current=true;setBusyAction({operation:'phone.input.read',scope});setError('');try{const returned=await readEIPhoneInputs(window.location.origin,requestId);setInputs(returned.inputs);setRejections(returned.rejections);setReadback({scope,requestId,value:returned})}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{pending.current=false;setBusyAction(null)}}
 const release=async(input:typeof retained[number])=>{if(pending.current||!supported)return;const scope={address,revision},operation=`phone.input.release:${input.id}`,requestId=crypto.randomUUID();pending.current=true;setBusyAction({operation,scope});setError('');try{const returned=await acknowledgeEIPhoneInput(window.location.origin,requestId,input);setAck(`${input.id} · ${returned.status}`);setQueueReturn({scope,operation,requestId,status:returned.status,inputId:input.id})}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{pending.current=false;setBusyAction(null)}}
 const discard=async(input:EIPhoneInput)=>{if(pending.current||!supported)return;const scope={address,revision},operation=`phone.input.discard:${input.id}`,requestId=crypto.randomUUID();pending.current=true;setBusyAction({operation,scope});setError('');try{const returned=await discardEIPhoneInput(window.location.origin,requestId,input);setAck(`${input.id} · ${returned.status} from phone queue`);setQueueReturn({scope,operation,requestId,status:returned.status,inputId:input.id});if(returned.status==='discarded'||returned.status==='already-discarded')setInputs(current=>current.filter(item=>item.id!==input.id))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{pending.current=false;setBusyAction(null)}}
 const isPending=(operation:string)=>busyAction?.operation===operation&&phoneReturnMatches(busyAction.scope,{address,revision})
 const currentRead=readback&&phoneReturnMatches(readback.scope,{address,revision})?readback:null
 const returnedSlot=(operation:string)=>queueReturn?.operation===operation&&phoneReturnMatches(queueReturn.scope,{address,revision})?{returned:{id:queueReturn.requestId,label:queueReturn.status,address:queueReturn.scope.address,revision:queueReturn.scope.revision,sourceId:queueReturn.inputId,status:queueReturn.status,value:JSON.stringify(queueReturn)}}:{}
 return <section aria-label="Phone input sources"><EIFieldAction address={address} revision={revision} sourceId={sourceId} operation="phone.input.read" label="Read shared phone input" hint="Read" disabled={disabled||busy||!supported} pending={isPending('phone.input.read')} presented={!!currentRead} onClick={read} form={{kind:'source-return',source:{id:address,label:'Field',address,revision,sourceId},destination:{id:'native:inputs',label:'Inputs'},...(currentRead?{returned:{id:currentRead.requestId,label:`${currentRead.value.inputs.length} inputs`,address,revision,status:'returned',value:JSON.stringify(currentRead.value)}}:{})}}/>{error&&<p role="alert">{error}</p>}{ack&&<p role="status">{ack}</p>}{retained.map(input=>{const operation=`phone.input.release:${input.id}`;return <EIFieldAction key={input.id} address={address} revision={revision} sourceId={input.id} operation={operation} label={`Release retained source ${input.id} from phone queue`} hint="Release" disabled={disabled||busy} pending={isPending(operation)} onClick={()=>release(input)} form={{kind:'source-return',source:{id:input.id,label:'Retained',sourceId:input.id,value:JSON.stringify(input)},destination:{id:`native:ack:${input.id}`,label:'Queue'},...returnedSlot(operation)}}/>})}{rejections.map((code,index)=><p key={index} role="status">{code}</p>)}{inputs.map(input=><details key={input.id}><summary>{input.channel} · {input.id}</summary><pre>{input.text}</pre>{phoneInputAdmissionError(input)&&<p>{phoneInputAdmissionError(input)}</p>}<EIFieldAction address={address} revision={revision} sourceId={input.id} operation={`phone.input.stage:${input.id}`} label="Stage exact input" hint="Stage" disabled={disabled||used.includes(input.id)||!!phoneInputAdmissionError(input)} onClick={()=>{onChoose(input)}} form={{kind:'transition',before:{id:address,label:'Field',address,revision,sourceId},proposed:{id:input.id,label:'Input',sourceId:input.id,value:input.text}}}/><EIFieldAction address={address} revision={revision} sourceId={input.id} operation={`phone.input.discard:${input.id}`} label="Discard this source from phone queue" hint="Discard" disabled={disabled||busy} pending={isPending(`phone.input.discard:${input.id}`)} onClick={()=>discard(input)} form={{kind:'source-return',source:{id:input.id,label:'Input',sourceId:input.id,value:input.text},destination:{id:`native:discard:${input.id}`,label:'Queue'},...returnedSlot(`phone.input.discard:${input.id}`)}}/></details>)}</section>
}
