import {useMemo,useState} from 'react'
import {EI_LIMITS,type EILedger} from './model/ei-engine'
import type {EIPageAttempt} from './model/ei-session'
import {inspectEIWholeField} from './model/ei-whole-field-coverage'
import {readEIDiscoverySteps} from './model/ei-discovery'
import {parseEILedgerSource,compileEILedgerProgram} from './model/ei-ledger-language'
import inventory from '../docs/FRACTURE-FIELD-INVENTORY.json'
import nativeEvidence from '../native/ei-core/size-report.json'
/** Read-only proof projection of retained sources and returned state.
 * Opening it creates no assertion, engine transaction or external upload. */
export function EIProofDocument({ledger,userRoot,tickets}:{ledger:EILedger;userRoot:string;tickets:readonly EIPageAttempt[]}){
 const [expanded,setExpanded]=useState(false)
 const whole=useMemo(()=>inspectEIWholeField(ledger,userRoot),[ledger,userRoot])
 const language=useMemo(()=>{const clauses=inventory.retained_binary_relations;return compileEILedgerProgram([parseEILedgerSource({recordAddress:'model/inventory-root',sourceId:`public-inventory:${inventory.source_revision}`,revision:0,frameId:'published-retained-clause-audit',text:JSON.stringify(clauses)},{pointers:clauses.map((_,index)=>`/${index}`)})])},[])
 const clauses=language.asts.flatMap(ast=>ast.clauses),rules=clauses.filter(clause=>clause.syntax.kind==='comparison-rule')
 const steps=useMemo(()=>readEIDiscoverySteps(ledger),[ledger])
 return <details className="ei-proof-document" data-proof-revision={ledger.revision} onToggle={event=>setExpanded(event.currentTarget.open)}><summary>Mechanism proof · sources, tickets, receipts and quotas</summary>
 {expanded&&<article aria-label="Mechanism proof document"><h2>Retained evidence</h2><details><summary>The claim and criterion</summary><p>User claim: “I can script binary life.” Testing direction: “the points that make it false, but by binary relationships.”</p><p>Tests challenge the implemented relations with contradictions, malformed bytes, stale sources, interrupted returns and capacity failures. Untested and opaque relations remain unresolved; a finite passing test set does not establish the whole claim.</p><a href="https://github.com/Acidfang/EverthingFromNothing/blob/main/docs/MECHANISM-CLAIM-EVIDENCE.md" target="_blank" rel="noreferrer">Supporting requirements and test scope</a></details><p>{userRoot} · committed revision {ledger.revision}</p>
 <p>{whole.addresses.length} retained addresses · {whole.relations.length} retained links · {ledger.receipts.length} receipts · {tickets.length} uncommitted tickets</p>
 <details><summary>Build verification · 0.1.12</summary><p>691 model tests passed. One test checks 768 finite witness/query combinations against the independent prior interpreter. TypeScript, build and 12 release audits passed locally.</p><p>Portable ATmega328P build: {nativeEvidence.flash_bytes} flash bytes; {nativeEvidence.static_sram_bytes} static SRAM bytes. Host tests and sanitizers passed. Board execution has not been tested.</p><p>The tested behavior covers supplied input, retained history, source-bound response and defined Difference handling. The proof scope stays with those observable behaviors.</p><a href="https://github.com/Acidfang/EverthingFromNothing/blob/main/qa/field-release-0.1.12.json" target="_blank" rel="noreferrer">Exact release and renderer evidence</a></details><details><summary>Source → binary library → returned conclusion</summary><p>The public source has {clauses.length} clauses, {rules.length} admitted rule forms and {language.opaqueClauses.length} opaque clauses. The compiler is hosted; its own compiler is not self-compiled.</p>{rules.map(rule=><pre key={rule.id}>{JSON.stringify(rule,null,2)}</pre>)}<p>{language.evaluations.length} witnessed evaluations return {language.evaluations.reduce((n,item)=>n+item.result.proofs.length,0)} symbolic proofs. This inspection does not commit them to the user field.</p><a href="https://github.com/Acidfang/EverthingFromNothing/blob/main/docs/MECHANISM-EXECUTION-COVERAGE.md" target="_blank" rel="noreferrer">Executable coverage and reproduction</a></details>
 <details><summary>Actual committed returns</summary>{ledger.receipts.map(receipt=><details key={receipt.id}><summary>{receipt.id} · {receipt.status} · {receipt.scope}</summary><pre>{JSON.stringify(receipt,null,2)}</pre></details>)}</details>
 <details><summary>Uncommitted tickets</summary>{tickets.map((ticket,index)=><pre key={`${ticket.transactionId}/${index}`}>{JSON.stringify(ticket,null,2)}</pre>)}</details>
 <details><summary>Quotas and observed usage</summary><p>Records {ledger.records.length}/{EI_LIMITS.records}; receipts {ledger.receipts.length}/{EI_LIMITS.receipts}. These are configured bounds and observed counts.</p><pre>{JSON.stringify(EI_LIMITS,null,2)}</pre>{steps.map(step=><details key={step.address}><summary>{step.address} · {step.data.batch.status}</summary><pre>{JSON.stringify({sourceAddress:step.data.batch.address,sourceRevision:step.data.batch.revision,receipt:step.receiptId,reportedProgress:step.data.batch.progress,providerLimits:step.data.batch.limits,diagnostics:step.data.batch.diagnostics,logicalSnapshotRevision:step.data.logicalSnapshotRevision,physicalSimultaneity:false},null,2)}</pre></details>)}</details>
 <details><summary>Open coverage</summary><p>General meaning and intent interpretation, the remaining opaque clauses, external spooling, full source-derived geometry and private cross-device transport remain open. The portable core is built separately; this JavaScript runtime does not yet call it.</p><pre>{JSON.stringify({unknownEndpoints:whole.unresolvedEndpoints,unreachedAddresses:whole.unreachedAddresses,wholeExternalSourceEstablished:false},null,2)}</pre><a href="https://github.com/Acidfang/EverthingFromNothing/blob/main/docs/FRACTURE-THREAD-CHRONICLE.md" target="_blank" rel="noreferrer">Published Chronicle</a></details>
 </article>}</details>
}
