import { useEffect, useMemo, useRef, useState } from "react"
import { FirstActExplorer } from "./model/explorer.ts"
import "./infinity.css"

type Channel = "NONE" | "FILTER" | "ISOLATE" | "RECONSTRUCT"
type FieldAddress = { root:string; grain:number; act:number; x:number; y:number; z:number; depth:number; channel:Channel; subject?:string }
type FieldNode = { id:string; x:number; y:number; z:number; generation:number; address:string }
type Whole = { root:string; zero:FieldAddress; nodes:FieldNode[]; channel:Channel; scope:string; enactment:string; provenance:string[] }

const ROOT="FAMILY/NOTODUS/ZERO"
const DEFAULT_ADDRESS:FieldAddress={root:ROOT,grain:0,act:0,x:0,y:0,z:0,depth:2,channel:"NONE"}
const DIRECTIONS=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]] as const
function readAddress():FieldAddress{const source=new URLSearchParams(location.search).get("field")||new URLSearchParams(location.hash.replace(/^#/,"")).get("field");if(!source)return DEFAULT_ADDRESS;try{return{...DEFAULT_ADDRESS,...JSON.parse(decodeURIComponent(source))}}catch{return DEFAULT_ADDRESS}}
function writeAddress(address:FieldAddress){history.replaceState(null,"",`${location.pathname}#field=${encodeURIComponent(JSON.stringify(address))}`)}
function nodeAddress(g:number,x:number,y:number,z:number){return `${ROOT}/FIELD/${g}/X${x}/Y${y}/Z${z}`}
function buildNodes(depth:number):FieldNode[]{const seen=new Map<string,FieldNode>();const add=(g:number,x:number,y:number,z:number)=>{const id=`${x}:${y}:${z}`;if(!seen.has(id))seen.set(id,{id,x,y,z,generation:g,address:nodeAddress(g,x,y,z)})};add(0,0,0,0);for(let g=1;g<=depth;g++){for(const n of [...seen.values()].filter(n=>n.generation===g-1)){for(const[dX,dY,dZ]of DIRECTIONS)add(g,n.x+dX,n.y+dY,n.z+dZ)}}return [...seen.values()]}
function project(n:FieldNode,w:number,h:number,scale:number){const px=w/2+(n.x-n.z*.55)*scale;const py=h/2+(n.y*.82+n.z*.45)*scale;return{x:px,y:py}}
function download(name:string,type:string,data:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}

export function InfinityApp(){
 const explorer=useMemo(()=>new FirstActExplorer(),[])
 const[address,setAddress]=useState<FieldAddress>(()=>readAddress())
 const[frame,setFrame]=useState(()=>explorer.frame())
 const[message,setMessage]=useState("Whole addressed")
 const[spoken,setSpoken]=useState("")
 const canvas=useRef<HTMLCanvasElement>(null)
 const nodes=useMemo(()=>buildNodes(Math.max(1,Math.min(5,address.depth))),[address.depth])
 const whole=useMemo<Whole>(()=>({root:ROOT,zero:address,nodes,channel:address.channel,scope:"Complete addressable field: node, relation, lineage, provenance and presentation remain inside the carried Whole.",enactment:address.channel==="NONE"?"DO NOTHING -> MOVE ON":"Carry Whole -> address Difference -> "+address.channel+" -> return resolved Whole",provenance:["DEFAULT/WHOLE/PIXEL_ARRAY_MAP",address.root,nodeAddress(address.grain,address.x,address.y,address.z)]}),[address,nodes])
 const apply=(next:FieldAddress)=>{setAddress(next);writeAddress(next);explorer.setQueryDepth(Math.max(0,Math.min(4,next.depth)));setFrame(explorer.frame());setMessage(`${next.channel}: Whole at ${next.x},${next.y},${next.z}`)}
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const resize=()=>{const r=c.getBoundingClientRect();c.width=Math.max(1,Math.floor(r.width*devicePixelRatio));c.height=Math.max(1,Math.floor(r.height*devicePixelRatio));ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);ctx.fillStyle="#050708";ctx.fillRect(0,0,w,h);const scale=Math.max(24,Math.min(w,h)/(address.depth*5+5));const p=new Map(nodes.map(n=>[n.id,project(n,w,h,scale)]));ctx.strokeStyle="rgba(229,173,86,.18)";ctx.lineWidth=1;for(const n of nodes){for(const[dX,dY,dZ]of DIRECTIONS){const q=nodes.find(m=>m.x===n.x+dX&&m.y===n.y+dY&&m.z===n.z+dZ);if(!q)continue;const a=p.get(n.id)!,b=p.get(q.id)!;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}for(const n of nodes){const q=p.get(n.id)!;const active=n.x===address.x&&n.y===address.y&&n.z===address.z;ctx.beginPath();ctx.arc(q.x,q.y,active?5:2.2,0,Math.PI*2);ctx.fillStyle=active?"#eeeade":"#e5ad56";ctx.fill()}const z=p.get("0:0:0");if(z){ctx.strokeStyle="#69d5ce";ctx.beginPath();ctx.arc(z.x,z.y,10,0,Math.PI*2);ctx.stroke()}};resize();addEventListener("resize",resize);return()=>removeEventListener("resize",resize)},[nodes,address])
 useEffect(()=>{const handler=(e:MessageEvent)=>{if(e.data?.type==="INFINITY_FIELD_ADDRESS")apply({...address,...e.data.address})};addEventListener("message",handler);const bc="BroadcastChannel"in window?new BroadcastChannel("infinity-field"):null;bc?.addEventListener("message",handler);return()=>{removeEventListener("message",handler);bc?.close()}},[address])
 const requestMedia=async(kind:"microphone"|"camera")=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:kind==="microphone",video:kind==="camera"});stream.getTracks().forEach(t=>t.stop());setMessage(`${kind} available at this field address`)}catch{setMessage(`${kind} unavailable or permission not granted`)}}
 const requestUsb=async()=>{try{const usb=(navigator as Navigator&{usb?:{requestDevice(options:{filters:unknown[]}):Promise<unknown>}}).usb;if(!usb)throw new Error();await usb.requestDevice({filters:[]});setMessage("USB addressed") }catch{setMessage("USB unavailable or permission not granted")}}
 const speak=()=>{if(!("speechSynthesis"in window)){setMessage("Speech output unavailable");return}const text=spoken||`Infinity field ${address.x} ${address.y} ${address.z}`;speechSynthesis.speak(new SpeechSynthesisUtterance(text));setMessage("Speech output enacted")}
 const spawn=()=>{const child=open(location.href,"infinity-field-map","popup,width=1100,height=800");if(child){setMessage("Field surface spawned");setTimeout(()=>child.postMessage({type:"INFINITY_FIELD_ADDRESS",address},location.origin),300)}else setMessage("Spawn blocked; webpage remains the field surface")}
 const exportWhole=()=>download("infinity-whole.json","application/json",JSON.stringify({whole,frame},null,2))
 return <main className="infinity-map"><header className="infinity-hud"><strong>INFINITY · WHOLE/PIXEL_ARRAY_MAP</strong><span>{message}</span><button onClick={()=>document.documentElement.requestFullscreen?.()}>Fullscreen</button></header><section className="infinity-field" aria-label="Addressable Infinity field map"><canvas ref={canvas} className="infinity-canvas"/><div className="infinity-centre"><div className="infinity-zero">0</div><div className="infinity-address">{nodeAddress(address.grain,address.x,address.y,address.z)}</div><div className="infinity-stats">{nodes.length} addressed states · {frame.recursiveQuery.relationCount} model relations · Whole carried</div></div><div className="infinity-channels">{(["FILTER","ISOLATE","RECONSTRUCT","NONE"] as Channel[]).map(channel=><button key={channel} data-active={address.channel===channel} onClick={()=>apply({...address,channel})}>{channel==="NONE"?"DO NOTHING / MOVE ON":channel}</button>)}</div></section><aside className="infinity-controls"><label>Field depth <input type="range" min="1" max="5" value={address.depth} onChange={e=>apply({...address,depth:Number(e.target.value)})}/></label><button onClick={()=>apply({...address,x:address.x+1})}>+X</button><button onClick={()=>apply({...address,x:address.x-1})}>−X</button><button onClick={()=>apply({...address,y:address.y+1})}>+Y</button><button onClick={()=>apply({...address,y:address.y-1})}>−Y</button><button onClick={()=>apply({...address,z:address.z+1})}>+Z</button><button onClick={()=>apply({...address,z:address.z-1})}>−Z</button><button onClick={()=>requestMedia("microphone")}>Microphone</button><button onClick={()=>requestMedia("camera")}>Camera</button><button onClick={requestUsb}>USB</button><input aria-label="Speech text" value={spoken} onChange={e=>setSpoken(e.target.value)} placeholder="Addressed speech"/><button onClick={speak}>Speak</button><button onClick={spawn}>Spawn field surface</button><button onClick={exportWhole}>Save Whole</button><button onClick={()=>navigator.clipboard?.writeText(location.href)}>Copy field address</button></aside></main>
}
