import {useEffect,useRef,useState,type RefObject} from 'react'
import {createEIFitImprovementState,proposeEIFitImprovement,commitEIFitImprovement,serializeEIFitImprovement,restoreEIFitImprovement,type EIFitEvidence,type EIFitProposal,type EIFitCamera,type EIFitReadback} from './model/ei-fit-improvement'
function sameContext(a:EIFitEvidence,b:EIFitEvidence){const normalize=(v:EIFitEvidence)=>[v.sourceSnapshot,v.viewport.width,v.viewport.height,[...v.objects].sort((a,b)=>a.address.localeCompare(b.address)).map(o=>[o.address,o.revision,o.sourceId,o.bounds.left,o.bounds.right,o.bounds.top,o.bounds.bottom])];return JSON.stringify(normalize(a))===JSON.stringify(normalize(b))}
export function useEIFitImprovement(evidence:EIFitEvidence,svg:RefObject<SVGSVGElement|null>,apply:(view:EIFitCamera)=>void){
 const [state,setState]=useState(createEIFitImprovementState),[pending,setPending]=useState<EIFitProposal|null>(null),[status,setStatus]=useState('idle')
 const live=useRef(evidence);live.current=evidence
 const improve=()=>{if(pending)return;const result=proposeEIFitImprovement(state,evidence);setStatus(result.status);if(result.proposal){setPending(result.proposal);apply(result.proposal.camera)}}
 useEffect(()=>{if(!pending)return;let first=0,second=0,cancelled=false;first=requestAnimationFrame(()=>{second=requestAnimationFrame(()=>{if(cancelled)return;let readback:EIFitReadback|null=null;const surface=svg.current
  try{if(!surface)throw new Error('Missing field');const viewport=surface.getBoundingClientRect();const objects=[...surface.querySelectorAll<SVGGElement>('[data-field-node]')].filter(node=>Number(node.getAttribute('opacity'))>0&&node.getAttribute('aria-hidden')!=='true').map(node=>{const path=node.querySelector<SVGGraphicsElement>('[data-world-outline]');if(!path)throw new Error('Missing rendered object');const revision=node.getAttribute('data-render-revision');if(revision===null||!/^\d+$/.test(revision))throw new Error('Missing returned revision');const box=path.getBBox(),position=/^translate\(([-+\d.eE]+) ([-+\d.eE]+)\)$/.exec(node.getAttribute('transform')??'');if(!position)throw new Error('Unbound rendered transform');const x=Number(position[1]),y=Number(position[2]);return {address:node.getAttribute('data-field-node')!,revision:Number(revision),sourceId:node.getAttribute('data-render-source')!,bounds:{left:x+box.x,right:x+box.x+box.width,top:y+box.y,bottom:y+box.y+box.height}}});readback={proposalId:pending.proposalId,sourceSnapshot:surface.getAttribute('data-field-source-snapshot')??'',viewport:{width:viewport.width,height:viewport.height},viewBox:surface.getAttribute('viewBox')??'',objects}
  }catch{/* missing evidence remains missing */}
  const result=commitEIFitImprovement(state,pending,live.current,readback);setState(result.state);setStatus(result.status);setPending(null)
  if(result.status!=='committed'&&result.status!=='duplicate'&&sameContext(live.current,pending.before)&&live.current.view.x===pending.camera.x&&live.current.view.y===pending.camera.y&&live.current.view.zoom===pending.camera.zoom)apply(pending.before.view)
 })});return()=>{cancelled=true;cancelAnimationFrame(first);cancelAnimationFrame(second)}},[pending])
 return {state,pending,status,improve,save:()=>serializeEIFitImprovement(state),restore:(value:string,applyCamera=false)=>{const result=restoreEIFitImprovement(value,live.current);if(result.status==='invalid')throw new Error(result.reasons.join('; '));setState(result.state);if(applyCamera&&result.applicableCamera)apply(result.applicableCamera);setStatus(result.status)}}
}
